# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\TkgDesignerTools_Legacy\Maya\scripts\Project_Gallop\glp_arrange_vtx_order\glp_arrange_vtx_order_ui.ui'
#
# Created: Thu Apr  8 18:18:23 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.foward_x = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foward_x.sizePolicy().hasHeightForWidth())
        self.foward_x.setSizePolicy(sizePolicy)
        self.foward_x.setObjectName("foward_x")
        self.horizontalLayout.addWidget(self.foward_x)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.foward_y = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foward_y.sizePolicy().hasHeightForWidth())
        self.foward_y.setSizePolicy(sizePolicy)
        self.foward_y.setObjectName("foward_y")
        self.horizontalLayout_2.addWidget(self.foward_y)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.foward_z = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foward_z.sizePolicy().hasHeightForWidth())
        self.foward_z.setSizePolicy(sizePolicy)
        self.foward_z.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.foward_z.setObjectName("foward_z")
        self.horizontalLayout_3.addWidget(self.foward_z)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(70, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.mesh_direction_x = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mesh_direction_x.sizePolicy().hasHeightForWidth())
        self.mesh_direction_x.setSizePolicy(sizePolicy)
        self.mesh_direction_x.setObjectName("mesh_direction_x")
        self.horizontalLayout_8.addWidget(self.mesh_direction_x)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.mesh_direction_y = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mesh_direction_y.sizePolicy().hasHeightForWidth())
        self.mesh_direction_y.setSizePolicy(sizePolicy)
        self.mesh_direction_y.setObjectName("mesh_direction_y")
        self.horizontalLayout_9.addWidget(self.mesh_direction_y)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.mesh_direction_z = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mesh_direction_z.sizePolicy().hasHeightForWidth())
        self.mesh_direction_z.setSizePolicy(sizePolicy)
        self.mesh_direction_z.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mesh_direction_z.setObjectName("mesh_direction_z")
        self.horizontalLayout_10.addWidget(self.mesh_direction_z)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMinimumSize(QtCore.QSize(70, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.unite_direction_x = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unite_direction_x.sizePolicy().hasHeightForWidth())
        self.unite_direction_x.setSizePolicy(sizePolicy)
        self.unite_direction_x.setObjectName("unite_direction_x")
        self.horizontalLayout_13.addWidget(self.unite_direction_x)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.unite_direction_y = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unite_direction_y.sizePolicy().hasHeightForWidth())
        self.unite_direction_y.setSizePolicy(sizePolicy)
        self.unite_direction_y.setObjectName("unite_direction_y")
        self.horizontalLayout_14.addWidget(self.unite_direction_y)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.unite_direction_z = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unite_direction_z.sizePolicy().hasHeightForWidth())
        self.unite_direction_z.setSizePolicy(sizePolicy)
        self.unite_direction_z.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.unite_direction_z.setObjectName("unite_direction_z")
        self.horizontalLayout_15.addWidget(self.unite_direction_z)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setMinimumSize(QtCore.QSize(70, 0))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.mesh_preset = QtWidgets.QComboBox(self.groupBox)
        self.mesh_preset.setMinimumSize(QtCore.QSize(300, 0))
        self.mesh_preset.setObjectName("mesh_preset")
        self.horizontalLayout_16.addWidget(self.mesh_preset)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.ordered_by = QtWidgets.QComboBox(self.groupBox_2)
        self.ordered_by.setMinimumSize(QtCore.QSize(300, 0))
        self.ordered_by.setObjectName("ordered_by")
        self.horizontalLayout_17.addWidget(self.ordered_by)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.auto_button = QtWidgets.QPushButton(self.groupBox_2)
        self.auto_button.setObjectName("auto_button")
        self.verticalLayout_3.addWidget(self.auto_button)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.create_reorder_mesh = QtWidgets.QPushButton(self.groupBox_3)
        self.create_reorder_mesh.setObjectName("create_reorder_mesh")
        self.verticalLayout_4.addWidget(self.create_reorder_mesh)
        self.create_reorder_meshes = QtWidgets.QPushButton(self.groupBox_3)
        self.create_reorder_meshes.setObjectName("create_reorder_meshes")
        self.verticalLayout_4.addWidget(self.create_reorder_meshes)
        self.combine_meshes = QtWidgets.QPushButton(self.groupBox_3)
        self.combine_meshes.setObjectName("combine_meshes")
        self.verticalLayout_4.addWidget(self.combine_meshes)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "メッシュ情報設定", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "正面方向", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "X:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Y:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Z:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "メッシュの流れ", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "X:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Y:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Z:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "結合方向", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "X:", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Y:", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Z:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "設定プリセット", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "一括処理", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "面の並びの判定方法", None, -1))
        self.auto_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択面から自動で頂点番号を修正したメッシュを作成", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "個別処理（一括処理で上手くいかない場合）", None, -1))
        self.create_reorder_mesh.setText(QtWidgets.QApplication.translate("MainWindow", "選択面を分離して頂点番号を修正", None, -1))
        self.create_reorder_meshes.setText(QtWidgets.QApplication.translate("MainWindow", "面の列ごとに分割して頂点番号を修正したメッシュ群を作成", None, -1))
        self.combine_meshes.setText(QtWidgets.QApplication.translate("MainWindow", "選択順にメッシュを結合（Mesh > Combine）", None, -1))

