# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\sourcetree\techart_stage\inhouse\maya\share\scripts\ui_CreateAssetFolder.ui'
#
# Created: Thu Oct 14 18:45:29 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(550, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(550, 500))
        Form.setMaximumSize(QtCore.QSize(550, 500))
        Form.setMouseTracking(False)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(5, 10, 101, 16))
        self.label_5.setObjectName("label_5")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(10, 130, 531, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 61, 531, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 335, 16))
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 531, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(10, 229, 531, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pb_mkdir = QtWidgets.QPushButton(Form)
        self.pb_mkdir.setGeometry(QtCore.QRect(10, 460, 531, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_mkdir.sizePolicy().hasHeightForWidth())
        self.pb_mkdir.setSizePolicy(sizePolicy)
        self.pb_mkdir.setObjectName("pb_mkdir")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 531, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.le_local_dir = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_local_dir.sizePolicy().hasHeightForWidth())
        self.le_local_dir.setSizePolicy(sizePolicy)
        self.le_local_dir.setMinimumSize(QtCore.QSize(300, 0))
        self.le_local_dir.setMaximumSize(QtCore.QSize(400, 16777215))
        self.le_local_dir.setObjectName("le_local_dir")
        self.horizontalLayout.addWidget(self.le_local_dir)
        self.pb_select_local_dir = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_select_local_dir.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_select_local_dir.sizePolicy().hasHeightForWidth())
        self.pb_select_local_dir.setSizePolicy(sizePolicy)
        self.pb_select_local_dir.setMaximumSize(QtCore.QSize(80, 20))
        self.pb_select_local_dir.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pb_select_local_dir.setCheckable(False)
        self.pb_select_local_dir.setObjectName("pb_select_local_dir")
        self.horizontalLayout.addWidget(self.pb_select_local_dir)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 238, 531, 212))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lw_sub_folders = QtWidgets.QListWidget(self.layoutWidget1)
        self.lw_sub_folders.setEnabled(True)
        self.lw_sub_folders.setMovement(QtWidgets.QListView.Static)
        self.lw_sub_folders.setFlow(QtWidgets.QListView.TopToBottom)
        self.lw_sub_folders.setProperty("isWrapping", False)
        self.lw_sub_folders.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.lw_sub_folders.setSpacing(2)
        self.lw_sub_folders.setViewMode(QtWidgets.QListView.ListMode)
        self.lw_sub_folders.setModelColumn(0)
        self.lw_sub_folders.setUniformItemSizes(False)
        self.lw_sub_folders.setWordWrap(False)
        self.lw_sub_folders.setSelectionRectVisible(False)
        self.lw_sub_folders.setObjectName("lw_sub_folders")
        item = QtWidgets.QListWidgetItem(self.lw_sub_folders)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        item = QtWidgets.QListWidgetItem(self.lw_sub_folders)
        item.setCheckState(QtCore.Qt.Unchecked)
        item = QtWidgets.QListWidgetItem(self.lw_sub_folders)
        item.setCheckState(QtCore.Qt.Unchecked)
        item = QtWidgets.QListWidgetItem(self.lw_sub_folders)
        item.setCheckState(QtCore.Qt.Unchecked)
        item = QtWidgets.QListWidgetItem(self.lw_sub_folders)
        item.setCheckState(QtCore.Qt.Unchecked)
        item = QtWidgets.QListWidgetItem(self.lw_sub_folders)
        item.setCheckState(QtCore.Qt.Unchecked)
        item = QtWidgets.QListWidgetItem(self.lw_sub_folders)
        item.setCheckState(QtCore.Qt.Unchecked)
        item = QtWidgets.QListWidgetItem(self.lw_sub_folders)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.verticalLayout.addWidget(self.lw_sub_folders)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 149, 531, 62))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.le_export_dir = QtWidgets.QLineEdit(self.layoutWidget2)
        self.le_export_dir.setReadOnly(True)
        self.le_export_dir.setObjectName("le_export_dir")
        self.verticalLayout_2.addWidget(self.le_export_dir)
        self.cb_wanna_open_exported_folder = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_wanna_open_exported_folder.setChecked(True)
        self.cb_wanna_open_exported_folder.setObjectName("cb_wanna_open_exported_folder")
        self.verticalLayout_2.addWidget(self.cb_wanna_open_exported_folder)
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 90, 531, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.tl_asset_name = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tl_asset_name.sizePolicy().hasHeightForWidth())
        self.tl_asset_name.setSizePolicy(sizePolicy)
        self.tl_asset_name.setMinimumSize(QtCore.QSize(300, 0))
        self.tl_asset_name.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tl_asset_name.setFrame(True)
        self.tl_asset_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tl_asset_name.setClearButtonEnabled(False)
        self.tl_asset_name.setObjectName("tl_asset_name")
        self.horizontalLayout_3.addWidget(self.tl_asset_name)
        self.pb_set_asset_name = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_set_asset_name.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pb_set_asset_name.setObjectName("pb_set_asset_name")
        self.horizontalLayout_3.addWidget(self.pb_set_asset_name)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_local_dir, self.pb_select_local_dir)
        Form.setTabOrder(self.pb_select_local_dir, self.tl_asset_name)
        Form.setTabOrder(self.tl_asset_name, self.pb_set_asset_name)
        Form.setTabOrder(self.pb_set_asset_name, self.le_export_dir)
        Form.setTabOrder(self.le_export_dir, self.cb_wanna_open_exported_folder)
        Form.setTabOrder(self.cb_wanna_open_exported_folder, self.lw_sub_folders)
        Form.setTabOrder(self.lw_sub_folders, self.pb_mkdir)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "CreateAssetFolder", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" text-decoration: underline;\">1)ディレクトリを設定</span></p></body></html>", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" text-decoration: underline;\">2 ) アセット名を入力（作成する親フォルダ名になります） 例） prj_1001</span></p></body></html>", None, -1))
        self.pb_mkdir.setText(QtWidgets.QApplication.translate("Form", "アセットフォルダを作成", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "作業フォルダ", None, -1))
        self.pb_select_local_dir.setText(QtWidgets.QApplication.translate("Form", "フォルダを選択", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" text-decoration: underline;\">4 ) 作成するサブフォルダを選択</span></p></body></html>", None, -1))
        self.lw_sub_folders.setSortingEnabled(False)
        __sortingEnabled = self.lw_sub_folders.isSortingEnabled()
        self.lw_sub_folders.setSortingEnabled(False)
        self.lw_sub_folders.item(0).setText(QtWidgets.QApplication.translate("Form", "scene", None, -1))
        self.lw_sub_folders.item(1).setText(QtWidgets.QApplication.translate("Form", "sourceimages", None, -1))
        self.lw_sub_folders.item(2).setText(QtWidgets.QApplication.translate("Form", "Materials", None, -1))
        self.lw_sub_folders.item(3).setText(QtWidgets.QApplication.translate("Form", "Meshes", None, -1))
        self.lw_sub_folders.item(4).setText(QtWidgets.QApplication.translate("Form", "Motions", None, -1))
        self.lw_sub_folders.item(5).setText(QtWidgets.QApplication.translate("Form", "Prefab", None, -1))
        self.lw_sub_folders.item(6).setText(QtWidgets.QApplication.translate("Form", "Prefabs", None, -1))
        self.lw_sub_folders.item(7).setText(QtWidgets.QApplication.translate("Form", "Textures", None, -1))
        self.lw_sub_folders.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" text-decoration: underline;\">3 ) 出力先を確認</span></p></body></html>", None, -1))
        self.cb_wanna_open_exported_folder.setText(QtWidgets.QApplication.translate("Form", "出力後にフォルダをエクスプローラーで開く", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "アセット名   ", None, -1))
        self.pb_set_asset_name.setText(QtWidgets.QApplication.translate("Form", "決定", None, -1))

