# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_lightmap_maker\ui\glp_lightmap_maker_window.ui'
#
# Created: Fri Oct 14 12:17:43 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 986)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.bake_layer_node_custom_list = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bake_layer_node_custom_list.sizePolicy().hasHeightForWidth())
        self.bake_layer_node_custom_list.setSizePolicy(sizePolicy)
        self.bake_layer_node_custom_list.setMinimumSize(QtCore.QSize(370, 150))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.bake_layer_node_custom_list.setFont(font)
        self.bake_layer_node_custom_list.setObjectName("bake_layer_node_custom_list")
        self.verticalLayout_11.addWidget(self.bake_layer_node_custom_list)
        self.verticalLayout_5.addLayout(self.verticalLayout_11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.create_bake_layer_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_bake_layer_label.sizePolicy().hasHeightForWidth())
        self.create_bake_layer_label.setSizePolicy(sizePolicy)
        self.create_bake_layer_label.setMinimumSize(QtCore.QSize(0, 0))
        self.create_bake_layer_label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.create_bake_layer_label.setObjectName("create_bake_layer_label")
        self.horizontalLayout_6.addWidget(self.create_bake_layer_label)
        self.bake_layer_suffix_line = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bake_layer_suffix_line.sizePolicy().hasHeightForWidth())
        self.bake_layer_suffix_line.setSizePolicy(sizePolicy)
        self.bake_layer_suffix_line.setObjectName("bake_layer_suffix_line")
        self.horizontalLayout_6.addWidget(self.bake_layer_suffix_line)
        self.bake_layer_create_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bake_layer_create_button.sizePolicy().hasHeightForWidth())
        self.bake_layer_create_button.setSizePolicy(sizePolicy)
        self.bake_layer_create_button.setObjectName("bake_layer_create_button")
        self.horizontalLayout_6.addWidget(self.bake_layer_create_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.bake_obj_node_list = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bake_obj_node_list.sizePolicy().hasHeightForWidth())
        self.bake_obj_node_list.setSizePolicy(sizePolicy)
        self.bake_obj_node_list.setMinimumSize(QtCore.QSize(0, 150))
        self.bake_obj_node_list.setObjectName("bake_obj_node_list")
        self.verticalLayout.addWidget(self.bake_obj_node_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bake_obj_add_button = QtWidgets.QPushButton(self.groupBox)
        self.bake_obj_add_button.setObjectName("bake_obj_add_button")
        self.horizontalLayout.addWidget(self.bake_obj_add_button)
        self.bake_obj_rem_button = QtWidgets.QPushButton(self.groupBox)
        self.bake_obj_rem_button.setObjectName("bake_obj_rem_button")
        self.horizontalLayout.addWidget(self.bake_obj_rem_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.bake_type_tex_radio = QtWidgets.QRadioButton(self.groupBox_3)
        self.bake_type_tex_radio.setEnabled(True)
        self.bake_type_tex_radio.setChecked(True)
        self.bake_type_tex_radio.setObjectName("bake_type_tex_radio")
        self.horizontalLayout_4.addWidget(self.bake_type_tex_radio)
        self.bake_type_vtx_radio = QtWidgets.QRadioButton(self.groupBox_3)
        self.bake_type_vtx_radio.setObjectName("bake_type_vtx_radio")
        self.horizontalLayout_4.addWidget(self.bake_type_vtx_radio)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.setting_vertical_layout = QtWidgets.QVBoxLayout()
        self.setting_vertical_layout.setObjectName("setting_vertical_layout")
        self.info_bake_setting_area = QtWidgets.QScrollArea(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_bake_setting_area.sizePolicy().hasHeightForWidth())
        self.info_bake_setting_area.setSizePolicy(sizePolicy)
        self.info_bake_setting_area.setMinimumSize(QtCore.QSize(0, 130))
        self.info_bake_setting_area.setMaximumSize(QtCore.QSize(16777215, 130))
        self.info_bake_setting_area.setWidgetResizable(True)
        self.info_bake_setting_area.setObjectName("info_bake_setting_area")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 564, 128))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.info_bake_setting_label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.info_bake_setting_label_2.setText("")
        self.info_bake_setting_label_2.setObjectName("info_bake_setting_label_2")
        self.verticalLayout_8.addWidget(self.info_bake_setting_label_2)
        self.info_bake_setting_area.setWidget(self.scrollAreaWidgetContents_4)
        self.setting_vertical_layout.addWidget(self.info_bake_setting_area)
        self.verticalLayout_2.addLayout(self.setting_vertical_layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.light_set_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.light_set_line.setObjectName("light_set_line")
        self.horizontalLayout_2.addWidget(self.light_set_line)
        self.light_set_select_button = QtWidgets.QPushButton(self.groupBox_3)
        self.light_set_select_button.setObjectName("light_set_select_button")
        self.horizontalLayout_2.addWidget(self.light_set_select_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.open_render_setting_button = QtWidgets.QPushButton(self.groupBox_3)
        self.open_render_setting_button.setObjectName("open_render_setting_button")
        self.verticalLayout_2.addWidget(self.open_render_setting_button)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.output_legacy_tool_radio = QtWidgets.QRadioButton(self.groupBox_4)
        self.output_legacy_tool_radio.setEnabled(True)
        self.output_legacy_tool_radio.setChecked(True)
        self.output_legacy_tool_radio.setObjectName("output_legacy_tool_radio")
        self.horizontalLayout_7.addWidget(self.output_legacy_tool_radio)
        self.output_new_tool_radio = QtWidgets.QRadioButton(self.groupBox_4)
        self.output_new_tool_radio.setObjectName("output_new_tool_radio")
        self.horizontalLayout_7.addWidget(self.output_new_tool_radio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.use_gi_check = QtWidgets.QCheckBox(self.groupBox_4)
        self.use_gi_check.setObjectName("use_gi_check")
        self.verticalLayout_3.addWidget(self.use_gi_check)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.exe_bake_button = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exe_bake_button.sizePolicy().hasHeightForWidth())
        self.exe_bake_button.setSizePolicy(sizePolicy)
        self.exe_bake_button.setMinimumSize(QtCore.QSize(0, 50))
        self.exe_bake_button.setObjectName("exe_bake_button")
        self.horizontalLayout_8.addWidget(self.exe_bake_button)
        self.exe_test_bake_button = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exe_test_bake_button.sizePolicy().hasHeightForWidth())
        self.exe_test_bake_button.setSizePolicy(sizePolicy)
        self.exe_test_bake_button.setMinimumSize(QtCore.QSize(0, 50))
        self.exe_test_bake_button.setObjectName("exe_test_bake_button")
        self.horizontalLayout_8.addWidget(self.exe_test_bake_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.fbx_export_list = QtWidgets.QListWidget(self.groupBox_5)
        self.fbx_export_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fbx_export_list.setObjectName("fbx_export_list")
        self.horizontalLayout_10.addWidget(self.fbx_export_list)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.add_fbx_export_button = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_fbx_export_button.sizePolicy().hasHeightForWidth())
        self.add_fbx_export_button.setSizePolicy(sizePolicy)
        self.add_fbx_export_button.setObjectName("add_fbx_export_button")
        self.verticalLayout_6.addWidget(self.add_fbx_export_button)
        self.rem_fbx_export_button = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rem_fbx_export_button.sizePolicy().hasHeightForWidth())
        self.rem_fbx_export_button.setSizePolicy(sizePolicy)
        self.rem_fbx_export_button.setObjectName("rem_fbx_export_button")
        self.verticalLayout_6.addWidget(self.rem_fbx_export_button)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.fbx_export_suffix_line = QtWidgets.QLineEdit(self.groupBox_5)
        self.fbx_export_suffix_line.setObjectName("fbx_export_suffix_line")
        self.horizontalLayout_9.addWidget(self.fbx_export_suffix_line)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.export_fbx_button = QtWidgets.QPushButton(self.groupBox_5)
        self.export_fbx_button.setMinimumSize(QtCore.QSize(0, 50))
        self.export_fbx_button.setObjectName("export_fbx_button")
        self.verticalLayout_7.addWidget(self.export_fbx_button)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "TURTLE ベイクレイヤー設定", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "操作するベイクレイヤー", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "ベイクレイヤーの作成：", None, -1))
        self.create_bake_layer_label.setText(QtWidgets.QApplication.translate("MainWindow", "GlpBL_", None, -1))
        self.bake_layer_create_button.setText(QtWidgets.QApplication.translate("MainWindow", "作成", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "ベイク対象のシェイプ", None, -1))
        self.bake_obj_add_button.setText(QtWidgets.QApplication.translate("MainWindow", "追加", None, -1))
        self.bake_obj_rem_button.setText(QtWidgets.QApplication.translate("MainWindow", "削除", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "ベイク設定", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "ベイク方式：", None, -1))
        self.bake_type_tex_radio.setText(QtWidgets.QApplication.translate("MainWindow", "テクスチャ", None, -1))
        self.bake_type_vtx_radio.setText(QtWidgets.QApplication.translate("MainWindow", "頂点カラー", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "使用ライトセット：", None, -1))
        self.light_set_select_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.open_render_setting_button.setText(QtWidgets.QApplication.translate("MainWindow", "レンダーセッティングを開く", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "ベイク実行＆テクスチャ出力", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "出力方式：", None, -1))
        self.output_legacy_tool_radio.setText(QtWidgets.QApplication.translate("MainWindow", "従来のツール合成", None, -1))
        self.output_new_tool_radio.setText(QtWidgets.QApplication.translate("MainWindow", "新しいツール合成", None, -1))
        self.use_gi_check.setText(QtWidgets.QApplication.translate("MainWindow", "GIの有効化", None, -1))
        self.exe_bake_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択しているベイクレイヤーに対してベイク実行", None, -1))
        self.exe_test_bake_button.setText(QtWidgets.QApplication.translate("MainWindow", "テストベイク実行", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "FBX出力", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "出力する親グループ", None, -1))
        self.add_fbx_export_button.setText(QtWidgets.QApplication.translate("MainWindow", "追加", None, -1))
        self.rem_fbx_export_button.setText(QtWidgets.QApplication.translate("MainWindow", "削除", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "出力時のサフィックス：", None, -1))
        self.export_fbx_button.setText(QtWidgets.QApplication.translate("MainWindow", "現在の表示状態でFBXを出力", None, -1))

