# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_lightmap_maker\ui\textures_bake_setting_widget.ui'
#
# Created: Mon Nov 14 17:50:56 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(631, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.uv_set_line = QtWidgets.QLineEdit(Form)
        self.uv_set_line.setObjectName("uv_set_line")
        self.horizontalLayout.addWidget(self.uv_set_line)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.update_uv_set_button = QtWidgets.QPushButton(Form)
        self.update_uv_set_button.setObjectName("update_uv_set_button")
        self.horizontalLayout_4.addWidget(self.update_uv_set_button)
        self.layout_uvs_button = QtWidgets.QPushButton(Form)
        self.layout_uvs_button.setObjectName("layout_uvs_button")
        self.horizontalLayout_4.addWidget(self.layout_uvs_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tex_x_line = QtWidgets.QLineEdit(Form)
        self.tex_x_line.setMinimumSize(QtCore.QSize(80, 0))
        self.tex_x_line.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tex_x_line.setText("")
        self.tex_x_line.setObjectName("tex_x_line")
        self.horizontalLayout_2.addWidget(self.tex_x_line)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.test_tex_x_line = QtWidgets.QLineEdit(Form)
        self.test_tex_x_line.setMinimumSize(QtCore.QSize(80, 0))
        self.test_tex_x_line.setMaximumSize(QtCore.QSize(80, 16777215))
        self.test_tex_x_line.setText("")
        self.test_tex_x_line.setObjectName("test_tex_x_line")
        self.horizontalLayout_2.addWidget(self.test_tex_x_line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.tex_y_line = QtWidgets.QLineEdit(Form)
        self.tex_y_line.setMinimumSize(QtCore.QSize(80, 0))
        self.tex_y_line.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tex_y_line.setText("")
        self.tex_y_line.setObjectName("tex_y_line")
        self.horizontalLayout_3.addWidget(self.tex_y_line)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.test_tex_y_line = QtWidgets.QLineEdit(Form)
        self.test_tex_y_line.setMinimumSize(QtCore.QSize(80, 0))
        self.test_tex_y_line.setMaximumSize(QtCore.QSize(80, 16777215))
        self.test_tex_y_line.setText("")
        self.test_tex_y_line.setObjectName("test_tex_y_line")
        self.horizontalLayout_3.addWidget(self.test_tex_y_line)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.tex_name_line = QtWidgets.QLineEdit(Form)
        self.tex_name_line.setObjectName("tex_name_line")
        self.horizontalLayout_5.addWidget(self.tex_name_line)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "ベイク先のUVセット", None, -1))
        self.update_uv_set_button.setText(QtWidgets.QApplication.translate("Form", "ターゲットのUVセットを更新", None, -1))
        self.layout_uvs_button.setText(QtWidgets.QApplication.translate("Form", "ターゲットのUVを再配置", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "ベイクテクスチャの幅", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "テストサイズ: ", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "ベイクテクスチャの高さ", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "テストサイズ: ", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "ベイクテクスチャ名", None, -1))

