# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_lightmap_maker\ui\vertices_bake_setting_widget.ui'
#
# Created: Mon Nov 14 17:51:03 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

try:
    # Maya 2022-
    from builtins import object
except Exception:
    pass

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(493, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.bake_colort_set_line = QtWidgets.QLineEdit(Form)
        self.bake_colort_set_line.setObjectName("bake_colort_set_line")
        self.horizontalLayout.addWidget(self.bake_colort_set_line)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.open_colorset_editor_button = QtWidgets.QPushButton(Form)
        self.open_colorset_editor_button.setObjectName("open_colorset_editor_button")
        self.horizontalLayout_2.addWidget(self.open_colorset_editor_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.ray_min_line = QtWidgets.QLineEdit(Form)
        self.ray_min_line.setMinimumSize(QtCore.QSize(80, 0))
        self.ray_min_line.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ray_min_line.setText("")
        self.ray_min_line.setObjectName("ray_min_line")
        self.horizontalLayout_3.addWidget(self.ray_min_line)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.test_ray_min_line = QtWidgets.QLineEdit(Form)
        self.test_ray_min_line.setMinimumSize(QtCore.QSize(80, 0))
        self.test_ray_min_line.setMaximumSize(QtCore.QSize(80, 16777215))
        self.test_ray_min_line.setText("")
        self.test_ray_min_line.setObjectName("test_ray_min_line")
        self.horizontalLayout_3.addWidget(self.test_ray_min_line)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.ray_max_line = QtWidgets.QLineEdit(Form)
        self.ray_max_line.setMinimumSize(QtCore.QSize(80, 0))
        self.ray_max_line.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ray_max_line.setText("")
        self.ray_max_line.setObjectName("ray_max_line")
        self.horizontalLayout_4.addWidget(self.ray_max_line)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.test_ray_max_line = QtWidgets.QLineEdit(Form)
        self.test_ray_max_line.setMinimumSize(QtCore.QSize(80, 0))
        self.test_ray_max_line.setMaximumSize(QtCore.QSize(80, 16777215))
        self.test_ray_max_line.setText("")
        self.test_ray_max_line.setObjectName("test_ray_max_line")
        self.horizontalLayout_4.addWidget(self.test_ray_max_line)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "ベイク先のカラーセット", None, -1))
        self.open_colorset_editor_button.setText(QtWidgets.QApplication.translate("Form", "カラーセットエディターを開く", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "MinSampleRays", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "テストサイズ: ", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "MaxSampleRays", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "テストサイズ: ", None, -1))

