# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_copy_key_frame\ui\window.ui'
#
# Created: Tue Nov 14 16:47:15 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 277)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.set_source_obj_button = QtWidgets.QPushButton(self.groupBox)
        self.set_source_obj_button.setMinimumSize(QtCore.QSize(0, 40))
        self.set_source_obj_button.setObjectName("set_source_obj_button")
        self.verticalLayout.addWidget(self.set_source_obj_button)
        self.src_info_label = QtWidgets.QLabel(self.groupBox)
        self.src_info_label.setText("")
        self.src_info_label.setObjectName("src_info_label")
        self.verticalLayout.addWidget(self.src_info_label)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.use_frame_range_check = QtWidgets.QCheckBox(self.groupBox_2)
        self.use_frame_range_check.setObjectName("use_frame_range_check")
        self.horizontalLayout.addWidget(self.use_frame_range_check)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.start_range_label = QtWidgets.QLabel(self.groupBox_2)
        self.start_range_label.setEnabled(True)
        self.start_range_label.setObjectName("start_range_label")
        self.horizontalLayout.addWidget(self.start_range_label)
        self.start_frame_spin = QtWidgets.QSpinBox(self.groupBox_2)
        self.start_frame_spin.setMaximum(10000)
        self.start_frame_spin.setObjectName("start_frame_spin")
        self.horizontalLayout.addWidget(self.start_frame_spin)
        self.end_range_label = QtWidgets.QLabel(self.groupBox_2)
        self.end_range_label.setObjectName("end_range_label")
        self.horizontalLayout.addWidget(self.end_range_label)
        self.end_frame_spin = QtWidgets.QSpinBox(self.groupBox_2)
        self.end_frame_spin.setMaximum(10000)
        self.end_frame_spin.setObjectName("end_frame_spin")
        self.horizontalLayout.addWidget(self.end_frame_spin)
        self.set_range_from_timeline_button = QtWidgets.QPushButton(self.groupBox_2)
        self.set_range_from_timeline_button.setObjectName("set_range_from_timeline_button")
        self.horizontalLayout.addWidget(self.set_range_from_timeline_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.key_frame_copy_button = QtWidgets.QPushButton(self.groupBox_2)
        self.key_frame_copy_button.setMinimumSize(QtCore.QSize(0, 40))
        self.key_frame_copy_button.setObjectName("key_frame_copy_button")
        self.verticalLayout_2.addWidget(self.key_frame_copy_button)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.select_hierarchy_check = QtWidgets.QCheckBox(self.groupBox_3)
        self.select_hierarchy_check.setChecked(True)
        self.select_hierarchy_check.setObjectName("select_hierarchy_check")
        self.verticalLayout_4.addWidget(self.select_hierarchy_check)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "ソースオブジェクトの指定", None, -1))
        self.set_source_obj_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択オブジェクトをソースに指定", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "キーフレームコピー", None, -1))
        self.use_frame_range_check.setText(QtWidgets.QApplication.translate("MainWindow", "フレームを指定", None, -1))
        self.start_range_label.setText(QtWidgets.QApplication.translate("MainWindow", "開始：", None, -1))
        self.end_range_label.setText(QtWidgets.QApplication.translate("MainWindow", "　終了：", None, -1))
        self.set_range_from_timeline_button.setText(QtWidgets.QApplication.translate("MainWindow", "タイムレンジから取得", None, -1))
        self.key_frame_copy_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択オブジェクトにソースから命名一致でキーフレームをコピー", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "オプション", None, -1))
        self.select_hierarchy_check.setText(QtWidgets.QApplication.translate("MainWindow", "選択した子階層も対象に含む", None, -1))

