# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_sp_joint_finder\glp_joint_finder.ui'
#
# Created: Fri Oct 13 14:34:12 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.view_object_text = QtWidgets.QLineEdit(self.groupBox_2)
        self.view_object_text.setText("")
        self.view_object_text.setFrame(False)
        self.view_object_text.setReadOnly(True)
        self.view_object_text.setObjectName("view_object_text")
        self.verticalLayout_8.addWidget(self.view_object_text)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.button_update = QtWidgets.QPushButton(self.tab)
        self.button_update.setMinimumSize(QtCore.QSize(0, 50))
        self.button_update.setObjectName("button_update")
        self.verticalLayout_2.addWidget(self.button_update)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.group_parts = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_parts.sizePolicy().hasHeightForWidth())
        self.group_parts.setSizePolicy(sizePolicy)
        self.group_parts.setMaximumSize(QtCore.QSize(16777215, 150))
        self.group_parts.setObjectName("group_parts")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_parts)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.list_parts = QtWidgets.QListWidget(self.group_parts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_parts.sizePolicy().hasHeightForWidth())
        self.list_parts.setSizePolicy(sizePolicy)
        self.list_parts.setMinimumSize(QtCore.QSize(0, 0))
        self.list_parts.setObjectName("list_parts")
        self.verticalLayout_6.addWidget(self.list_parts)
        self.button_select_highlight = QtWidgets.QPushButton(self.group_parts)
        self.button_select_highlight.setObjectName("button_select_highlight")
        self.verticalLayout_6.addWidget(self.button_select_highlight)
        self.verticalLayout_2.addWidget(self.group_parts)
        self.group_spjoint = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_spjoint.sizePolicy().hasHeightForWidth())
        self.group_spjoint.setSizePolicy(sizePolicy)
        self.group_spjoint.setObjectName("group_spjoint")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_spjoint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.check_sp = QtWidgets.QCheckBox(self.group_spjoint)
        self.check_sp.setChecked(True)
        self.check_sp.setObjectName("check_sp")
        self.horizontalLayout_4.addWidget(self.check_sp)
        self.check_ex = QtWidgets.QCheckBox(self.group_spjoint)
        self.check_ex.setChecked(True)
        self.check_ex.setObjectName("check_ex")
        self.horizontalLayout_4.addWidget(self.check_ex)
        self.check_tp = QtWidgets.QCheckBox(self.group_spjoint)
        self.check_tp.setChecked(True)
        self.check_tp.setObjectName("check_tp")
        self.horizontalLayout_4.addWidget(self.check_tp)
        self.check_pc = QtWidgets.QCheckBox(self.group_spjoint)
        self.check_pc.setChecked(True)
        self.check_pc.setObjectName("check_pc")
        self.horizontalLayout_4.addWidget(self.check_pc)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.list_spjoint = QtWidgets.QListWidget(self.group_spjoint)
        self.list_spjoint.setObjectName("list_spjoint")
        self.verticalLayout.addWidget(self.list_spjoint)
        self.button_copy = QtWidgets.QPushButton(self.group_spjoint)
        self.button_copy.setObjectName("button_copy")
        self.verticalLayout.addWidget(self.button_copy)
        self.verticalLayout_2.addWidget(self.group_spjoint)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.text_target_path = QtWidgets.QLineEdit(self.groupBox)
        self.text_target_path.setObjectName("text_target_path")
        self.horizontalLayout_3.addWidget(self.text_target_path)
        self.button_select_root = QtWidgets.QPushButton(self.groupBox)
        self.button_select_root.setObjectName("button_select_root")
        self.horizontalLayout_3.addWidget(self.button_select_root)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.text_output_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.text_output_path.setObjectName("text_output_path")
        self.verticalLayout_7.addWidget(self.text_output_path)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.button_batch_exe = QtWidgets.QPushButton(self.tab_2)
        self.button_batch_exe.setObjectName("button_batch_exe")
        self.verticalLayout_4.addWidget(self.button_batch_exe)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "現在表示中のオブジェクト", None, -1))
        self.button_update.setText(QtWidgets.QApplication.translate("MainWindow", "選択オブジェクト以下の特殊ジョイントを再検索", None, -1))
        self.group_parts.setTitle(QtWidgets.QApplication.translate("MainWindow", "部位ハイライト", None, -1))
        self.button_select_highlight.setText(QtWidgets.QApplication.translate("MainWindow", "ハイライトしているJointを選択", None, -1))
        self.group_spjoint.setTitle(QtWidgets.QApplication.translate("MainWindow", "特殊ジョイント一覧", None, -1))
        self.check_sp.setText(QtWidgets.QApplication.translate("MainWindow", "Sp_", None, -1))
        self.check_ex.setText(QtWidgets.QApplication.translate("MainWindow", "Ex_", None, -1))
        self.check_tp.setText(QtWidgets.QApplication.translate("MainWindow", "Tp_", None, -1))
        self.check_pc.setText(QtWidgets.QApplication.translate("MainWindow", "Pc_", None, -1))
        self.button_copy.setText(QtWidgets.QApplication.translate("MainWindow", "クリップボードにコピー", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "現在シーン", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "対象フォルダパス", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "特殊ジョイント一覧を出力したい親フォルダを指定してください", None, -1))
        self.button_select_root.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "出力先", None, -1))
        self.button_batch_exe.setText(QtWidgets.QApplication.translate("MainWindow", "バッチ処理実行", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "バッチ", None, -1))

