# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_random_obj_placement\ui\randPlacementObjWindow.ui'
#
# Created: Tue Jun 21 11:05:15 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 935)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidgetLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralwidgetLayout.setObjectName("centralwidgetLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 917))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.baseObjGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseObjGroup.sizePolicy().hasHeightForWidth())
        self.baseObjGroup.setSizePolicy(sizePolicy)
        self.baseObjGroup.setObjectName("baseObjGroup")
        self.baseObjLayout = QtWidgets.QVBoxLayout(self.baseObjGroup)
        self.baseObjLayout.setObjectName("baseObjLayout")
        self.baseObjDescriptionGroup = QtWidgets.QLabel(self.baseObjGroup)
        self.baseObjDescriptionGroup.setObjectName("baseObjDescriptionGroup")
        self.baseObjLayout.addWidget(self.baseObjDescriptionGroup)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.baseObjNameListWidget = QtWidgets.QListWidget(self.baseObjGroup)
        self.baseObjNameListWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseObjNameListWidget.sizePolicy().hasHeightForWidth())
        self.baseObjNameListWidget.setSizePolicy(sizePolicy)
        self.baseObjNameListWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.baseObjNameListWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.baseObjNameListWidget.setAutoScrollMargin(16)
        self.baseObjNameListWidget.setBatchSize(100)
        self.baseObjNameListWidget.setObjectName("baseObjNameListWidget")
        self.verticalLayout.addWidget(self.baseObjNameListWidget)
        self.setObjNameListButton = QtWidgets.QPushButton(self.baseObjGroup)
        self.setObjNameListButton.setObjectName("setObjNameListButton")
        self.verticalLayout.addWidget(self.setObjNameListButton)
        self.removeObjNameListButton = QtWidgets.QPushButton(self.baseObjGroup)
        self.removeObjNameListButton.setObjectName("removeObjNameListButton")
        self.verticalLayout.addWidget(self.removeObjNameListButton)
        self.baseObjLayout.addLayout(self.verticalLayout)
        self.baseObjOptionGroup = QtWidgets.QGroupBox(self.baseObjGroup)
        self.baseObjOptionGroup.setAutoFillBackground(False)
        self.baseObjOptionGroup.setObjectName("baseObjOptionGroup")
        self.baseObjOptionLayout = QtWidgets.QVBoxLayout(self.baseObjOptionGroup)
        self.baseObjOptionLayout.setSpacing(6)
        self.baseObjOptionLayout.setContentsMargins(9, 9, 9, 9)
        self.baseObjOptionLayout.setObjectName("baseObjOptionLayout")
        self.objDistanceLayout = QtWidgets.QHBoxLayout()
        self.objDistanceLayout.setObjectName("objDistanceLayout")
        self.objDistanceLabel1 = QtWidgets.QLabel(self.baseObjOptionGroup)
        self.objDistanceLabel1.setObjectName("objDistanceLabel1")
        self.objDistanceLayout.addWidget(self.objDistanceLabel1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.objDistanceLayout.addItem(spacerItem)
        self.objDistanceSpinBox = QtWidgets.QDoubleSpinBox(self.baseObjOptionGroup)
        self.objDistanceSpinBox.setDecimals(1)
        self.objDistanceSpinBox.setMaximum(999.0)
        self.objDistanceSpinBox.setObjectName("objDistanceSpinBox")
        self.objDistanceLayout.addWidget(self.objDistanceSpinBox)
        self.objDistanceLabel2 = QtWidgets.QLabel(self.baseObjOptionGroup)
        self.objDistanceLabel2.setObjectName("objDistanceLabel2")
        self.objDistanceLayout.addWidget(self.objDistanceLabel2)
        self.baseObjOptionLayout.addLayout(self.objDistanceLayout)
        self.placementOptionGroupBox = QtWidgets.QGroupBox(self.baseObjOptionGroup)
        self.placementOptionGroupBox.setObjectName("placementOptionGroupBox")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.placementOptionGroupBox)
        self.horizontalLayout_18.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.placementSettingRadioButton1 = QtWidgets.QRadioButton(self.placementOptionGroupBox)
        self.placementSettingRadioButton1.setChecked(True)
        self.placementSettingRadioButton1.setObjectName("placementSettingRadioButton1")
        self.verticalLayout_3.addWidget(self.placementSettingRadioButton1)
        self.placementSettingRadioButton2 = QtWidgets.QRadioButton(self.placementOptionGroupBox)
        self.placementSettingRadioButton2.setObjectName("placementSettingRadioButton2")
        self.verticalLayout_3.addWidget(self.placementSettingRadioButton2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.setRotationRadioButton_2 = QtWidgets.QRadioButton(self.placementOptionGroupBox)
        self.setRotationRadioButton_2.setObjectName("setRotationRadioButton_2")
        self.horizontalLayout_10.addWidget(self.setRotationRadioButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.rotateXLabel_2 = QtWidgets.QLabel(self.placementOptionGroupBox)
        self.rotateXLabel_2.setObjectName("rotateXLabel_2")
        self.horizontalLayout_12.addWidget(self.rotateXLabel_2)
        self.rotateXSpinBox = QtWidgets.QDoubleSpinBox(self.placementOptionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotateXSpinBox.sizePolicy().hasHeightForWidth())
        self.rotateXSpinBox.setSizePolicy(sizePolicy)
        self.rotateXSpinBox.setMinimumSize(QtCore.QSize(80, 0))
        self.rotateXSpinBox.setDecimals(1)
        self.rotateXSpinBox.setMaximum(360.0)
        self.rotateXSpinBox.setObjectName("rotateXSpinBox")
        self.horizontalLayout_12.addWidget(self.rotateXSpinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.rotateYLabel_2 = QtWidgets.QLabel(self.placementOptionGroupBox)
        self.rotateYLabel_2.setObjectName("rotateYLabel_2")
        self.horizontalLayout_13.addWidget(self.rotateYLabel_2)
        self.rotateYSpinBox = QtWidgets.QDoubleSpinBox(self.placementOptionGroupBox)
        self.rotateYSpinBox.setMinimumSize(QtCore.QSize(80, 0))
        self.rotateYSpinBox.setDecimals(1)
        self.rotateYSpinBox.setMaximum(360.0)
        self.rotateYSpinBox.setObjectName("rotateYSpinBox")
        self.horizontalLayout_13.addWidget(self.rotateYSpinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.rotateZLabel_2 = QtWidgets.QLabel(self.placementOptionGroupBox)
        self.rotateZLabel_2.setObjectName("rotateZLabel_2")
        self.horizontalLayout_14.addWidget(self.rotateZLabel_2)
        self.rotateZSpinBox = QtWidgets.QDoubleSpinBox(self.placementOptionGroupBox)
        self.rotateZSpinBox.setMinimumSize(QtCore.QSize(80, 0))
        self.rotateZSpinBox.setDecimals(1)
        self.rotateZSpinBox.setMaximum(360.0)
        self.rotateZSpinBox.setObjectName("rotateZSpinBox")
        self.horizontalLayout_14.addWidget(self.rotateZSpinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.setLookTargetRadioButton_2 = QtWidgets.QRadioButton(self.placementOptionGroupBox)
        self.setLookTargetRadioButton_2.setObjectName("setLookTargetRadioButton_2")
        self.horizontalLayout_15.addWidget(self.setLookTargetRadioButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lookTargetLineEdit_2 = QtWidgets.QLineEdit(self.placementOptionGroupBox)
        self.lookTargetLineEdit_2.setEnabled(False)
        self.lookTargetLineEdit_2.setMinimumSize(QtCore.QSize(200, 0))
        self.lookTargetLineEdit_2.setObjectName("lookTargetLineEdit_2")
        self.horizontalLayout_17.addWidget(self.lookTargetLineEdit_2)
        self.lookTargetSetButton = QtWidgets.QPushButton(self.placementOptionGroupBox)
        self.lookTargetSetButton.setObjectName("lookTargetSetButton")
        self.horizontalLayout_17.addWidget(self.lookTargetSetButton)
        self.lookTargetClearButton = QtWidgets.QPushButton(self.placementOptionGroupBox)
        self.lookTargetClearButton.setObjectName("lookTargetClearButton")
        self.horizontalLayout_17.addWidget(self.lookTargetClearButton)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18.addLayout(self.verticalLayout_3)
        self.baseObjOptionLayout.addWidget(self.placementOptionGroupBox)
        self.baseObjLayout.addWidget(self.baseObjOptionGroup)
        self.verticalLayout_4.addWidget(self.baseObjGroup)
        self.randObjPlacementGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randObjPlacementGroup.sizePolicy().hasHeightForWidth())
        self.randObjPlacementGroup.setSizePolicy(sizePolicy)
        self.randObjPlacementGroup.setAutoFillBackground(False)
        self.randObjPlacementGroup.setFlat(False)
        self.randObjPlacementGroup.setCheckable(False)
        self.randObjPlacementGroup.setObjectName("randObjPlacementGroup")
        self.randObjPlacementLayout = QtWidgets.QVBoxLayout(self.randObjPlacementGroup)
        self.randObjPlacementLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.randObjPlacementLayout.setObjectName("randObjPlacementLayout")
        self.randObjPlacementDescriptionLayout = QtWidgets.QHBoxLayout()
        self.randObjPlacementDescriptionLayout.setObjectName("randObjPlacementDescriptionLayout")
        self.randObjPlacementDescriptionLabel = QtWidgets.QLabel(self.randObjPlacementGroup)
        self.randObjPlacementDescriptionLabel.setObjectName("randObjPlacementDescriptionLabel")
        self.randObjPlacementDescriptionLayout.addWidget(self.randObjPlacementDescriptionLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.randObjPlacementDescriptionLayout.addItem(spacerItem3)
        self.randObjPlacementNumLabel = QtWidgets.QLabel(self.randObjPlacementGroup)
        self.randObjPlacementNumLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.randObjPlacementNumLabel.setObjectName("randObjPlacementNumLabel")
        self.randObjPlacementDescriptionLayout.addWidget(self.randObjPlacementNumLabel)
        self.randObjPlacementLayout.addLayout(self.randObjPlacementDescriptionLayout)
        self.randObjPlacementListScroll = QtWidgets.QScrollArea(self.randObjPlacementGroup)
        self.randObjPlacementListScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.randObjPlacementListScroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.randObjPlacementListScroll.setLineWidth(0)
        self.randObjPlacementListScroll.setWidgetResizable(True)
        self.randObjPlacementListScroll.setObjectName("randObjPlacementListScroll")
        self.randObjPlacementListWidget = QtWidgets.QWidget()
        self.randObjPlacementListWidget.setGeometry(QtCore.QRect(0, 0, 589, 108))
        self.randObjPlacementListWidget.setObjectName("randObjPlacementListWidget")
        self.randObjPlacementListLayout = QtWidgets.QVBoxLayout(self.randObjPlacementListWidget)
        self.randObjPlacementListLayout.setObjectName("randObjPlacementListLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.randObjPlacementListLayout.addItem(spacerItem4)
        self.randObjPlacementListScroll.setWidget(self.randObjPlacementListWidget)
        self.randObjPlacementLayout.addWidget(self.randObjPlacementListScroll)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.randObjPlacementAddListButton = QtWidgets.QPushButton(self.randObjPlacementGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randObjPlacementAddListButton.sizePolicy().hasHeightForWidth())
        self.randObjPlacementAddListButton.setSizePolicy(sizePolicy)
        self.randObjPlacementAddListButton.setObjectName("randObjPlacementAddListButton")
        self.horizontalLayout_2.addWidget(self.randObjPlacementAddListButton)
        self.randObjPlacementResetListButton = QtWidgets.QPushButton(self.randObjPlacementGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randObjPlacementResetListButton.sizePolicy().hasHeightForWidth())
        self.randObjPlacementResetListButton.setSizePolicy(sizePolicy)
        self.randObjPlacementResetListButton.setObjectName("randObjPlacementResetListButton")
        self.horizontalLayout_2.addWidget(self.randObjPlacementResetListButton)
        self.randObjPlacementLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.randObjPlacementGroup)
        self.centerObjSettingGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.centerObjSettingGroup.setObjectName("centerObjSettingGroup")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centerObjSettingGroup)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.centerObjSettingDescriptionLabel = QtWidgets.QLabel(self.centerObjSettingGroup)
        self.centerObjSettingDescriptionLabel.setLineWidth(1)
        self.centerObjSettingDescriptionLabel.setObjectName("centerObjSettingDescriptionLabel")
        self.verticalLayout_9.addWidget(self.centerObjSettingDescriptionLabel)
        self.centerObjNameLayout = QtWidgets.QHBoxLayout()
        self.centerObjNameLayout.setObjectName("centerObjNameLayout")
        self.centerObjNameLineEdit = QtWidgets.QLineEdit(self.centerObjSettingGroup)
        self.centerObjNameLineEdit.setEnabled(False)
        self.centerObjNameLineEdit.setInputMask("")
        self.centerObjNameLineEdit.setText("")
        self.centerObjNameLineEdit.setReadOnly(False)
        self.centerObjNameLineEdit.setObjectName("centerObjNameLineEdit")
        self.centerObjNameLayout.addWidget(self.centerObjNameLineEdit)
        self.centerObjNameSetButton = QtWidgets.QPushButton(self.centerObjSettingGroup)
        self.centerObjNameSetButton.setObjectName("centerObjNameSetButton")
        self.centerObjNameLayout.addWidget(self.centerObjNameSetButton)
        self.centerObjNameClearButton = QtWidgets.QPushButton(self.centerObjSettingGroup)
        self.centerObjNameClearButton.setObjectName("centerObjNameClearButton")
        self.centerObjNameLayout.addWidget(self.centerObjNameClearButton)
        self.centerObjNameLayout.setStretch(0, 3)
        self.centerObjNameLayout.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.centerObjNameLayout)
        self.centerObjSettingOptionGroup = QtWidgets.QGroupBox(self.centerObjSettingGroup)
        self.centerObjSettingOptionGroup.setCheckable(False)
        self.centerObjSettingOptionGroup.setObjectName("centerObjSettingOptionGroup")
        self.centerObjSettingOptionLayou = QtWidgets.QVBoxLayout(self.centerObjSettingOptionGroup)
        self.centerObjSettingOptionLayou.setContentsMargins(5, 5, 5, 5)
        self.centerObjSettingOptionLayou.setObjectName("centerObjSettingOptionLayou")
        self.centerObjDistanceLayou = QtWidgets.QHBoxLayout()
        self.centerObjDistanceLayou.setObjectName("centerObjDistanceLayou")
        self.centerObjDistanceLabel1 = QtWidgets.QLabel(self.centerObjSettingOptionGroup)
        self.centerObjDistanceLabel1.setObjectName("centerObjDistanceLabel1")
        self.centerObjDistanceLayou.addWidget(self.centerObjDistanceLabel1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.centerObjDistanceLayou.addItem(spacerItem5)
        self.centerObjDistanceSpinBox = QtWidgets.QDoubleSpinBox(self.centerObjSettingOptionGroup)
        self.centerObjDistanceSpinBox.setDecimals(1)
        self.centerObjDistanceSpinBox.setMaximum(999.0)
        self.centerObjDistanceSpinBox.setObjectName("centerObjDistanceSpinBox")
        self.centerObjDistanceLayou.addWidget(self.centerObjDistanceSpinBox)
        self.centerObjSettingOptionLayou.addLayout(self.centerObjDistanceLayou)
        self.verticalLayout_9.addWidget(self.centerObjSettingOptionGroup)
        self.verticalLayout_4.addWidget(self.centerObjSettingGroup)
        self.randSettingOptionGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randSettingOptionGroupBox.sizePolicy().hasHeightForWidth())
        self.randSettingOptionGroupBox.setSizePolicy(sizePolicy)
        self.randSettingOptionGroupBox.setObjectName("randSettingOptionGroupBox")
        self.randSettingOptionLayout = QtWidgets.QVBoxLayout(self.randSettingOptionGroupBox)
        self.randSettingOptionLayout.setObjectName("randSettingOptionLayout")
        self.randSettingOptionDescriptionLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingOptionDescriptionLabel.setObjectName("randSettingOptionDescriptionLabel")
        self.randSettingOptionLayout.addWidget(self.randSettingOptionDescriptionLabel)
        self.randSettingHeightLayout = QtWidgets.QHBoxLayout()
        self.randSettingHeightLayout.setObjectName("randSettingHeightLayout")
        self.randSettingHeightCheckBox = QtWidgets.QCheckBox(self.randSettingOptionGroupBox)
        self.randSettingHeightCheckBox.setText("")
        self.randSettingHeightCheckBox.setObjectName("randSettingHeightCheckBox")
        self.randSettingHeightLayout.addWidget(self.randSettingHeightCheckBox)
        self.randSettingHeightLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingHeightLabel.setObjectName("randSettingHeightLabel")
        self.randSettingHeightLayout.addWidget(self.randSettingHeightLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.randSettingHeightLayout.addItem(spacerItem6)
        self.randSettingHeightMinValueLayout = QtWidgets.QHBoxLayout()
        self.randSettingHeightMinValueLayout.setObjectName("randSettingHeightMinValueLayout")
        self.randSettingHeightMinValueLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingHeightMinValueLabel.setObjectName("randSettingHeightMinValueLabel")
        self.randSettingHeightMinValueLayout.addWidget(self.randSettingHeightMinValueLabel)
        self.randSettingHeightMinValueSpinBox = QtWidgets.QDoubleSpinBox(self.randSettingOptionGroupBox)
        self.randSettingHeightMinValueSpinBox.setDecimals(1)
        self.randSettingHeightMinValueSpinBox.setMinimum(-999.0)
        self.randSettingHeightMinValueSpinBox.setMaximum(999.0)
        self.randSettingHeightMinValueSpinBox.setObjectName("randSettingHeightMinValueSpinBox")
        self.randSettingHeightMinValueLayout.addWidget(self.randSettingHeightMinValueSpinBox)
        self.randSettingHeightLayout.addLayout(self.randSettingHeightMinValueLayout)
        self.randSettingHeightMaxValueLayout = QtWidgets.QHBoxLayout()
        self.randSettingHeightMaxValueLayout.setObjectName("randSettingHeightMaxValueLayout")
        self.randSettingHeightMaxValueLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingHeightMaxValueLabel.setObjectName("randSettingHeightMaxValueLabel")
        self.randSettingHeightMaxValueLayout.addWidget(self.randSettingHeightMaxValueLabel)
        self.randSettingHeightMaxValueSpinBox = QtWidgets.QDoubleSpinBox(self.randSettingOptionGroupBox)
        self.randSettingHeightMaxValueSpinBox.setDecimals(1)
        self.randSettingHeightMaxValueSpinBox.setMinimum(-999.0)
        self.randSettingHeightMaxValueSpinBox.setMaximum(999.0)
        self.randSettingHeightMaxValueSpinBox.setObjectName("randSettingHeightMaxValueSpinBox")
        self.randSettingHeightMaxValueLayout.addWidget(self.randSettingHeightMaxValueSpinBox)
        self.randSettingHeightLayout.addLayout(self.randSettingHeightMaxValueLayout)
        self.randSettingOptionLayout.addLayout(self.randSettingHeightLayout)
        self.randSettingRotateXLayout = QtWidgets.QHBoxLayout()
        self.randSettingRotateXLayout.setObjectName("randSettingRotateXLayout")
        self.randSettingRotateXCheckBox = QtWidgets.QCheckBox(self.randSettingOptionGroupBox)
        self.randSettingRotateXCheckBox.setText("")
        self.randSettingRotateXCheckBox.setObjectName("randSettingRotateXCheckBox")
        self.randSettingRotateXLayout.addWidget(self.randSettingRotateXCheckBox)
        self.randSettingRotateXLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingRotateXLabel.setObjectName("randSettingRotateXLabel")
        self.randSettingRotateXLayout.addWidget(self.randSettingRotateXLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.randSettingRotateXLayout.addItem(spacerItem7)
        self.randSettingRotateXMinValueLayout = QtWidgets.QHBoxLayout()
        self.randSettingRotateXMinValueLayout.setObjectName("randSettingRotateXMinValueLayout")
        self.randSettingRotateXMinValueLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingRotateXMinValueLabel.setObjectName("randSettingRotateXMinValueLabel")
        self.randSettingRotateXMinValueLayout.addWidget(self.randSettingRotateXMinValueLabel)
        self.randSettingRotateXMinValueSpinBox = QtWidgets.QDoubleSpinBox(self.randSettingOptionGroupBox)
        self.randSettingRotateXMinValueSpinBox.setDecimals(1)
        self.randSettingRotateXMinValueSpinBox.setMinimum(-360.0)
        self.randSettingRotateXMinValueSpinBox.setMaximum(360.0)
        self.randSettingRotateXMinValueSpinBox.setObjectName("randSettingRotateXMinValueSpinBox")
        self.randSettingRotateXMinValueLayout.addWidget(self.randSettingRotateXMinValueSpinBox)
        self.randSettingRotateXLayout.addLayout(self.randSettingRotateXMinValueLayout)
        self.randSettingRotateXMaxValueLayout = QtWidgets.QHBoxLayout()
        self.randSettingRotateXMaxValueLayout.setObjectName("randSettingRotateXMaxValueLayout")
        self.randSettingRotateXMaxValueLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingRotateXMaxValueLabel.setObjectName("randSettingRotateXMaxValueLabel")
        self.randSettingRotateXMaxValueLayout.addWidget(self.randSettingRotateXMaxValueLabel)
        self.randSettingRotateXMaxValueSpinBox = QtWidgets.QDoubleSpinBox(self.randSettingOptionGroupBox)
        self.randSettingRotateXMaxValueSpinBox.setDecimals(1)
        self.randSettingRotateXMaxValueSpinBox.setMinimum(-360.0)
        self.randSettingRotateXMaxValueSpinBox.setMaximum(360.0)
        self.randSettingRotateXMaxValueSpinBox.setObjectName("randSettingRotateXMaxValueSpinBox")
        self.randSettingRotateXMaxValueLayout.addWidget(self.randSettingRotateXMaxValueSpinBox)
        self.randSettingRotateXLayout.addLayout(self.randSettingRotateXMaxValueLayout)
        self.randSettingOptionLayout.addLayout(self.randSettingRotateXLayout)
        self.randSettingRotateYLayout = QtWidgets.QHBoxLayout()
        self.randSettingRotateYLayout.setObjectName("randSettingRotateYLayout")
        self.randSettingRotateYCheckBox = QtWidgets.QCheckBox(self.randSettingOptionGroupBox)
        self.randSettingRotateYCheckBox.setText("")
        self.randSettingRotateYCheckBox.setObjectName("randSettingRotateYCheckBox")
        self.randSettingRotateYLayout.addWidget(self.randSettingRotateYCheckBox)
        self.randSettingRotateYLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingRotateYLabel.setObjectName("randSettingRotateYLabel")
        self.randSettingRotateYLayout.addWidget(self.randSettingRotateYLabel)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.randSettingRotateYLayout.addItem(spacerItem8)
        self.randSettingRotateYMinValueLayout = QtWidgets.QHBoxLayout()
        self.randSettingRotateYMinValueLayout.setObjectName("randSettingRotateYMinValueLayout")
        self.randSettingRotateYMinValueLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingRotateYMinValueLabel.setObjectName("randSettingRotateYMinValueLabel")
        self.randSettingRotateYMinValueLayout.addWidget(self.randSettingRotateYMinValueLabel)
        self.randSettingRotateYMinValueSpinBox = QtWidgets.QDoubleSpinBox(self.randSettingOptionGroupBox)
        self.randSettingRotateYMinValueSpinBox.setDecimals(1)
        self.randSettingRotateYMinValueSpinBox.setMinimum(-360.0)
        self.randSettingRotateYMinValueSpinBox.setMaximum(360.0)
        self.randSettingRotateYMinValueSpinBox.setObjectName("randSettingRotateYMinValueSpinBox")
        self.randSettingRotateYMinValueLayout.addWidget(self.randSettingRotateYMinValueSpinBox)
        self.randSettingRotateYLayout.addLayout(self.randSettingRotateYMinValueLayout)
        self.randSettingRotateYMaxValueLayout = QtWidgets.QHBoxLayout()
        self.randSettingRotateYMaxValueLayout.setObjectName("randSettingRotateYMaxValueLayout")
        self.randSettingRotateYMaxValueLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingRotateYMaxValueLabel.setObjectName("randSettingRotateYMaxValueLabel")
        self.randSettingRotateYMaxValueLayout.addWidget(self.randSettingRotateYMaxValueLabel)
        self.randSettingRotateYMaxValueSpinBox = QtWidgets.QDoubleSpinBox(self.randSettingOptionGroupBox)
        self.randSettingRotateYMaxValueSpinBox.setDecimals(1)
        self.randSettingRotateYMaxValueSpinBox.setMinimum(-360.0)
        self.randSettingRotateYMaxValueSpinBox.setMaximum(360.0)
        self.randSettingRotateYMaxValueSpinBox.setObjectName("randSettingRotateYMaxValueSpinBox")
        self.randSettingRotateYMaxValueLayout.addWidget(self.randSettingRotateYMaxValueSpinBox)
        self.randSettingRotateYLayout.addLayout(self.randSettingRotateYMaxValueLayout)
        self.randSettingOptionLayout.addLayout(self.randSettingRotateYLayout)
        self.randSettingRotateZLayout = QtWidgets.QHBoxLayout()
        self.randSettingRotateZLayout.setObjectName("randSettingRotateZLayout")
        self.randSettingRotateZCheckBox = QtWidgets.QCheckBox(self.randSettingOptionGroupBox)
        self.randSettingRotateZCheckBox.setText("")
        self.randSettingRotateZCheckBox.setObjectName("randSettingRotateZCheckBox")
        self.randSettingRotateZLayout.addWidget(self.randSettingRotateZCheckBox)
        self.randSettingRotateZLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingRotateZLabel.setObjectName("randSettingRotateZLabel")
        self.randSettingRotateZLayout.addWidget(self.randSettingRotateZLabel)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.randSettingRotateZLayout.addItem(spacerItem9)
        self.randSettingRotateZMinValueLayout = QtWidgets.QHBoxLayout()
        self.randSettingRotateZMinValueLayout.setObjectName("randSettingRotateZMinValueLayout")
        self.randSettingRotateZMinValueLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingRotateZMinValueLabel.setObjectName("randSettingRotateZMinValueLabel")
        self.randSettingRotateZMinValueLayout.addWidget(self.randSettingRotateZMinValueLabel)
        self.randSettingRotateZMinValueSpinBox = QtWidgets.QDoubleSpinBox(self.randSettingOptionGroupBox)
        self.randSettingRotateZMinValueSpinBox.setDecimals(1)
        self.randSettingRotateZMinValueSpinBox.setMinimum(-360.0)
        self.randSettingRotateZMinValueSpinBox.setMaximum(360.0)
        self.randSettingRotateZMinValueSpinBox.setObjectName("randSettingRotateZMinValueSpinBox")
        self.randSettingRotateZMinValueLayout.addWidget(self.randSettingRotateZMinValueSpinBox)
        self.randSettingRotateZLayout.addLayout(self.randSettingRotateZMinValueLayout)
        self.randSettingRotateZMaxValueLayout = QtWidgets.QHBoxLayout()
        self.randSettingRotateZMaxValueLayout.setObjectName("randSettingRotateZMaxValueLayout")
        self.randSettingRotateZMaxValueLabel = QtWidgets.QLabel(self.randSettingOptionGroupBox)
        self.randSettingRotateZMaxValueLabel.setObjectName("randSettingRotateZMaxValueLabel")
        self.randSettingRotateZMaxValueLayout.addWidget(self.randSettingRotateZMaxValueLabel)
        self.randSettingRotateZMaxValueSpinBox = QtWidgets.QDoubleSpinBox(self.randSettingOptionGroupBox)
        self.randSettingRotateZMaxValueSpinBox.setDecimals(1)
        self.randSettingRotateZMaxValueSpinBox.setMinimum(-360.0)
        self.randSettingRotateZMaxValueSpinBox.setMaximum(360.0)
        self.randSettingRotateZMaxValueSpinBox.setObjectName("randSettingRotateZMaxValueSpinBox")
        self.randSettingRotateZMaxValueLayout.addWidget(self.randSettingRotateZMaxValueSpinBox)
        self.randSettingRotateZLayout.addLayout(self.randSettingRotateZMaxValueLayout)
        self.randSettingOptionLayout.addLayout(self.randSettingRotateZLayout)
        self.verticalLayout_4.addWidget(self.randSettingOptionGroupBox)
        self.placementRandomButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.placementRandomButton.setObjectName("placementRandomButton")
        self.verticalLayout_4.addWidget(self.placementRandomButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.centralwidgetLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "ランダム配置ツール ver1.2.0", None, -1))
        self.baseObjGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "ランダム配置ベースオブジェクト設定", None, -1))
        self.baseObjDescriptionGroup.setText(QtWidgets.QApplication.translate("MainWindow", "配置の範囲を設定するオブジェクトを設定します(入力必須/複数設定可)", None, -1))
        self.setObjNameListButton.setText(QtWidgets.QApplication.translate("MainWindow", "選択したオブジェクトをセット", None, -1))
        self.removeObjNameListButton.setText(QtWidgets.QApplication.translate("MainWindow", "リストから削除", None, -1))
        self.baseObjOptionGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "オプション", None, -1))
        self.objDistanceLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "オブジェクト間の距離", None, -1))
        self.objDistanceLabel2.setText(QtWidgets.QApplication.translate("MainWindow", "以上", None, -1))
        self.placementOptionGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "オブジェクト配置方法", None, -1))
        self.placementSettingRadioButton1.setText(QtWidgets.QApplication.translate("MainWindow", "デフォルトの向き", None, -1))
        self.placementSettingRadioButton2.setText(QtWidgets.QApplication.translate("MainWindow", "フェース法線の向き", None, -1))
        self.setRotationRadioButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "角度を指定", None, -1))
        self.rotateXLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.rotateYLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.rotateZLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.setLookTargetRadioButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Z+方向を向けるターゲットを指定", None, -1))
        self.lookTargetSetButton.setText(QtWidgets.QApplication.translate("MainWindow", "セット", None, -1))
        self.lookTargetClearButton.setText(QtWidgets.QApplication.translate("MainWindow", "クリア", None, -1))
        self.randObjPlacementGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "ランダム配置対象オブジェクト設定", None, -1))
        self.randObjPlacementDescriptionLabel.setText(QtWidgets.QApplication.translate("MainWindow", "ランダムに配置するオブジェクトを設定します", None, -1))
        self.randObjPlacementNumLabel.setText(QtWidgets.QApplication.translate("MainWindow", "現在のオブジェクト数：0", None, -1))
        self.randObjPlacementAddListButton.setText(QtWidgets.QApplication.translate("MainWindow", "選択中のオブジェクトをリストに追加", None, -1))
        self.randObjPlacementResetListButton.setText(QtWidgets.QApplication.translate("MainWindow", "クリア", None, -1))
        self.centerObjSettingGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "中心オブジェクト設定", None, -1))
        self.centerObjSettingDescriptionLabel.setText(QtWidgets.QApplication.translate("MainWindow", "周囲にオブジェクトを配置したくない箇所に設定するオブジェクトを設定できます\n"
"空の場合は無視して配置します", None, -1))
        self.centerObjNameSetButton.setText(QtWidgets.QApplication.translate("MainWindow", "セット", None, -1))
        self.centerObjNameClearButton.setText(QtWidgets.QApplication.translate("MainWindow", "クリア", None, -1))
        self.centerObjSettingOptionGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "オプション", None, -1))
        self.centerObjDistanceLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "配置を行わない距離", None, -1))
        self.randSettingOptionGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "ランダム幅", None, -1))
        self.randSettingOptionDescriptionLabel.setText(QtWidgets.QApplication.translate("MainWindow", "ランダム幅を設定します\n"
"チェックボックスがONになっている対象のみ処理を行います", None, -1))
        self.randSettingHeightLabel.setText(QtWidgets.QApplication.translate("MainWindow", "高さ", None, -1))
        self.randSettingHeightMinValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "最小", None, -1))
        self.randSettingHeightMaxValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "最大", None, -1))
        self.randSettingRotateXLabel.setText(QtWidgets.QApplication.translate("MainWindow", "回転(X)", None, -1))
        self.randSettingRotateXMinValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "最小", None, -1))
        self.randSettingRotateXMaxValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "最大", None, -1))
        self.randSettingRotateYLabel.setText(QtWidgets.QApplication.translate("MainWindow", "回転(Y)", None, -1))
        self.randSettingRotateYMinValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "最小", None, -1))
        self.randSettingRotateYMaxValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "最大", None, -1))
        self.randSettingRotateZLabel.setText(QtWidgets.QApplication.translate("MainWindow", "回転(Z)", None, -1))
        self.randSettingRotateZMinValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "最小", None, -1))
        self.randSettingRotateZMaxValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "最大", None, -1))
        self.placementRandomButton.setText(QtWidgets.QApplication.translate("MainWindow", "ランダム配置", None, -1))

