tools:
  - name: エクスポーター
    type: separator

  - name: fbx exporter
    label: FBXエクスポーター
    type: command
    icon: fbxReview.png
    tooltip: Wiz2でのみ動作する、FBXエクスポーターの起動
    command: import cygames_tools.chara.fbx_exporter.main;cygames_tools.chara.fbx_exporter.main.main()
    enable: True
  
  - name: スキニング
    type: separator

  - name: wiz2 bind
    label: Wiz2設定でバインド
    type: command
    icon: smoothSkin.png
    tooltip: wiz2でのみ動作する skinning用 tool
    command: import cygames_tools.chara.chara_rebinder.main;cygames_tools.chara.chara_rebinder.bind_rebind.BindSkinCmd.project_bind()
    enable: True

  - name: wiz2 rebind
    label: Wiz2設定でリバインド
    type: command
    icon: smoothSkin.png
    tooltip: wiz2でのみ動作する skinning用 tool
    command: import cygames_tools.chara.chara_rebinder.main;cygames_tools.chara.chara_rebinder.bind_rebind.BindSkinCmd.rebind()
    enable: True

  - name: ジョイント
    type: separator

  - name: segment_scale_off
    label: SegmentScaleをオフ
    icon: joint.svg
    type: command
    tooltip: "選択ジョイントのsegment scaleをオフ\n選択していなければすべての骨のsegment scaleをオフ"
    type: command
    command: from cygames_tools.chara.chara_utility.other_tools import OtherTools;selected = cmds.ls(sl=True);OtherTools.set_segment_scale(False, selected)
    enable: True

  - name: モデル
    type: separator

  - name: animation_convert_mtk_to_shr
    label: アウトラインの作成・更新
    icon: character.svg
    type: command
    tooltip: 選択したメッシュのアウトラインメッシュを生成
    command: import cygames_tools.chara.chara_utility.outline as chara_outline;chara_outline.create_outline()
    enable: True
    
  - name: hidden_vertex_color
    label: 足先非表示の頂点カラー設定
    icon: paintVertexColour.png
    type: command
    tooltip: 頂点カラーの設定
    command: import cygames_tools.chara.hidden_vertex_color.main;cygames_tools.chara.hidden_vertex_color.main.main()
    enable: True

  - name: texture_selector
    label: テクスチャー選択
    icon: textureList.svg
    type: command
    tooltip: 選択オブジェクトのテクスチャ－を切り替え
    command:   import cygames_tools.chara.chara_texture_selector.controller as ctrl;from importlib import reload;import importlib;importlib.reload(ctrl);ctrl.show()
    enable: True

  - name: normal_settings
    label: 法線設定ツール
    icon: polyNormalsConform.png
    type: command
    tooltip: 頂点カラーの設定
    command: import cygames_tools.chara.normal_editor.main;import importlib;importlib.reload(cygames_tools.chara.normal_editor.main);cygames_tools.chara.normal_editor.main.main()
    enable: True

  - name: チェッカー
    type: separator

  - name: character_checker
    label: キャラクターチェッカー
    icon: checkboxOn.png
    type: command
    tooltip: キャラクターのデータチェッカー
    command: import cygames_tools.chara.character_checker.app as app;app.show_checker_gui()
    enable: True


