# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/CF0438/Desktop/Ui_WriteAtomFile.ui'
#
# Created: Fri Mar 04 18:52:09 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(374, 472)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_close = QtGui.QPushButton(Dialog)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.pushButton_close, 1, 2, 1, 1)
        self.pushButton_apply = QtGui.QPushButton(Dialog)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.gridLayout.addWidget(self.pushButton_apply, 1, 1, 1, 1)
        self.pushButton_applyAndClose = QtGui.QPushButton(Dialog)
        self.pushButton_applyAndClose.setObjectName("pushButton_applyAndClose")
        self.gridLayout.addWidget(self.pushButton_applyAndClose, 1, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_option = QtGui.QLabel(Dialog)
        self.label_option.setObjectName("label_option")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_option)
        self.checkBox_sdk = QtGui.QCheckBox(Dialog)
        self.checkBox_sdk.setObjectName("checkBox_sdk")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.checkBox_sdk)
        self.checkBox_constraint = QtGui.QCheckBox(Dialog)
        self.checkBox_constraint.setObjectName("checkBox_constraint")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkBox_constraint)
        self.checkBox_animLayers = QtGui.QCheckBox(Dialog)
        self.checkBox_animLayers.setObjectName("checkBox_animLayers")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkBox_animLayers)
        self.checkBox_statics = QtGui.QCheckBox(Dialog)
        self.checkBox_statics.setObjectName("checkBox_statics")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.checkBox_statics)
        self.checkBox_baked = QtGui.QCheckBox(Dialog)
        self.checkBox_baked.setObjectName("checkBox_baked")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.checkBox_baked)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.line)
        self.label_hierarchy = QtGui.QLabel(Dialog)
        self.label_hierarchy.setObjectName("label_hierarchy")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_hierarchy)
        self.radioButton_selectedOnly = QtGui.QRadioButton(Dialog)
        self.radioButton_selectedOnly.setObjectName("radioButton_selectedOnly")
        self.buttonGroup_selected = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_selected.setObjectName("buttonGroup_selected")
        self.buttonGroup_selected.addButton(self.radioButton_selectedOnly)
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.radioButton_selectedOnly)
        self.radioButton_childrenToo = QtGui.QRadioButton(Dialog)
        self.radioButton_childrenToo.setObjectName("radioButton_childrenToo")
        self.buttonGroup_selected.addButton(self.radioButton_childrenToo)
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.radioButton_childrenToo)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(9, QtGui.QFormLayout.SpanningRole, self.line_2)
        self.label_channel = QtGui.QLabel(Dialog)
        self.label_channel.setObjectName("label_channel")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_channel)
        self.radioButton_allKey = QtGui.QRadioButton(Dialog)
        self.radioButton_allKey.setObjectName("radioButton_allKey")
        self.buttonGroup_channel = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_channel.setObjectName("buttonGroup_channel")
        self.buttonGroup_channel.addButton(self.radioButton_allKey)
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.radioButton_allKey)
        self.radioButton_fromChannelBox = QtGui.QRadioButton(Dialog)
        self.radioButton_fromChannelBox.setObjectName("radioButton_fromChannelBox")
        self.buttonGroup_channel.addButton(self.radioButton_fromChannelBox)
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.radioButton_fromChannelBox)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(12, QtGui.QFormLayout.SpanningRole, self.line_3)
        self.label_range = QtGui.QLabel(Dialog)
        self.label_range.setObjectName("label_range")
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_range)
        self.radioButton_range_timeSlider = QtGui.QRadioButton(Dialog)
        self.radioButton_range_timeSlider.setObjectName("radioButton_range_timeSlider")
        self.buttonGroup_range = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_range.setObjectName("buttonGroup_range")
        self.buttonGroup_range.addButton(self.radioButton_range_timeSlider)
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.radioButton_range_timeSlider)
        self.radioButton_range_all = QtGui.QRadioButton(Dialog)
        self.radioButton_range_all.setObjectName("radioButton_range_all")
        self.buttonGroup_range.addButton(self.radioButton_range_all)
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.radioButton_range_all)
        self.radioButton_range_oneFrame = QtGui.QRadioButton(Dialog)
        self.radioButton_range_oneFrame.setObjectName("radioButton_range_oneFrame")
        self.buttonGroup_range.addButton(self.radioButton_range_oneFrame)
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.radioButton_range_oneFrame)
        self.radioButton_range_startEnd = QtGui.QRadioButton(Dialog)
        self.radioButton_range_startEnd.setObjectName("radioButton_range_startEnd")
        self.buttonGroup_range.addButton(self.radioButton_range_startEnd)
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.radioButton_range_startEnd)
        self.label_startTime = QtGui.QLabel(Dialog)
        self.label_startTime.setObjectName("label_startTime")
        self.formLayout.setWidget(17, QtGui.QFormLayout.LabelRole, self.label_startTime)
        self.label_endTime = QtGui.QLabel(Dialog)
        self.label_endTime.setObjectName("label_endTime")
        self.formLayout.setWidget(18, QtGui.QFormLayout.LabelRole, self.label_endTime)
        self.lineEdit_endTime = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_endTime.sizePolicy().hasHeightForWidth())
        self.lineEdit_endTime.setSizePolicy(sizePolicy)
        self.lineEdit_endTime.setObjectName("lineEdit_endTime")
        self.formLayout.setWidget(18, QtGui.QFormLayout.FieldRole, self.lineEdit_endTime)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout.setWidget(19, QtGui.QFormLayout.SpanningRole, self.line_4)
        self.label_fileName = QtGui.QLabel(Dialog)
        self.label_fileName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_fileName.setObjectName("label_fileName")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_fileName)
        self.lineEdit_fileName = QtGui.QLineEdit(Dialog)
        self.lineEdit_fileName.setObjectName("lineEdit_fileName")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_fileName)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_startTime = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_startTime.sizePolicy().hasHeightForWidth())
        self.lineEdit_startTime.setSizePolicy(sizePolicy)
        self.lineEdit_startTime.setInputMask("")
        self.lineEdit_startTime.setObjectName("lineEdit_startTime")
        self.horizontalLayout.addWidget(self.lineEdit_startTime)
        self.pushButton_currentTime = QtGui.QPushButton(Dialog)
        self.pushButton_currentTime.setObjectName("pushButton_currentTime")
        self.horizontalLayout.addWidget(self.pushButton_currentTime)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(17, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_close.setText(QtGui.QApplication.translate("Dialog", "閉じる", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_apply.setText(QtGui.QApplication.translate("Dialog", "適用", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_applyAndClose.setText(QtGui.QApplication.translate("Dialog", "適用して閉じる", None, QtGui.QApplication.UnicodeUTF8))
        self.label_option.setText(QtGui.QApplication.translate("Dialog", "含めるオプション：", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_sdk.setText(QtGui.QApplication.translate("Dialog", "ドリブンキーの設定", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_constraint.setText(QtGui.QApplication.translate("Dialog", "コンストレイント", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_animLayers.setText(QtGui.QApplication.translate("Dialog", "アニメーション レイヤ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_statics.setText(QtGui.QApplication.translate("Dialog", "スタティック値", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_baked.setText(QtGui.QApplication.translate("Dialog", "ベイク処理されたアニメーション", None, QtGui.QApplication.UnicodeUTF8))
        self.label_hierarchy.setText(QtGui.QApplication.translate("Dialog", "階層：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_selectedOnly.setText(QtGui.QApplication.translate("Dialog", "選択項目", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_childrenToo.setText(QtGui.QApplication.translate("Dialog", "下位", None, QtGui.QApplication.UnicodeUTF8))
        self.label_channel.setText(QtGui.QApplication.translate("Dialog", "チャンネル：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_allKey.setText(QtGui.QApplication.translate("Dialog", "すべてのキーを設定可", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_fromChannelBox.setText(QtGui.QApplication.translate("Dialog", "チャンネルボックスから", None, QtGui.QApplication.UnicodeUTF8))
        self.label_range.setText(QtGui.QApplication.translate("Dialog", "タイム レンジ：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_range_timeSlider.setText(QtGui.QApplication.translate("Dialog", "タイム スライダ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_range_all.setText(QtGui.QApplication.translate("Dialog", "すべて", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_range_oneFrame.setText(QtGui.QApplication.translate("Dialog", "単一フレーム", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_range_startEnd.setText(QtGui.QApplication.translate("Dialog", "開始/終了", None, QtGui.QApplication.UnicodeUTF8))
        self.label_startTime.setText(QtGui.QApplication.translate("Dialog", "開始時間：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_endTime.setText(QtGui.QApplication.translate("Dialog", "終了時間：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fileName.setText(QtGui.QApplication.translate("Dialog", "ファイル名：", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_currentTime.setText(QtGui.QApplication.translate("Dialog", "現在のフレーム", None, QtGui.QApplication.UnicodeUTF8))

