# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_scene_cleanup\ui\scene_cleanup_window.ui'
#
# Created: Fri Oct  6 16:54:50 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 528)
        MainWindow.setMinimumSize(QtCore.QSize(450, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fix_initial_node_cb = QtWidgets.QCheckBox(self.groupBox)
        self.fix_initial_node_cb.setObjectName("fix_initial_node_cb")
        self.verticalLayout_2.addWidget(self.fix_initial_node_cb)
        self.delete_unknown_nodes_and_plugins_cb = QtWidgets.QCheckBox(self.groupBox)
        self.delete_unknown_nodes_and_plugins_cb.setObjectName("delete_unknown_nodes_and_plugins_cb")
        self.verticalLayout_2.addWidget(self.delete_unknown_nodes_and_plugins_cb)
        self.delete_vaccine_cb = QtWidgets.QCheckBox(self.groupBox)
        self.delete_vaccine_cb.setObjectName("delete_vaccine_cb")
        self.verticalLayout_2.addWidget(self.delete_vaccine_cb)
        self.reset_ui_callback_cb = QtWidgets.QCheckBox(self.groupBox)
        self.reset_ui_callback_cb.setObjectName("reset_ui_callback_cb")
        self.verticalLayout_2.addWidget(self.reset_ui_callback_cb)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.delete_script_nodes_cb = QtWidgets.QCheckBox(self.groupBox)
        self.delete_script_nodes_cb.setObjectName("delete_script_nodes_cb")
        self.horizontalLayout_3.addWidget(self.delete_script_nodes_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.delete_outliner_panel_select_command_cb = QtWidgets.QCheckBox(self.groupBox)
        self.delete_outliner_panel_select_command_cb.setObjectName("delete_outliner_panel_select_command_cb")
        self.horizontalLayout_4.addWidget(self.delete_outliner_panel_select_command_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.all_cleanup_on_btn = QtWidgets.QPushButton(self.groupBox)
        self.all_cleanup_on_btn.setObjectName("all_cleanup_on_btn")
        self.horizontalLayout.addWidget(self.all_cleanup_on_btn)
        self.all_cleanup_off_btn = QtWidgets.QPushButton(self.groupBox)
        self.all_cleanup_off_btn.setObjectName("all_cleanup_off_btn")
        self.horizontalLayout.addWidget(self.all_cleanup_off_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.exec_cleanup_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.exec_cleanup_btn.setObjectName("exec_cleanup_btn")
        self.verticalLayout_4.addWidget(self.exec_cleanup_btn)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.exec_batch_cleanup_target_dir_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.exec_batch_cleanup_target_dir_edit.setObjectName("exec_batch_cleanup_target_dir_edit")
        self.horizontalLayout_2.addWidget(self.exec_batch_cleanup_target_dir_edit)
        self.set_batch_cleanup_target_dir_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.set_batch_cleanup_target_dir_btn.setObjectName("set_batch_cleanup_target_dir_btn")
        self.horizontalLayout_2.addWidget(self.set_batch_cleanup_target_dir_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.exec_cleanup_for_child_hierarchy_cb = QtWidgets.QCheckBox(self.groupBox_3)
        self.exec_cleanup_for_child_hierarchy_cb.setObjectName("exec_cleanup_for_child_hierarchy_cb")
        self.verticalLayout_5.addWidget(self.exec_cleanup_for_child_hierarchy_cb)
        self.exec_batch_cleanup_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.exec_batch_cleanup_btn.setObjectName("exec_batch_cleanup_btn")
        self.verticalLayout_5.addWidget(self.exec_batch_cleanup_btn)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "glp_scene_cleanup", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "対象のクリーンアップコマンド", None, -1))
        self.fix_initial_node_cb.setText(QtWidgets.QApplication.translate("MainWindow", "不正にロックされたノードのロック解除", None, -1))
        self.delete_unknown_nodes_and_plugins_cb.setText(QtWidgets.QApplication.translate("MainWindow", "unknownノード並びにunknownプラグインの削除", None, -1))
        self.delete_vaccine_cb.setText(QtWidgets.QApplication.translate("MainWindow", "Vaccine周りの不正なノード並びにファイルの削除", None, -1))
        self.reset_ui_callback_cb.setText(QtWidgets.QApplication.translate("MainWindow", "uiConfigurationNodeをリセット", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "※↑の「uiConfigurationNodeをリセット」は\n"
"CgAbBlastPanelOptChangeCallbackエラー等を削除できます。\n"
"但し、UI情報もリセットされるため、TimeRangeもリセットされます。\n"
"また、正常に実行を行ってもMayaを再起動するまで表示が残り続けることがあります。", None, -1))
        self.delete_script_nodes_cb.setText(QtWidgets.QApplication.translate("MainWindow", "ScriptNodeを既定の物以外削除", None, -1))
        self.delete_outliner_panel_select_command_cb.setText(QtWidgets.QApplication.translate("MainWindow", "OutlinerPanelのSelectCommand削除", None, -1))
        self.all_cleanup_on_btn.setText(QtWidgets.QApplication.translate("MainWindow", "ALL ON", None, -1))
        self.all_cleanup_off_btn.setText(QtWidgets.QApplication.translate("MainWindow", "ALL OFF", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "現在のシーンで実行", None, -1))
        self.exec_cleanup_btn.setText(QtWidgets.QApplication.translate("MainWindow", "チェックボックスがONのクリーンアップコマンドを現在のシーンで実行", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Maya上でバッチ実行", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "「Maya上でバッチ実行」は、現在起動しているMaya上で順にバッチ実行を行います。\n"
"Mayaで現在開いているシーンは一度閉じてからループ実行されるため、\n"
"現在のシーンは必ず保存してから実行をお願いします。\n"
"また、バッチ実行結果は以下の場所に保存されます。\n"
"「D:batch_cleanup_result_(実行時の年号から始まる数字).csv」", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "実行対象フォルダ", None, -1))
        self.set_batch_cleanup_target_dir_btn.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.exec_cleanup_for_child_hierarchy_cb.setText(QtWidgets.QApplication.translate("MainWindow", "実行対象フォルダより下の階層にも実行する", None, -1))
        self.exec_batch_cleanup_btn.setText(QtWidgets.QApplication.translate("MainWindow", "チェックボックスがONの実行フォルダ以下のmaファイルを対象に実行", None, -1))

