# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_skinweight_editor\ui\edit_joint_window.ui'
#
# Created: Wed Jul 26 14:49:01 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(474, 326)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.joint_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.joint_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.joint_list_widget.setObjectName("joint_list_widget")
        self.horizontalLayout.addWidget(self.joint_list_widget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.joint_name_le = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint_name_le.sizePolicy().hasHeightForWidth())
        self.joint_name_le.setSizePolicy(sizePolicy)
        self.joint_name_le.setObjectName("joint_name_le")
        self.verticalLayout.addWidget(self.joint_name_le)
        self.set_joint_name_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_joint_name_btn.setObjectName("set_joint_name_btn")
        self.verticalLayout.addWidget(self.set_joint_name_btn)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout.addWidget(self.frame_4)
        self.select_item_from_maya_btn = QtWidgets.QPushButton(self.centralwidget)
        self.select_item_from_maya_btn.setObjectName("select_item_from_maya_btn")
        self.verticalLayout.addWidget(self.select_item_from_maya_btn)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.swap_joint_name_btn = QtWidgets.QPushButton(self.centralwidget)
        self.swap_joint_name_btn.setObjectName("swap_joint_name_btn")
        self.verticalLayout.addWidget(self.swap_joint_name_btn)
        self.swap_item_from_maya_btn = QtWidgets.QPushButton(self.centralwidget)
        self.swap_item_from_maya_btn.setObjectName("swap_item_from_maya_btn")
        self.verticalLayout.addWidget(self.swap_item_from_maya_btn)
        self.set_selected_obj_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_selected_obj_btn.setObjectName("set_selected_obj_btn")
        self.verticalLayout.addWidget(self.set_selected_obj_btn)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setObjectName("reset_btn")
        self.verticalLayout.addWidget(self.reset_btn)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        self.continue_btn = QtWidgets.QPushButton(self.centralwidget)
        self.continue_btn.setStyleSheet("#continue_btn{background-color:#cc7f00;}")
        self.continue_btn.setObjectName("continue_btn")
        self.verticalLayout.addWidget(self.continue_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Edit Joint Map", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Joint Name", None, -1))
        self.set_joint_name_btn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "選択しているアイテムのペースト先のジョイントを入力したJoint名で置き換えます", None, -1))
        self.set_joint_name_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Set Joint Name", None, -1))
        self.select_item_from_maya_btn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Mayaで選択しているジョイントに対応するジョイントをリスト上でハイライト", None, -1))
        self.select_item_from_maya_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Select List By Selected Joint", None, -1))
        self.swap_joint_name_btn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "リスト上で選択されている2つのアイテムのペースト先Joint名を入れ替えます", None, -1))
        self.swap_joint_name_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Swap JointName", None, -1))
        self.swap_item_from_maya_btn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Maya上で選択しているジョイント同士でペースト先Joint名を入れ替えます", None, -1))
        self.swap_item_from_maya_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Swap JointNames\n"
" Between Selected Joint", None, -1))
        self.set_selected_obj_btn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "リストで選択しているアイテムのペースト先JointをMayaで選択しているJointにします", None, -1))
        self.set_selected_obj_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Set Selected Object Name", None, -1))
        self.reset_btn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "リストのペースト先のジョイントの設定を初期状態に戻します", None, -1))
        self.reset_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))
        self.continue_btn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "ジョイントのリマップを完了して、ペースト処理を実行します", None, -1))
        self.continue_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Continues Processing", None, -1))

