# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_skinweight_editor\ui\main_window.ui'
#
# Created: Wed Jul 26 14:40:41 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(306, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.copy_btn = QtWidgets.QPushButton(self.tab_2)
        self.copy_btn.setObjectName("copy_btn")
        self.verticalLayout_3.addWidget(self.copy_btn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.copy_obj_space_rb = QtWidgets.QRadioButton(self.tab_2)
        self.copy_obj_space_rb.setChecked(True)
        self.copy_obj_space_rb.setObjectName("copy_obj_space_rb")
        self.horizontalLayout_2.addWidget(self.copy_obj_space_rb)
        self.copy_world_space_rb = QtWidgets.QRadioButton(self.tab_2)
        self.copy_world_space_rb.setObjectName("copy_world_space_rb")
        self.horizontalLayout_2.addWidget(self.copy_world_space_rb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.paste_by_select_btn = QtWidgets.QPushButton(self.tab_2)
        self.paste_by_select_btn.setObjectName("paste_by_select_btn")
        self.verticalLayout_3.addWidget(self.paste_by_select_btn)
        self.paste_by_index_btn = QtWidgets.QPushButton(self.tab_2)
        self.paste_by_index_btn.setObjectName("paste_by_index_btn")
        self.verticalLayout_3.addWidget(self.paste_by_index_btn)
        self.paste_by_pos_btn = QtWidgets.QPushButton(self.tab_2)
        self.paste_by_pos_btn.setObjectName("paste_by_pos_btn")
        self.verticalLayout_3.addWidget(self.paste_by_pos_btn)
        self.paste_by_uv_pos_btn = QtWidgets.QPushButton(self.tab_2)
        self.paste_by_uv_pos_btn.setObjectName("paste_by_uv_pos_btn")
        self.verticalLayout_3.addWidget(self.paste_by_uv_pos_btn)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.paste_mirror_x_btn = QtWidgets.QPushButton(self.tab_2)
        self.paste_mirror_x_btn.setObjectName("paste_mirror_x_btn")
        self.verticalLayout_3.addWidget(self.paste_mirror_x_btn)
        self.paste_mirror_y_btn = QtWidgets.QPushButton(self.tab_2)
        self.paste_mirror_y_btn.setObjectName("paste_mirror_y_btn")
        self.verticalLayout_3.addWidget(self.paste_mirror_y_btn)
        self.paste_mirror_z_btn = QtWidgets.QPushButton(self.tab_2)
        self.paste_mirror_z_btn.setObjectName("paste_mirror_z_btn")
        self.verticalLayout_3.addWidget(self.paste_mirror_z_btn)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.export_btn = QtWidgets.QPushButton(self.tab)
        self.export_btn.setObjectName("export_btn")
        self.verticalLayout_2.addWidget(self.export_btn)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.export_obj_space_rb = QtWidgets.QRadioButton(self.tab)
        self.export_obj_space_rb.setChecked(True)
        self.export_obj_space_rb.setObjectName("export_obj_space_rb")
        self.horizontalLayout_3.addWidget(self.export_obj_space_rb)
        self.export_world_space_rb = QtWidgets.QRadioButton(self.tab)
        self.export_world_space_rb.setObjectName("export_world_space_rb")
        self.horizontalLayout_3.addWidget(self.export_world_space_rb)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.import_by_select_btn = QtWidgets.QPushButton(self.tab)
        self.import_by_select_btn.setObjectName("import_by_select_btn")
        self.verticalLayout_2.addWidget(self.import_by_select_btn)
        self.import_by_index_btn = QtWidgets.QPushButton(self.tab)
        self.import_by_index_btn.setObjectName("import_by_index_btn")
        self.verticalLayout_2.addWidget(self.import_by_index_btn)
        self.import_by_pos_btn = QtWidgets.QPushButton(self.tab)
        self.import_by_pos_btn.setObjectName("import_by_pos_btn")
        self.verticalLayout_2.addWidget(self.import_by_pos_btn)
        self.import_by_uv_pos_btn = QtWidgets.QPushButton(self.tab)
        self.import_by_uv_pos_btn.setObjectName("import_by_uv_pos_btn")
        self.verticalLayout_2.addWidget(self.import_by_uv_pos_btn)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.import_mirror_x_btn = QtWidgets.QPushButton(self.tab)
        self.import_mirror_x_btn.setObjectName("import_mirror_x_btn")
        self.verticalLayout_2.addWidget(self.import_mirror_x_btn)
        self.import_mirror_y_btn = QtWidgets.QPushButton(self.tab)
        self.import_mirror_y_btn.setObjectName("import_mirror_y_btn")
        self.verticalLayout_2.addWidget(self.import_mirror_y_btn)
        self.import_mirror_z_btn = QtWidgets.QPushButton(self.tab)
        self.import_mirror_z_btn.setObjectName("import_mirror_z_btn")
        self.verticalLayout_2.addWidget(self.import_mirror_z_btn)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setMinimumSize(QtCore.QSize(75, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.round_digits_spin = QtWidgets.QSpinBox(self.tab_3)
        self.round_digits_spin.setMinimum(1)
        self.round_digits_spin.setMaximum(10)
        self.round_digits_spin.setProperty("value", 2)
        self.round_digits_spin.setObjectName("round_digits_spin")
        self.horizontalLayout_4.addWidget(self.round_digits_spin)
        self.round_digits_sl = QtWidgets.QSlider(self.tab_3)
        self.round_digits_sl.setMinimum(1)
        self.round_digits_sl.setMaximum(10)
        self.round_digits_sl.setProperty("value", 2)
        self.round_digits_sl.setOrientation(QtCore.Qt.Horizontal)
        self.round_digits_sl.setObjectName("round_digits_sl")
        self.horizontalLayout_4.addWidget(self.round_digits_sl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.round_weight_btn = QtWidgets.QPushButton(self.tab_3)
        self.round_weight_btn.setObjectName("round_weight_btn")
        self.verticalLayout_4.addWidget(self.round_weight_btn)
        self.check_round_weight_btn = QtWidgets.QPushButton(self.tab_3)
        self.check_round_weight_btn.setObjectName("check_round_weight_btn")
        self.verticalLayout_4.addWidget(self.check_round_weight_btn)
        self.frame_5 = QtWidgets.QFrame(self.tab_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4.addWidget(self.frame_5)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setMinimumSize(QtCore.QSize(75, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.inf_num_spin = QtWidgets.QSpinBox(self.tab_3)
        self.inf_num_spin.setMinimum(1)
        self.inf_num_spin.setMaximum(10)
        self.inf_num_spin.setProperty("value", 2)
        self.inf_num_spin.setObjectName("inf_num_spin")
        self.horizontalLayout_5.addWidget(self.inf_num_spin)
        self.inf_num_sl = QtWidgets.QSlider(self.tab_3)
        self.inf_num_sl.setMinimum(1)
        self.inf_num_sl.setMaximum(10)
        self.inf_num_sl.setProperty("value", 2)
        self.inf_num_sl.setOrientation(QtCore.Qt.Horizontal)
        self.inf_num_sl.setObjectName("inf_num_sl")
        self.horizontalLayout_5.addWidget(self.inf_num_sl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.set_max_inf_btn = QtWidgets.QPushButton(self.tab_3)
        self.set_max_inf_btn.setObjectName("set_max_inf_btn")
        self.verticalLayout_4.addWidget(self.set_max_inf_btn)
        self.check_max_inf_btn = QtWidgets.QPushButton(self.tab_3)
        self.check_max_inf_btn.setObjectName("check_max_inf_btn")
        self.verticalLayout_4.addWidget(self.check_max_inf_btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.paste_distance_ds = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.paste_distance_ds.setMaximum(1000.0)
        self.paste_distance_ds.setProperty("value", 5.0)
        self.paste_distance_ds.setObjectName("paste_distance_ds")
        self.horizontalLayout.addWidget(self.paste_distance_ds)
        self.paste_distance_sl = QtWidgets.QSlider(self.centralwidget)
        self.paste_distance_sl.setMaximum(1000)
        self.paste_distance_sl.setProperty("value", 5)
        self.paste_distance_sl.setOrientation(QtCore.Qt.Horizontal)
        self.paste_distance_sl.setObjectName("paste_distance_sl")
        self.horizontalLayout.addWidget(self.paste_distance_sl)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.edit_joint_map_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.edit_joint_map_cb.setObjectName("edit_joint_map_cb")
        self.gridLayout.addWidget(self.edit_joint_map_cb, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "GlpSkinWeightEditor", None, -1))
        self.copy_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Copy Weight", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Space:", None, -1))
        self.copy_obj_space_rb.setText(QtWidgets.QApplication.translate("MainWindow", "Object", None, -1))
        self.copy_world_space_rb.setText(QtWidgets.QApplication.translate("MainWindow", "World", None, -1))
        self.paste_by_select_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Paste Weight By SelectOrder", None, -1))
        self.paste_by_index_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Paste Weight By Index", None, -1))
        self.paste_by_pos_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Paste Weight By Position", None, -1))
        self.paste_by_uv_pos_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Paste Weight By UV Position", None, -1))
        self.paste_mirror_x_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Paste Weight By MirrorX", None, -1))
        self.paste_mirror_y_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Paste Weight By MirrorY", None, -1))
        self.paste_mirror_z_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Paste Weight By MirrorZ", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Copy And Paste", None, -1))
        self.export_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Export Weight", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Space:", None, -1))
        self.export_obj_space_rb.setText(QtWidgets.QApplication.translate("MainWindow", "Object", None, -1))
        self.export_world_space_rb.setText(QtWidgets.QApplication.translate("MainWindow", "World", None, -1))
        self.import_by_select_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Import Weight By SelectOrder", None, -1))
        self.import_by_index_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Import Weight By Index", None, -1))
        self.import_by_pos_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Import Weight By Position", None, -1))
        self.import_by_uv_pos_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Import Weight By UV Position", None, -1))
        self.import_mirror_x_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Import Weight By MirrorX", None, -1))
        self.import_mirror_y_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Import Weight By MirrorY", None, -1))
        self.import_mirror_z_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Import Weight By MirrorZ", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Export And Import", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Round Weight", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Fraction Digit", None, -1))
        self.round_weight_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Round Weight", None, -1))
        self.check_round_weight_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Check Round Weight", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Max Influence", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Influence Num", None, -1))
        self.set_max_inf_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Set Max Influence", None, -1))
        self.check_max_inf_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Check Max Influence", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Utility", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Paste Distance", None, -1))
        self.edit_joint_map_cb.setText(QtWidgets.QApplication.translate("MainWindow", "スキンウェイト適用時JointMapを編集する", None, -1))

