# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tech-designer\Maya\scripts\Project_Gallop\glp_symmetrical_weight_checker\glp_symmetrical_weight_checker_ui.ui'
#
# Created: Tue Feb  9 14:51:09 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

try:
    # Maya 2022-
    from builtins import object
except Exception:
    pass

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(569, 769)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_group = QtWidgets.QGroupBox(self.groupBox)
        self.main_group.setObjectName("main_group")
        self.layoutWidget = QtWidgets.QWidget(self.main_group)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 303, 18))
        self.layoutWidget.setObjectName("layoutWidget")
        self.search_type_select_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.search_type_select_layout.setContentsMargins(0, 0, 0, 0)
        self.search_type_select_layout.setObjectName("search_type_select_layout")
        self.search_type_label = QtWidgets.QLabel(self.layoutWidget)
        self.search_type_label.setMinimumSize(QtCore.QSize(120, 0))
        self.search_type_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.search_type_label.setObjectName("search_type_label")
        self.search_type_select_layout.addWidget(self.search_type_label)
        self.by_name_radio_button = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.by_name_radio_button.sizePolicy().hasHeightForWidth())
        self.by_name_radio_button.setSizePolicy(sizePolicy)
        self.by_name_radio_button.setChecked(True)
        self.by_name_radio_button.setObjectName("by_name_radio_button")
        self.search_type_select_layout.addWidget(self.by_name_radio_button)
        self.by_pos_radio_button = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.by_pos_radio_button.sizePolicy().hasHeightForWidth())
        self.by_pos_radio_button.setSizePolicy(sizePolicy)
        self.by_pos_radio_button.setObjectName("by_pos_radio_button")
        self.search_type_select_layout.addWidget(self.by_pos_radio_button)
        self.layoutWidget1 = QtWidgets.QWidget(self.main_group)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 23, 270, 18))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.axis_select_layout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.axis_select_layout.setContentsMargins(0, 0, 0, 0)
        self.axis_select_layout.setObjectName("axis_select_layout")
        self.axis_select_label = QtWidgets.QLabel(self.layoutWidget1)
        self.axis_select_label.setMinimumSize(QtCore.QSize(120, 0))
        self.axis_select_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.axis_select_label.setObjectName("axis_select_label")
        self.axis_select_layout.addWidget(self.axis_select_label)
        self.axis_x_radio_button = QtWidgets.QRadioButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axis_x_radio_button.sizePolicy().hasHeightForWidth())
        self.axis_x_radio_button.setSizePolicy(sizePolicy)
        self.axis_x_radio_button.setToolTip("")
        self.axis_x_radio_button.setChecked(True)
        self.axis_x_radio_button.setObjectName("axis_x_radio_button")
        self.axis_select_layout.addWidget(self.axis_x_radio_button)
        self.axis_y_radio_button = QtWidgets.QRadioButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axis_y_radio_button.sizePolicy().hasHeightForWidth())
        self.axis_y_radio_button.setSizePolicy(sizePolicy)
        self.axis_y_radio_button.setToolTip("")
        self.axis_y_radio_button.setObjectName("axis_y_radio_button")
        self.axis_select_layout.addWidget(self.axis_y_radio_button)
        self.axis_z_radio_button = QtWidgets.QRadioButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axis_z_radio_button.sizePolicy().hasHeightForWidth())
        self.axis_z_radio_button.setSizePolicy(sizePolicy)
        self.axis_z_radio_button.setToolTip("")
        self.axis_z_radio_button.setObjectName("axis_z_radio_button")
        self.axis_select_layout.addWidget(self.axis_z_radio_button)
        self.verticalLayout.addWidget(self.main_group)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.option_group = QtWidgets.QGroupBox(self.groupBox)
        self.option_group.setMaximumSize(QtCore.QSize(200, 16777215))
        self.option_group.setObjectName("option_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.option_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.symmetrical_str_label = QtWidgets.QLabel(self.option_group)
        self.symmetrical_str_label.setMinimumSize(QtCore.QSize(60, 0))
        self.symmetrical_str_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.symmetrical_str_label.setObjectName("symmetrical_str_label")
        self.horizontalLayout_3.addWidget(self.symmetrical_str_label)
        self.symmetrical_str = QtWidgets.QLineEdit(self.option_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symmetrical_str.sizePolicy().hasHeightForWidth())
        self.symmetrical_str.setSizePolicy(sizePolicy)
        self.symmetrical_str.setMinimumSize(QtCore.QSize(100, 0))
        self.symmetrical_str.setMaximumSize(QtCore.QSize(100, 16777215))
        self.symmetrical_str.setObjectName("symmetrical_str")
        self.horizontalLayout_3.addWidget(self.symmetrical_str)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.torelance_label = QtWidgets.QLabel(self.option_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.torelance_label.sizePolicy().hasHeightForWidth())
        self.torelance_label.setSizePolicy(sizePolicy)
        self.torelance_label.setMinimumSize(QtCore.QSize(60, 0))
        self.torelance_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.torelance_label.setObjectName("torelance_label")
        self.horizontalLayout_4.addWidget(self.torelance_label)
        self.torelance = QtWidgets.QLineEdit(self.option_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.torelance.sizePolicy().hasHeightForWidth())
        self.torelance.setSizePolicy(sizePolicy)
        self.torelance.setMinimumSize(QtCore.QSize(100, 0))
        self.torelance.setMaximumSize(QtCore.QSize(100, 16777215))
        self.torelance.setObjectName("torelance")
        self.horizontalLayout_4.addWidget(self.torelance)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.addWidget(self.option_group)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.target_label = QtWidgets.QLabel(self.groupBox)
        self.target_label.setObjectName("target_label")
        self.horizontalLayout.addWidget(self.target_label)
        self.target_obj_text = QtWidgets.QLineEdit(self.groupBox)
        self.target_obj_text.setObjectName("target_obj_text")
        self.horizontalLayout.addWidget(self.target_obj_text)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.exe_button = QtWidgets.QPushButton(self.groupBox)
        self.exe_button.setObjectName("exe_button")
        self.verticalLayout_4.addWidget(self.exe_button)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.inf_error_checkbox = QtWidgets.QCheckBox(self.groupBox_4)
        self.inf_error_checkbox.setStyleSheet("background-color: rgb(64, 0, 0);")
        self.inf_error_checkbox.setObjectName("inf_error_checkbox")
        self.verticalLayout_8.addWidget(self.inf_error_checkbox)
        self.weight_error_checkbox = QtWidgets.QCheckBox(self.groupBox_4)
        self.weight_error_checkbox.setStyleSheet("background-color: rgb(0, 0, 64);")
        self.weight_error_checkbox.setObjectName("weight_error_checkbox")
        self.verticalLayout_8.addWidget(self.weight_error_checkbox)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.normal_pair_checkbox = QtWidgets.QCheckBox(self.groupBox_5)
        self.normal_pair_checkbox.setObjectName("normal_pair_checkbox")
        self.verticalLayout_9.addWidget(self.normal_pair_checkbox)
        self.no_pair_checkbox = QtWidgets.QCheckBox(self.groupBox_5)
        self.no_pair_checkbox.setObjectName("no_pair_checkbox")
        self.verticalLayout_9.addWidget(self.no_pair_checkbox)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.result_vtx_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.result_vtx_table.setMinimumSize(QtCore.QSize(260, 0))
        self.result_vtx_table.setColumnCount(2)
        self.result_vtx_table.setObjectName("result_vtx_table")
        self.result_vtx_table.setColumnCount(2)
        self.result_vtx_table.setRowCount(0)
        self.result_vtx_table.horizontalHeader().setCascadingSectionResizes(False)
        self.result_vtx_table.horizontalHeader().setDefaultSectionSize(129)
        self.result_vtx_table.horizontalHeader().setMinimumSectionSize(34)
        self.result_vtx_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_8.addWidget(self.result_vtx_table)
        self.result_info_list = QtWidgets.QListWidget(self.groupBox_2)
        self.result_info_list.setObjectName("result_info_list")
        self.horizontalLayout_8.addWidget(self.result_info_list)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.weight_fix_group = QtWidgets.QGroupBox(self.centralwidget)
        self.weight_fix_group.setObjectName("weight_fix_group")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.weight_fix_group)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.select_negative_button = QtWidgets.QPushButton(self.weight_fix_group)
        self.select_negative_button.setObjectName("select_negative_button")
        self.verticalLayout_10.addWidget(self.select_negative_button)
        self.all_negative_button = QtWidgets.QPushButton(self.weight_fix_group)
        self.all_negative_button.setObjectName("all_negative_button")
        self.verticalLayout_10.addWidget(self.all_negative_button)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.select_positive_button = QtWidgets.QPushButton(self.weight_fix_group)
        self.select_positive_button.setObjectName("select_positive_button")
        self.verticalLayout_11.addWidget(self.select_positive_button)
        self.all_positive_button = QtWidgets.QPushButton(self.weight_fix_group)
        self.all_positive_button.setObjectName("all_positive_button")
        self.verticalLayout_11.addWidget(self.all_positive_button)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.refresh_list_checkbox = QtWidgets.QCheckBox(self.weight_fix_group)
        self.refresh_list_checkbox.setChecked(True)
        self.refresh_list_checkbox.setObjectName("refresh_list_checkbox")
        self.verticalLayout_12.addWidget(self.refresh_list_checkbox)
        self.verticalLayout_6.addWidget(self.weight_fix_group)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "頂点のスキニング対称性チェック", None, -1))
        self.main_group.setTitle(QtWidgets.QApplication.translate("MainWindow", "メイン設定", None, -1))
        self.search_type_label.setText(QtWidgets.QApplication.translate("MainWindow", "対称の判定方法", None, -1))
        self.by_name_radio_button.setText(QtWidgets.QApplication.translate("MainWindow", "ジョイント名", None, -1))
        self.by_pos_radio_button.setText(QtWidgets.QApplication.translate("MainWindow", "ジョイント位置", None, -1))
        self.axis_select_label.setText(QtWidgets.QApplication.translate("MainWindow", "対称座標選択", None, -1))
        self.axis_x_radio_button.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.axis_y_radio_button.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.axis_z_radio_button.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.option_group.setTitle(QtWidgets.QApplication.translate("MainWindow", "オプション設定", None, -1))
        self.symmetrical_str_label.setText(QtWidgets.QApplication.translate("MainWindow", "対称文字列", None, -1))
        self.torelance_label.setText(QtWidgets.QApplication.translate("MainWindow", "位置誤差　", None, -1))
        self.target_label.setText(QtWidgets.QApplication.translate("MainWindow", "チェック対象", None, -1))
        self.exe_button.setText(QtWidgets.QApplication.translate("MainWindow", "頂点のスキニングの対称性をチェック（Go to Bind Poseを実行します）", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "チェック結果", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "エラー表示", None, -1))
        self.inf_error_checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "ジョイント名/位置が非対称な頂点", None, -1))
        self.weight_error_checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "ウェイトが非対称な頂点", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "その他表示", None, -1))
        self.normal_pair_checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "対称にスキニングされている頂点", None, -1))
        self.no_pair_checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "対称位置に頂点の無い頂点", None, -1))
        self.weight_fix_group.setTitle(QtWidgets.QApplication.translate("MainWindow", "非対称ウェイトの修正", None, -1))
        self.select_negative_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択頂点を「-」に合わせる", None, -1))
        self.all_negative_button.setText(QtWidgets.QApplication.translate("MainWindow", "全頂点を「-」に合わせる", None, -1))
        self.select_positive_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択頂点を「+」に合わせる", None, -1))
        self.all_positive_button.setText(QtWidgets.QApplication.translate("MainWindow", "全頂点を「+」に合わせる", None, -1))
        self.refresh_list_checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "修正後チェック結果を更新する", None, -1))

