# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_create_union_model\ui\glp_create_union_model.ui'
#
# Created: Tue Oct 24 11:25:50 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 380)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 380))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.body_file_path_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.body_file_path_edit.setObjectName("body_file_path_edit")
        self.horizontalLayout.addWidget(self.body_file_path_edit)
        self.set_body_file_path_button = QtWidgets.QPushButton(self.groupBox_2)
        self.set_body_file_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.set_body_file_path_button.setObjectName("set_body_file_path_button")
        self.horizontalLayout.addWidget(self.set_body_file_path_button)
        self.open_body_file_path_button = QtWidgets.QPushButton(self.groupBox_2)
        self.open_body_file_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.open_body_file_path_button.setObjectName("open_body_file_path_button")
        self.horizontalLayout.addWidget(self.open_body_file_path_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dress_data_csv_path_edit = QtWidgets.QLineEdit(self.frame)
        self.dress_data_csv_path_edit.setEnabled(False)
        self.dress_data_csv_path_edit.setObjectName("dress_data_csv_path_edit")
        self.horizontalLayout_4.addWidget(self.dress_data_csv_path_edit)
        self.set_dress_data_csv_path_button = QtWidgets.QPushButton(self.frame)
        self.set_dress_data_csv_path_button.setEnabled(False)
        self.set_dress_data_csv_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.set_dress_data_csv_path_button.setObjectName("set_dress_data_csv_path_button")
        self.horizontalLayout_4.addWidget(self.set_dress_data_csv_path_button)
        self.open_dress_data_csv_path_button = QtWidgets.QPushButton(self.frame)
        self.open_dress_data_csv_path_button.setEnabled(False)
        self.open_dress_data_csv_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.open_dress_data_csv_path_button.setObjectName("open_dress_data_csv_path_button")
        self.horizontalLayout_4.addWidget(self.open_dress_data_csv_path_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.use_tool_dress_data_csv_cb = QtWidgets.QCheckBox(self.frame)
        self.use_tool_dress_data_csv_cb.setChecked(True)
        self.use_tool_dress_data_csv_cb.setObjectName("use_tool_dress_data_csv_cb")
        self.verticalLayout_3.addWidget(self.use_tool_dress_data_csv_cb)
        self.exec_set_union_file_path_button = QtWidgets.QPushButton(self.frame)
        self.exec_set_union_file_path_button.setObjectName("exec_set_union_file_path_button")
        self.verticalLayout_3.addWidget(self.exec_set_union_file_path_button)
        self.verticalLayout_4.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.head_file_path_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.head_file_path_edit.setObjectName("head_file_path_edit")
        self.horizontalLayout_2.addWidget(self.head_file_path_edit)
        self.set_head_file_path_button = QtWidgets.QPushButton(self.groupBox_2)
        self.set_head_file_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.set_head_file_path_button.setObjectName("set_head_file_path_button")
        self.horizontalLayout_2.addWidget(self.set_head_file_path_button)
        self.open_head_file_path_button = QtWidgets.QPushButton(self.groupBox_2)
        self.open_head_file_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.open_head_file_path_button.setObjectName("open_head_file_path_button")
        self.horizontalLayout_2.addWidget(self.open_head_file_path_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.tail_file_path_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tail_file_path_edit.setObjectName("tail_file_path_edit")
        self.horizontalLayout_3.addWidget(self.tail_file_path_edit)
        self.set_tail_file_path_button = QtWidgets.QPushButton(self.groupBox_2)
        self.set_tail_file_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.set_tail_file_path_button.setObjectName("set_tail_file_path_button")
        self.horizontalLayout_3.addWidget(self.set_tail_file_path_button)
        self.open_tail_file_path_button = QtWidgets.QPushButton(self.groupBox_2)
        self.open_tail_file_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.open_tail_file_path_button.setObjectName("open_tail_file_path_button")
        self.horizontalLayout_3.addWidget(self.open_tail_file_path_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.save_union_file_path_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.save_union_file_path_edit.setObjectName("save_union_file_path_edit")
        self.horizontalLayout_5.addWidget(self.save_union_file_path_edit)
        self.set_save_union_file_path_button = QtWidgets.QPushButton(self.groupBox_3)
        self.set_save_union_file_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.set_save_union_file_path_button.setObjectName("set_save_union_file_path_button")
        self.horizontalLayout_5.addWidget(self.set_save_union_file_path_button)
        self.open_save_union_file_path_button = QtWidgets.QPushButton(self.groupBox_3)
        self.open_save_union_file_path_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.open_save_union_file_path_button.setObjectName("open_save_union_file_path_button")
        self.horizontalLayout_5.addWidget(self.open_save_union_file_path_button)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.exec_create_union_model_button = QtWidgets.QPushButton(self.centralwidget)
        self.exec_create_union_model_button.setObjectName("exec_create_union_model_button")
        self.verticalLayout.addWidget(self.exec_create_union_model_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "合体する部位のパス設定", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Bodyファイルパス", None, -1))
        self.set_body_file_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.open_body_file_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Bodyファイルパスを設定後、dress_data.csvのパスを入力またはチェックボックスにチェックを入れた状態で\n"
"BodyファイルのパスからHead, Tailファイルパスを自動設定ボタンを押すと\n"
"dress_data.csvの値に応じて自動的にパスが設定されます", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "dress_data.csvのパス", None, -1))
        self.set_dress_data_csv_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.open_dress_data_csv_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.use_tool_dress_data_csv_cb.setText(QtWidgets.QApplication.translate("MainWindow", "ツール側のdress_data.csvを利用する", None, -1))
        self.exec_set_union_file_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "BodyファイルのパスからHead, Tailファイルパスを自動設定", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Headファイルパス", None, -1))
        self.set_head_file_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.open_head_file_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Tailファイルパス", None, -1))
        self.set_tail_file_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.open_tail_file_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "合体するモデルの保存パス設定", None, -1))
        self.set_save_union_file_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.open_save_union_file_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.exec_create_union_model_button.setText(QtWidgets.QApplication.translate("MainWindow", "合体モデルを作成", None, -1))

