# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_timewarp_baker\glp_timewarp_baker_window.ui'
#
# Created: Mon Jan 23 11:48:09 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 305)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.target_select_group = QtWidgets.QGroupBox(self.centralwidget)
        self.target_select_group.setObjectName("target_select_group")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.target_select_group)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.selection_only_radio = QtWidgets.QRadioButton(self.target_select_group)
        self.selection_only_radio.setChecked(True)
        self.selection_only_radio.setObjectName("selection_only_radio")
        self.horizontalLayout_3.addWidget(self.selection_only_radio)
        self.all_descendents_radio = QtWidgets.QRadioButton(self.target_select_group)
        self.all_descendents_radio.setObjectName("all_descendents_radio")
        self.horizontalLayout_3.addWidget(self.all_descendents_radio)
        self.all_keyed_radio = QtWidgets.QRadioButton(self.target_select_group)
        self.all_keyed_radio.setObjectName("all_keyed_radio")
        self.horizontalLayout_3.addWidget(self.all_keyed_radio)
        self.verticalLayout_3.addWidget(self.target_select_group)
        self.bake_frame_group = QtWidgets.QGroupBox(self.centralwidget)
        self.bake_frame_group.setObjectName("bake_frame_group")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bake_frame_group)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_frame_label = QtWidgets.QLabel(self.bake_frame_group)
        self.start_frame_label.setObjectName("start_frame_label")
        self.horizontalLayout.addWidget(self.start_frame_label)
        self.start_frame_box = QtWidgets.QSpinBox(self.bake_frame_group)
        self.start_frame_box.setMinimumSize(QtCore.QSize(80, 0))
        self.start_frame_box.setMaximum(1000000)
        self.start_frame_box.setObjectName("start_frame_box")
        self.horizontalLayout.addWidget(self.start_frame_box)
        self.line = QtWidgets.QFrame(self.bake_frame_group)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.end_frame_label = QtWidgets.QLabel(self.bake_frame_group)
        self.end_frame_label.setObjectName("end_frame_label")
        self.horizontalLayout.addWidget(self.end_frame_label)
        self.end_frame_box = QtWidgets.QSpinBox(self.bake_frame_group)
        self.end_frame_box.setMinimumSize(QtCore.QSize(80, 0))
        self.end_frame_box.setMaximum(1000000)
        self.end_frame_box.setObjectName("end_frame_box")
        self.horizontalLayout.addWidget(self.end_frame_box)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_adj_scene_button = QtWidgets.QPushButton(self.bake_frame_group)
        self.frame_adj_scene_button.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_adj_scene_button.setObjectName("frame_adj_scene_button")
        self.horizontalLayout_2.addWidget(self.frame_adj_scene_button)
        self.frame_adj_max_key_button = QtWidgets.QPushButton(self.bake_frame_group)
        self.frame_adj_max_key_button.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_adj_max_key_button.setObjectName("frame_adj_max_key_button")
        self.horizontalLayout_2.addWidget(self.frame_adj_max_key_button)
        self.frame_adj_timewarp_button = QtWidgets.QPushButton(self.bake_frame_group)
        self.frame_adj_timewarp_button.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_adj_timewarp_button.setObjectName("frame_adj_timewarp_button")
        self.horizontalLayout_2.addWidget(self.frame_adj_timewarp_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.bake_frame_group)
        self.bake_exe_group = QtWidgets.QGroupBox(self.centralwidget)
        self.bake_exe_group.setObjectName("bake_exe_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bake_exe_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.merge_bake_result_check = QtWidgets.QCheckBox(self.bake_exe_group)
        self.merge_bake_result_check.setChecked(True)
        self.merge_bake_result_check.setObjectName("merge_bake_result_check")
        self.verticalLayout_2.addWidget(self.merge_bake_result_check)
        self.delete_timewarp_check = QtWidgets.QCheckBox(self.bake_exe_group)
        self.delete_timewarp_check.setChecked(True)
        self.delete_timewarp_check.setObjectName("delete_timewarp_check")
        self.verticalLayout_2.addWidget(self.delete_timewarp_check)
        self.bake_exe_button = QtWidgets.QPushButton(self.bake_exe_group)
        self.bake_exe_button.setMinimumSize(QtCore.QSize(350, 40))
        self.bake_exe_button.setObjectName("bake_exe_button")
        self.verticalLayout_2.addWidget(self.bake_exe_button)
        self.verticalLayout_3.addWidget(self.bake_exe_group)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.target_select_group.setTitle(QtWidgets.QApplication.translate("MainWindow", "対象オブジェクト指定", None, -1))
        self.selection_only_radio.setText(QtWidgets.QApplication.translate("MainWindow", "選択オブジェクトのみ", None, -1))
        self.all_descendents_radio.setText(QtWidgets.QApplication.translate("MainWindow", "選択オブジェクトの子階層を含む", None, -1))
        self.all_keyed_radio.setText(QtWidgets.QApplication.translate("MainWindow", "キーが打たれている全オブジェクト", None, -1))
        self.bake_frame_group.setTitle(QtWidgets.QApplication.translate("MainWindow", "ベイクフレーム指定", None, -1))
        self.start_frame_label.setText(QtWidgets.QApplication.translate("MainWindow", "開始フレーム", None, -1))
        self.end_frame_label.setText(QtWidgets.QApplication.translate("MainWindow", "終了フレーム", None, -1))
        self.frame_adj_scene_button.setText(QtWidgets.QApplication.translate("MainWindow", "シーン幅", None, -1))
        self.frame_adj_max_key_button.setText(QtWidgets.QApplication.translate("MainWindow", "対象オブジェクトのキーフレーム", None, -1))
        self.frame_adj_timewarp_button.setText(QtWidgets.QApplication.translate("MainWindow", "タイムワープ幅", None, -1))
        self.bake_exe_group.setTitle(QtWidgets.QApplication.translate("MainWindow", "ベイク実行", None, -1))
        self.merge_bake_result_check.setText(QtWidgets.QApplication.translate("MainWindow", "ベイクに使用した全レイヤーをBaseAnimationにマージ", None, -1))
        self.delete_timewarp_check.setText(QtWidgets.QApplication.translate("MainWindow", "ベイク後にTimeWarpノードを削除", None, -1))
        self.bake_exe_button.setText(QtWidgets.QApplication.translate("MainWindow", "対象オブジェクトにタイムワープをベイク", None, -1))

