# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_normal_editor\ui\normalEditorWindow.ui'
#
# Created: Wed Sep 20 16:10:16 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_GallopNormalEditorWin(object):
    def setupUi(self, GallopNormalEditorWin):
        GallopNormalEditorWin.setObjectName("GallopNormalEditorWin")
        GallopNormalEditorWin.resize(496, 848)
        self.centralwidget = QtWidgets.QWidget(GallopNormalEditorWin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -620, 473, 1644))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.SetVtxNormalFromEdge = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.SetVtxNormalFromEdge.setMinimumSize(QtCore.QSize(0, 0))
        self.SetVtxNormalFromEdge.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SetVtxNormalFromEdge.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SetVtxNormalFromEdge.setObjectName("SetVtxNormalFromEdge")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.SetVtxNormalFromEdge)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.setNormWithSelectEdgeVLO = QtWidgets.QVBoxLayout()
        self.setNormWithSelectEdgeVLO.setObjectName("setNormWithSelectEdgeVLO")
        self.setNormWithSelectEdgeBtn = QtWidgets.QPushButton(self.SetVtxNormalFromEdge)
        self.setNormWithSelectEdgeBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.setNormWithSelectEdgeBtn.setStyleSheet("#setNormWithSelectEdgeBtn{background-color:#b38080;color:#000;}")
        self.setNormWithSelectEdgeBtn.setObjectName("setNormWithSelectEdgeBtn")
        self.setNormWithSelectEdgeVLO.addWidget(self.setNormWithSelectEdgeBtn)
        self.setNormWithSelectEdgeCB = QtWidgets.QCheckBox(self.SetVtxNormalFromEdge)
        self.setNormWithSelectEdgeCB.setObjectName("setNormWithSelectEdgeCB")
        self.setNormWithSelectEdgeVLO.addWidget(self.setNormWithSelectEdgeCB)
        self.gridLayout_19.addLayout(self.setNormWithSelectEdgeVLO, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.SetVtxNormalFromEdge, 19, 0, 1, 1)
        self.ShiftNormal = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.ShiftNormal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ShiftNormal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ShiftNormal.setObjectName("ShiftNormal")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.ShiftNormal)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.slideNormVLO = QtWidgets.QVBoxLayout()
        self.slideNormVLO.setContentsMargins(-1, 10, -1, 10)
        self.slideNormVLO.setObjectName("slideNormVLO")
        self.slideNormSliderHLO = QtWidgets.QHBoxLayout()
        self.slideNormSliderHLO.setContentsMargins(0, 0, -1, 0)
        self.slideNormSliderHLO.setObjectName("slideNormSliderHLO")
        self.slideNormSliderLbl = QtWidgets.QLabel(self.ShiftNormal)
        self.slideNormSliderLbl.setObjectName("slideNormSliderLbl")
        self.slideNormSliderHLO.addWidget(self.slideNormSliderLbl)
        self.slideNormSliderSpin = QtWidgets.QDoubleSpinBox(self.ShiftNormal)
        self.slideNormSliderSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.slideNormSliderSpin.setMaximum(2.0)
        self.slideNormSliderSpin.setProperty("value", 0.1)
        self.slideNormSliderSpin.setObjectName("slideNormSliderSpin")
        self.slideNormSliderHLO.addWidget(self.slideNormSliderSpin)
        self.slideNormSlider = QtWidgets.QSlider(self.ShiftNormal)
        self.slideNormSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.slideNormSlider.setMaximum(200)
        self.slideNormSlider.setProperty("value", 10)
        self.slideNormSlider.setOrientation(QtCore.Qt.Horizontal)
        self.slideNormSlider.setObjectName("slideNormSlider")
        self.slideNormSliderHLO.addWidget(self.slideNormSlider)
        self.slideNormVLO.addLayout(self.slideNormSliderHLO)
        self.slideNormHGrpFrame = QtWidgets.QFrame(self.ShiftNormal)
        self.slideNormHGrpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slideNormHGrpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slideNormHGrpFrame.setObjectName("slideNormHGrpFrame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.slideNormHGrpFrame)
        self.gridLayout_13.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.slideNormHGrpHLO = QtWidgets.QHBoxLayout()
        self.slideNormHGrpHLO.setContentsMargins(-1, 0, -1, 0)
        self.slideNormHGrpHLO.setObjectName("slideNormHGrpHLO")
        self.slideNormHGrpLbl = QtWidgets.QLabel(self.slideNormHGrpFrame)
        self.slideNormHGrpLbl.setMinimumSize(QtCore.QSize(70, 0))
        self.slideNormHGrpLbl.setObjectName("slideNormHGrpLbl")
        self.slideNormHGrpHLO.addWidget(self.slideNormHGrpLbl)
        self.slideNormHGrpDec = QtWidgets.QPushButton(self.slideNormHGrpFrame)
        self.slideNormHGrpDec.setMinimumSize(QtCore.QSize(93, 0))
        self.slideNormHGrpDec.setStyleSheet("#slideNormHGrpDec{background-color:#809a80;color:#000;}")
        self.slideNormHGrpDec.setObjectName("slideNormHGrpDec")
        self.slideNormHGrpHLO.addWidget(self.slideNormHGrpDec)
        self.slideNormHGrpAdd = QtWidgets.QPushButton(self.slideNormHGrpFrame)
        self.slideNormHGrpAdd.setMinimumSize(QtCore.QSize(93, 0))
        self.slideNormHGrpAdd.setStyleSheet("#slideNormHGrpAdd{background-color:#80809a;color:#000;}")
        self.slideNormHGrpAdd.setObjectName("slideNormHGrpAdd")
        self.slideNormHGrpHLO.addWidget(self.slideNormHGrpAdd)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.slideNormHGrpHLO.addItem(spacerItem)
        self.gridLayout_13.addLayout(self.slideNormHGrpHLO, 0, 0, 1, 1)
        self.slideNormVLO.addWidget(self.slideNormHGrpFrame)
        self.slideNormVGrpFrame = QtWidgets.QFrame(self.ShiftNormal)
        self.slideNormVGrpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slideNormVGrpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slideNormVGrpFrame.setObjectName("slideNormVGrpFrame")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.slideNormVGrpFrame)
        self.gridLayout_14.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.slideNormHGrpHLO_2 = QtWidgets.QHBoxLayout()
        self.slideNormHGrpHLO_2.setContentsMargins(-1, 0, -1, 0)
        self.slideNormHGrpHLO_2.setObjectName("slideNormHGrpHLO_2")
        self.slideNormVGrpLbl = QtWidgets.QLabel(self.slideNormVGrpFrame)
        self.slideNormVGrpLbl.setMinimumSize(QtCore.QSize(70, 0))
        self.slideNormVGrpLbl.setObjectName("slideNormVGrpLbl")
        self.slideNormHGrpHLO_2.addWidget(self.slideNormVGrpLbl)
        self.slideNormVGrpDec = QtWidgets.QPushButton(self.slideNormVGrpFrame)
        self.slideNormVGrpDec.setMinimumSize(QtCore.QSize(93, 0))
        self.slideNormVGrpDec.setStyleSheet("#slideNormVGrpDec{background-color:#809a80;color:#000;}")
        self.slideNormVGrpDec.setObjectName("slideNormVGrpDec")
        self.slideNormHGrpHLO_2.addWidget(self.slideNormVGrpDec)
        self.slideNormVGrpAdd = QtWidgets.QPushButton(self.slideNormVGrpFrame)
        self.slideNormVGrpAdd.setMinimumSize(QtCore.QSize(93, 0))
        self.slideNormVGrpAdd.setStyleSheet("#slideNormVGrpAdd{background-color:#80809a;color:#000;}")
        self.slideNormVGrpAdd.setObjectName("slideNormVGrpAdd")
        self.slideNormHGrpHLO_2.addWidget(self.slideNormVGrpAdd)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.slideNormHGrpHLO_2.addItem(spacerItem1)
        self.gridLayout_14.addLayout(self.slideNormHGrpHLO_2, 0, 0, 1, 1)
        self.slideNormVLO.addWidget(self.slideNormVGrpFrame)
        self.gridLayout_12.addLayout(self.slideNormVLO, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.ShiftNormal, 5, 0, 1, 1)
        self.normSmothGrpBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.normSmothGrpBtn.setStyleSheet("#normSmothGrpBtn{text-align: left;}")
        self.normSmothGrpBtn.setObjectName("normSmothGrpBtn")
        self.gridLayout_5.addWidget(self.normSmothGrpBtn, 6, 0, 1, 1)
        self.AdjustVtxNormal = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.AdjustVtxNormal.setMinimumSize(QtCore.QSize(0, 0))
        self.AdjustVtxNormal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AdjustVtxNormal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AdjustVtxNormal.setObjectName("AdjustVtxNormal")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.AdjustVtxNormal)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.normSPVLO = QtWidgets.QVBoxLayout()
        self.normSPVLO.setObjectName("normSPVLO")
        self.normSPBtn = QtWidgets.QPushButton(self.AdjustVtxNormal)
        self.normSPBtn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normSPBtn.setFont(font)
        self.normSPBtn.setStyleSheet("#normSPBtn{background-color:#b38080;color:#000;}")
        self.normSPBtn.setObjectName("normSPBtn")
        self.normSPVLO.addWidget(self.normSPBtn)
        self.normSPCheck = QtWidgets.QCheckBox(self.AdjustVtxNormal)
        self.normSPCheck.setObjectName("normSPCheck")
        self.normSPVLO.addWidget(self.normSPCheck)
        self.gridLayout_18.addLayout(self.normSPVLO, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.AdjustVtxNormal, 17, 0, 1, 1)
        self.AdjustVtxNormalGrpBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.AdjustVtxNormalGrpBtn.setStyleSheet("#AdjustVtxNormalGrpBtn{text-align: left;}")
        self.AdjustVtxNormalGrpBtn.setObjectName("AdjustVtxNormalGrpBtn")
        self.gridLayout_5.addWidget(self.AdjustVtxNormalGrpBtn, 16, 0, 1, 1)
        self.normBlendGrpBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.normBlendGrpBtn.setStyleSheet("#normBlendGrpBtn{text-align: left;}")
        self.normBlendGrpBtn.setObjectName("normBlendGrpBtn")
        self.gridLayout_5.addWidget(self.normBlendGrpBtn, 12, 0, 1, 1)
        self.basicNormToolGrpBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.basicNormToolGrpBtn.setStyleSheet("#basicNormToolGrpBtn{text-align: left;}")
        self.basicNormToolGrpBtn.setObjectName("basicNormToolGrpBtn")
        self.gridLayout_5.addWidget(self.basicNormToolGrpBtn, 0, 0, 1, 1)
        self.normCopyGrpBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.normCopyGrpBtn.setStyleSheet("#normCopyGrpBtn{text-align: left;}")
        self.normCopyGrpBtn.setObjectName("normCopyGrpBtn")
        self.gridLayout_5.addWidget(self.normCopyGrpBtn, 14, 0, 1, 1)
        self.setNormWithSelectEdgeGrpBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.setNormWithSelectEdgeGrpBtn.setStyleSheet("#setNormWithSelectEdgeGrpBtn{text-align: left;}")
        self.setNormWithSelectEdgeGrpBtn.setObjectName("setNormWithSelectEdgeGrpBtn")
        self.gridLayout_5.addWidget(self.setNormWithSelectEdgeGrpBtn, 18, 0, 1, 1)
        self.CopyNormal = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.CopyNormal.setMinimumSize(QtCore.QSize(0, 0))
        self.CopyNormal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CopyNormal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CopyNormal.setObjectName("CopyNormal")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.CopyNormal)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.normCopyVLO = QtWidgets.QVBoxLayout()
        self.normCopyVLO.setContentsMargins(-1, 0, -1, 0)
        self.normCopyVLO.setObjectName("normCopyVLO")
        self.normCopyBtn = QtWidgets.QPushButton(self.CopyNormal)
        self.normCopyBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.normCopyBtn.setStyleSheet("#normCopyBtn{background-color:#b38080;color:#000;}")
        self.normCopyBtn.setObjectName("normCopyBtn")
        self.normCopyVLO.addWidget(self.normCopyBtn)
        self.normCopySetingCBHLO = QtWidgets.QHBoxLayout()
        self.normCopySetingCBHLO.setContentsMargins(-1, 0, -1, 0)
        self.normCopySetingCBHLO.setObjectName("normCopySetingCBHLO")
        self.normCopySetingOnlyLock = QtWidgets.QCheckBox(self.CopyNormal)
        self.normCopySetingOnlyLock.setObjectName("normCopySetingOnlyLock")
        self.normCopySetingCBHLO.addWidget(self.normCopySetingOnlyLock)
        self.normCopySetingkeepOrgEdge = QtWidgets.QCheckBox(self.CopyNormal)
        self.normCopySetingkeepOrgEdge.setChecked(True)
        self.normCopySetingkeepOrgEdge.setObjectName("normCopySetingkeepOrgEdge")
        self.normCopySetingCBHLO.addWidget(self.normCopySetingkeepOrgEdge)
        self.normCopyVLO.addLayout(self.normCopySetingCBHLO)
        self.pasteWithSelectionBtn = QtWidgets.QPushButton(self.CopyNormal)
        self.pasteWithSelectionBtn.setStyleSheet("#pasteWithSelectionBtn{background-color:#cdcd80;color:#000;}")
        self.pasteWithSelectionBtn.setObjectName("pasteWithSelectionBtn")
        self.normCopyVLO.addWidget(self.pasteWithSelectionBtn)
        self.pasteWithIndexBtn = QtWidgets.QPushButton(self.CopyNormal)
        self.pasteWithIndexBtn.setStyleSheet("#pasteWithIndexBtn{background-color:#cdcd80;color:#000;}")
        self.pasteWithIndexBtn.setObjectName("pasteWithIndexBtn")
        self.normCopyVLO.addWidget(self.pasteWithIndexBtn)
        self.line = QtWidgets.QFrame(self.CopyNormal)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.normCopyVLO.addWidget(self.line)
        self.pasteWithPositionBtn = QtWidgets.QPushButton(self.CopyNormal)
        self.pasteWithPositionBtn.setStyleSheet("#pasteWithPositionBtn{background-color:#cdcd80;color:#000;}")
        self.pasteWithPositionBtn.setObjectName("pasteWithPositionBtn")
        self.normCopyVLO.addWidget(self.pasteWithPositionBtn)
        self.pasteSpaceBox = QtWidgets.QGroupBox(self.CopyNormal)
        self.pasteSpaceBox.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pasteSpaceBox.setFont(font)
        self.pasteSpaceBox.setObjectName("pasteSpaceBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pasteSpaceBox)
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pasteByWorldRadio = QtWidgets.QRadioButton(self.pasteSpaceBox)
        self.pasteByWorldRadio.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pasteByWorldRadio.setChecked(True)
        self.pasteByWorldRadio.setObjectName("pasteByWorldRadio")
        self.horizontalLayout.addWidget(self.pasteByWorldRadio)
        self.pasteByLocalRadio = QtWidgets.QRadioButton(self.pasteSpaceBox)
        self.pasteByLocalRadio.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pasteByLocalRadio.setObjectName("pasteByLocalRadio")
        self.horizontalLayout.addWidget(self.pasteByLocalRadio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.normCopyVLO.addWidget(self.pasteSpaceBox)
        self.mirrorOptionBox = QtWidgets.QGroupBox(self.CopyNormal)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.mirrorOptionBox.setFont(font)
        self.mirrorOptionBox.setObjectName("mirrorOptionBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.mirrorOptionBox)
        self.horizontalLayout_5.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.normCopyMirrorRadioNoMirror = QtWidgets.QRadioButton(self.mirrorOptionBox)
        self.normCopyMirrorRadioNoMirror.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normCopyMirrorRadioNoMirror.setFont(font)
        self.normCopyMirrorRadioNoMirror.setChecked(True)
        self.normCopyMirrorRadioNoMirror.setObjectName("normCopyMirrorRadioNoMirror")
        self.horizontalLayout_5.addWidget(self.normCopyMirrorRadioNoMirror)
        self.normCopyMirrorRadioXMirror = QtWidgets.QRadioButton(self.mirrorOptionBox)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normCopyMirrorRadioXMirror.setFont(font)
        self.normCopyMirrorRadioXMirror.setObjectName("normCopyMirrorRadioXMirror")
        self.horizontalLayout_5.addWidget(self.normCopyMirrorRadioXMirror)
        self.normCopyMirrorRadioYMirror = QtWidgets.QRadioButton(self.mirrorOptionBox)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normCopyMirrorRadioYMirror.setFont(font)
        self.normCopyMirrorRadioYMirror.setObjectName("normCopyMirrorRadioYMirror")
        self.horizontalLayout_5.addWidget(self.normCopyMirrorRadioYMirror)
        self.normCopyMirrorRadioZMirror = QtWidgets.QRadioButton(self.mirrorOptionBox)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normCopyMirrorRadioZMirror.setFont(font)
        self.normCopyMirrorRadioZMirror.setObjectName("normCopyMirrorRadioZMirror")
        self.horizontalLayout_5.addWidget(self.normCopyMirrorRadioZMirror)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.normCopyVLO.addWidget(self.mirrorOptionBox)
        self.normCopyMirrorNormal = QtWidgets.QCheckBox(self.CopyNormal)
        self.normCopyMirrorNormal.setObjectName("normCopyMirrorNormal")
        self.normCopyVLO.addWidget(self.normCopyMirrorNormal)
        self.gridLayout_17.addLayout(self.normCopyVLO, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.CopyNormal, 15, 0, 1, 1)
        self.General = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.General.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.General.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.General.setFrameShadow(QtWidgets.QFrame.Raised)
        self.General.setObjectName("General")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.General)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.showNormalGrpFrame = QtWidgets.QFrame(self.General)
        self.showNormalGrpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.showNormalGrpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.showNormalGrpFrame.setObjectName("showNormalGrpFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.showNormalGrpFrame)
        self.gridLayout_4.setContentsMargins(10, 2, 10, 2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.showNormalGrp = QtWidgets.QHBoxLayout()
        self.showNormalGrp.setObjectName("showNormalGrp")
        self.showNormalLbl = QtWidgets.QLabel(self.showNormalGrpFrame)
        self.showNormalLbl.setMinimumSize(QtCore.QSize(70, 0))
        self.showNormalLbl.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.showNormalLbl.setFont(font)
        self.showNormalLbl.setObjectName("showNormalLbl")
        self.showNormalGrp.addWidget(self.showNormalLbl)
        self.showNormalHideBtn = QtWidgets.QPushButton(self.showNormalGrpFrame)
        self.showNormalHideBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.showNormalHideBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.showNormalHideBtn.setFont(font)
        self.showNormalHideBtn.setStyleSheet("#showNormalHideBtn{background-color:#809a80;color:#000;}")
        self.showNormalHideBtn.setObjectName("showNormalHideBtn")
        self.showNormalGrp.addWidget(self.showNormalHideBtn)
        self.showNormalVtxBtn = QtWidgets.QPushButton(self.showNormalGrpFrame)
        self.showNormalVtxBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.showNormalVtxBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.showNormalVtxBtn.setFont(font)
        self.showNormalVtxBtn.setStyleSheet("#showNormalVtxBtn{background-color:#80809a;color:#000;}")
        self.showNormalVtxBtn.setObjectName("showNormalVtxBtn")
        self.showNormalGrp.addWidget(self.showNormalVtxBtn)
        self.showNormalFaceBtn = QtWidgets.QPushButton(self.showNormalGrpFrame)
        self.showNormalFaceBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.showNormalFaceBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.showNormalFaceBtn.setFont(font)
        self.showNormalFaceBtn.setStyleSheet("#showNormalFaceBtn{background-color:#80809a;color:#000;}")
        self.showNormalFaceBtn.setObjectName("showNormalFaceBtn")
        self.showNormalGrp.addWidget(self.showNormalFaceBtn)
        self.showNormalBothBtn = QtWidgets.QPushButton(self.showNormalGrpFrame)
        self.showNormalBothBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.showNormalBothBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.showNormalBothBtn.setFont(font)
        self.showNormalBothBtn.setStyleSheet("#showNormalBothBtn{background-color:#80809a;color:#000;}")
        self.showNormalBothBtn.setObjectName("showNormalBothBtn")
        self.showNormalGrp.addWidget(self.showNormalBothBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.showNormalGrp.addItem(spacerItem4)
        self.gridLayout_4.addLayout(self.showNormalGrp, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.showNormalGrpFrame)
        self.normalSizeFrame = QtWidgets.QFrame(self.General)
        self.normalSizeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.normalSizeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.normalSizeFrame.setObjectName("normalSizeFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.normalSizeFrame)
        self.gridLayout_6.setContentsMargins(10, 2, 10, 2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.normalSizeHLO = QtWidgets.QHBoxLayout()
        self.normalSizeHLO.setObjectName("normalSizeHLO")
        self.normalSizeLbl = QtWidgets.QLabel(self.normalSizeFrame)
        self.normalSizeLbl.setMinimumSize(QtCore.QSize(70, 0))
        self.normalSizeLbl.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.normalSizeLbl.setFont(font)
        self.normalSizeLbl.setObjectName("normalSizeLbl")
        self.normalSizeHLO.addWidget(self.normalSizeLbl)
        self.normalSizeDownBtn = QtWidgets.QPushButton(self.normalSizeFrame)
        self.normalSizeDownBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.normalSizeDownBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normalSizeDownBtn.setFont(font)
        self.normalSizeDownBtn.setStyleSheet("#normalSizeDownBtn{background-color:#80809a;color:#000;}")
        self.normalSizeDownBtn.setObjectName("normalSizeDownBtn")
        self.normalSizeHLO.addWidget(self.normalSizeDownBtn)
        self.normalSizeUpBtn = QtWidgets.QPushButton(self.normalSizeFrame)
        self.normalSizeUpBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.normalSizeUpBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normalSizeUpBtn.setFont(font)
        self.normalSizeUpBtn.setStyleSheet("#normalSizeUpBtn{background-color:#9a8080;color:#000;}")
        self.normalSizeUpBtn.setObjectName("normalSizeUpBtn")
        self.normalSizeHLO.addWidget(self.normalSizeUpBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.normalSizeHLO.addItem(spacerItem5)
        self.gridLayout_6.addLayout(self.normalSizeHLO, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.normalSizeFrame)
        self.normalLockFrame = QtWidgets.QFrame(self.General)
        self.normalLockFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.normalLockFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.normalLockFrame.setObjectName("normalLockFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.normalLockFrame)
        self.gridLayout.setContentsMargins(10, 2, 10, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.normalLockHLO = QtWidgets.QHBoxLayout()
        self.normalLockHLO.setObjectName("normalLockHLO")
        self.normalLockLbl = QtWidgets.QLabel(self.normalLockFrame)
        self.normalLockLbl.setMinimumSize(QtCore.QSize(70, 0))
        self.normalLockLbl.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.normalLockLbl.setFont(font)
        self.normalLockLbl.setObjectName("normalLockLbl")
        self.normalLockHLO.addWidget(self.normalLockLbl)
        self.normalLockLockBtn = QtWidgets.QPushButton(self.normalLockFrame)
        self.normalLockLockBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.normalLockLockBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normalLockLockBtn.setFont(font)
        self.normalLockLockBtn.setStyleSheet("#normalLockLockBtn{background-color:#b3b366;color:#000;}")
        self.normalLockLockBtn.setObjectName("normalLockLockBtn")
        self.normalLockHLO.addWidget(self.normalLockLockBtn)
        self.normalLockUnlockBtn = QtWidgets.QPushButton(self.normalLockFrame)
        self.normalLockUnlockBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.normalLockUnlockBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normalLockUnlockBtn.setFont(font)
        self.normalLockUnlockBtn.setStyleSheet("#normalLockUnlockBtn{background-color:#669a66;color:#000;}")
        self.normalLockUnlockBtn.setObjectName("normalLockUnlockBtn")
        self.normalLockHLO.addWidget(self.normalLockUnlockBtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.normalLockHLO.addItem(spacerItem6)
        self.gridLayout.addLayout(self.normalLockHLO, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.normalLockFrame)
        self.edgeFrame = QtWidgets.QFrame(self.General)
        self.edgeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edgeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edgeFrame.setObjectName("edgeFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.edgeFrame)
        self.gridLayout_7.setContentsMargins(10, 2, 10, 2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.EdgeHLO = QtWidgets.QHBoxLayout()
        self.EdgeHLO.setObjectName("EdgeHLO")
        self.EdgeLbl = QtWidgets.QLabel(self.edgeFrame)
        self.EdgeLbl.setMinimumSize(QtCore.QSize(70, 0))
        self.EdgeLbl.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.EdgeLbl.setFont(font)
        self.EdgeLbl.setObjectName("EdgeLbl")
        self.EdgeHLO.addWidget(self.EdgeLbl)
        self.EdgeHardBtn = QtWidgets.QPushButton(self.edgeFrame)
        self.EdgeHardBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.EdgeHardBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.EdgeHardBtn.setFont(font)
        self.EdgeHardBtn.setStyleSheet("#EdgeHardBtn{background-color:#9a80b3;color:#000;}")
        self.EdgeHardBtn.setObjectName("EdgeHardBtn")
        self.EdgeHLO.addWidget(self.EdgeHardBtn)
        self.edgeSoftBtn = QtWidgets.QPushButton(self.edgeFrame)
        self.edgeSoftBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.edgeSoftBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.edgeSoftBtn.setFont(font)
        self.edgeSoftBtn.setStyleSheet("#edgeSoftBtn{background-color:#9a9a80;color:#000;}")
        self.edgeSoftBtn.setObjectName("edgeSoftBtn")
        self.EdgeHLO.addWidget(self.edgeSoftBtn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.EdgeHLO.addItem(spacerItem7)
        self.gridLayout_7.addLayout(self.EdgeHLO, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.edgeFrame)
        self.showEdgeFrame = QtWidgets.QFrame(self.General)
        self.showEdgeFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.showEdgeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.showEdgeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.showEdgeFrame.setObjectName("showEdgeFrame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.showEdgeFrame)
        self.gridLayout_9.setContentsMargins(10, 2, 10, 2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.showEdgeHLO = QtWidgets.QHBoxLayout()
        self.showEdgeHLO.setObjectName("showEdgeHLO")
        self.showEdgeLbl = QtWidgets.QLabel(self.showEdgeFrame)
        self.showEdgeLbl.setMinimumSize(QtCore.QSize(70, 0))
        self.showEdgeLbl.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.showEdgeLbl.setFont(font)
        self.showEdgeLbl.setObjectName("showEdgeLbl")
        self.showEdgeHLO.addWidget(self.showEdgeLbl)
        self.showEdgeBasicBtn = QtWidgets.QPushButton(self.showEdgeFrame)
        self.showEdgeBasicBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.showEdgeBasicBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.showEdgeBasicBtn.setFont(font)
        self.showEdgeBasicBtn.setStyleSheet("#showEdgeBasicBtn{background-color:#809a80;color:#000;}")
        self.showEdgeBasicBtn.setObjectName("showEdgeBasicBtn")
        self.showEdgeHLO.addWidget(self.showEdgeBasicBtn)
        self.showEdgeHardAndSoftBtn = QtWidgets.QPushButton(self.showEdgeFrame)
        self.showEdgeHardAndSoftBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.showEdgeHardAndSoftBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.showEdgeHardAndSoftBtn.setFont(font)
        self.showEdgeHardAndSoftBtn.setStyleSheet("#showEdgeHardAndSoftBtn{background-color:#80809a;color:#000;}")
        self.showEdgeHardAndSoftBtn.setObjectName("showEdgeHardAndSoftBtn")
        self.showEdgeHLO.addWidget(self.showEdgeHardAndSoftBtn)
        self.showEdgeColoredHardBtn = QtWidgets.QPushButton(self.showEdgeFrame)
        self.showEdgeColoredHardBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.showEdgeColoredHardBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.showEdgeColoredHardBtn.setFont(font)
        self.showEdgeColoredHardBtn.setStyleSheet("#showEdgeColoredHardBtn{background-color:#80809a;color:#000;}")
        self.showEdgeColoredHardBtn.setObjectName("showEdgeColoredHardBtn")
        self.showEdgeHLO.addWidget(self.showEdgeColoredHardBtn)
        self.showEdgeOnlyHardBtn = QtWidgets.QPushButton(self.showEdgeFrame)
        self.showEdgeOnlyHardBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.showEdgeOnlyHardBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.showEdgeOnlyHardBtn.setFont(font)
        self.showEdgeOnlyHardBtn.setStyleSheet("#showEdgeOnlyHardBtn{background-color:#80809a;color:#000;}")
        self.showEdgeOnlyHardBtn.setObjectName("showEdgeOnlyHardBtn")
        self.showEdgeHLO.addWidget(self.showEdgeOnlyHardBtn)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.showEdgeHLO.addItem(spacerItem8)
        self.gridLayout_9.addLayout(self.showEdgeHLO, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.showEdgeFrame)
        self.normToolFrame = QtWidgets.QFrame(self.General)
        self.normToolFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.normToolFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.normToolFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.normToolFrame.setObjectName("normToolFrame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.normToolFrame)
        self.gridLayout_8.setContentsMargins(10, 2, 10, 2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.normToolHLO = QtWidgets.QHBoxLayout()
        self.normToolHLO.setObjectName("normToolHLO")
        self.normToolLbl = QtWidgets.QLabel(self.normToolFrame)
        self.normToolLbl.setMinimumSize(QtCore.QSize(70, 0))
        self.normToolLbl.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.normToolLbl.setFont(font)
        self.normToolLbl.setObjectName("normToolLbl")
        self.normToolHLO.addWidget(self.normToolLbl)
        self.normToolActBtn = QtWidgets.QPushButton(self.normToolFrame)
        self.normToolActBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.normToolActBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normToolActBtn.setFont(font)
        self.normToolActBtn.setStyleSheet("#normToolActBtn{background-color:#809a80;color:#000;}")
        self.normToolActBtn.setObjectName("normToolActBtn")
        self.normToolHLO.addWidget(self.normToolActBtn)
        self.normToolDisableBtn = QtWidgets.QPushButton(self.normToolFrame)
        self.normToolDisableBtn.setMinimumSize(QtCore.QSize(70, 0))
        self.normToolDisableBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normToolDisableBtn.setFont(font)
        self.normToolDisableBtn.setStyleSheet("#normToolDisableBtn{background-color:#80809a;color:#000;}")
        self.normToolDisableBtn.setObjectName("normToolDisableBtn")
        self.normToolHLO.addWidget(self.normToolDisableBtn)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.normToolHLO.addItem(spacerItem9)
        self.verticalLayout1.addLayout(self.normToolHLO)
        self.normToolHLO2 = QtWidgets.QHBoxLayout()
        self.normToolHLO2.setObjectName("normToolHLO2")
        self.normToolLbl2 = QtWidgets.QLabel(self.normToolFrame)
        self.normToolLbl2.setMinimumSize(QtCore.QSize(70, 0))
        self.normToolLbl2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.normToolLbl2.setFont(font)
        self.normToolLbl2.setText("")
        self.normToolLbl2.setObjectName("normToolLbl2")
        self.normToolHLO2.addWidget(self.normToolLbl2)
        self.normToolActBtn2 = QtWidgets.QPushButton(self.normToolFrame)
        self.normToolActBtn2.setMinimumSize(QtCore.QSize(70, 0))
        self.normToolActBtn2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normToolActBtn2.setFont(font)
        self.normToolActBtn2.setStyleSheet("#normToolActBtn2{background-color:#809a80;color:#000;}")
        self.normToolActBtn2.setObjectName("normToolActBtn2")
        self.normToolHLO2.addWidget(self.normToolActBtn2)
        self.normToolDisableBtn2 = QtWidgets.QPushButton(self.normToolFrame)
        self.normToolDisableBtn2.setMinimumSize(QtCore.QSize(70, 0))
        self.normToolDisableBtn2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normToolDisableBtn2.setFont(font)
        self.normToolDisableBtn2.setStyleSheet("#normToolDisableBtn2{background-color:#80809a;color:#000;}")
        self.normToolDisableBtn2.setObjectName("normToolDisableBtn2")
        self.normToolHLO2.addWidget(self.normToolDisableBtn2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.normToolHLO2.addItem(spacerItem10)
        self.verticalLayout1.addLayout(self.normToolHLO2)
        self.gridLayout_8.addLayout(self.verticalLayout1, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.normToolFrame)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.General, 1, 0, 1, 1)
        self.inputNumGrpBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.inputNumGrpBtn.setStyleSheet("#inputNumGrpBtn{text-align: left;}")
        self.inputNumGrpBtn.setObjectName("inputNumGrpBtn")
        self.gridLayout_5.addWidget(self.inputNumGrpBtn, 2, 0, 1, 1)
        self.BlendNormal = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.BlendNormal.setMinimumSize(QtCore.QSize(0, 0))
        self.BlendNormal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BlendNormal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BlendNormal.setObjectName("BlendNormal")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.BlendNormal)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.normBlenVLO = QtWidgets.QVBoxLayout()
        self.normBlenVLO.setContentsMargins(-1, 0, -1, 0)
        self.normBlenVLO.setObjectName("normBlenVLO")
        self.normBlendSliderHLO = QtWidgets.QHBoxLayout()
        self.normBlendSliderHLO.setObjectName("normBlendSliderHLO")
        self.normBlendSliderLbl = QtWidgets.QLabel(self.BlendNormal)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normBlendSliderLbl.setFont(font)
        self.normBlendSliderLbl.setObjectName("normBlendSliderLbl")
        self.normBlendSliderHLO.addWidget(self.normBlendSliderLbl)
        self.normBlendSliderSpin = QtWidgets.QDoubleSpinBox(self.BlendNormal)
        self.normBlendSliderSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.normBlendSliderSpin.setObjectName("normBlendSliderSpin")
        self.normBlendSliderHLO.addWidget(self.normBlendSliderSpin)
        self.normBlendSlider = QtWidgets.QSlider(self.BlendNormal)
        self.normBlendSlider.setMaximum(100)
        self.normBlendSlider.setOrientation(QtCore.Qt.Horizontal)
        self.normBlendSlider.setObjectName("normBlendSlider")
        self.normBlendSliderHLO.addWidget(self.normBlendSlider)
        self.normBlenVLO.addLayout(self.normBlendSliderHLO)
        self.normBlendEdgBtn = QtWidgets.QPushButton(self.BlendNormal)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normBlendEdgBtn.setFont(font)
        self.normBlendEdgBtn.setStyleSheet("#normBlendEdgBtn{background-color:#b38080;color:#000;}")
        self.normBlendEdgBtn.setObjectName("normBlendEdgBtn")
        self.normBlenVLO.addWidget(self.normBlendEdgBtn)
        self.gridLayout_16.addLayout(self.normBlenVLO, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.BlendNormal, 13, 0, 1, 1)
        self.SmoothNormal = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.SmoothNormal.setMinimumSize(QtCore.QSize(0, 0))
        self.SmoothNormal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SmoothNormal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SmoothNormal.setObjectName("SmoothNormal")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.SmoothNormal)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.normSmothGrpVLO = QtWidgets.QVBoxLayout()
        self.normSmothGrpVLO.setContentsMargins(-1, 0, -1, 0)
        self.normSmothGrpVLO.setObjectName("normSmothGrpVLO")
        self.normSmothGrpBlendSldHLO = QtWidgets.QHBoxLayout()
        self.normSmothGrpBlendSldHLO.setObjectName("normSmothGrpBlendSldHLO")
        self.normSmothGrpBlendSldLbl = QtWidgets.QLabel(self.SmoothNormal)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normSmothGrpBlendSldLbl.setFont(font)
        self.normSmothGrpBlendSldLbl.setToolTip("")
        self.normSmothGrpBlendSldLbl.setObjectName("normSmothGrpBlendSldLbl")
        self.normSmothGrpBlendSldHLO.addWidget(self.normSmothGrpBlendSldLbl)
        self.normSmothGrpBlendSldSpin = QtWidgets.QDoubleSpinBox(self.SmoothNormal)
        self.normSmothGrpBlendSldSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.normSmothGrpBlendSldSpin.setMaximum(1.0)
        self.normSmothGrpBlendSldSpin.setProperty("value", 0.5)
        self.normSmothGrpBlendSldSpin.setObjectName("normSmothGrpBlendSldSpin")
        self.normSmothGrpBlendSldHLO.addWidget(self.normSmothGrpBlendSldSpin)
        self.normSmothGrpBlendSlider = QtWidgets.QSlider(self.SmoothNormal)
        self.normSmothGrpBlendSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.normSmothGrpBlendSlider.setMaximum(100)
        self.normSmothGrpBlendSlider.setProperty("value", 50)
        self.normSmothGrpBlendSlider.setOrientation(QtCore.Qt.Horizontal)
        self.normSmothGrpBlendSlider.setObjectName("normSmothGrpBlendSlider")
        self.normSmothGrpBlendSldHLO.addWidget(self.normSmothGrpBlendSlider)
        self.normSmothGrpVLO.addLayout(self.normSmothGrpBlendSldHLO)
        self.normSmothGrpRangeSldHLO = QtWidgets.QHBoxLayout()
        self.normSmothGrpRangeSldHLO.setContentsMargins(-1, 0, -1, 0)
        self.normSmothGrpRangeSldHLO.setObjectName("normSmothGrpRangeSldHLO")
        self.normSmothGrpRangeSldLbl = QtWidgets.QLabel(self.SmoothNormal)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normSmothGrpRangeSldLbl.setFont(font)
        self.normSmothGrpRangeSldLbl.setObjectName("normSmothGrpRangeSldLbl")
        self.normSmothGrpRangeSldHLO.addWidget(self.normSmothGrpRangeSldLbl)
        self.normSmothGrpRangeSldSpin = QtWidgets.QDoubleSpinBox(self.SmoothNormal)
        self.normSmothGrpRangeSldSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.normSmothGrpRangeSldSpin.setDecimals(0)
        self.normSmothGrpRangeSldSpin.setMinimum(1.0)
        self.normSmothGrpRangeSldSpin.setMaximum(5.0)
        self.normSmothGrpRangeSldSpin.setObjectName("normSmothGrpRangeSldSpin")
        self.normSmothGrpRangeSldHLO.addWidget(self.normSmothGrpRangeSldSpin)
        self.normSmothGrpRangeSlider = QtWidgets.QSlider(self.SmoothNormal)
        self.normSmothGrpRangeSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.normSmothGrpRangeSlider.setMinimum(1)
        self.normSmothGrpRangeSlider.setMaximum(5)
        self.normSmothGrpRangeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.normSmothGrpRangeSlider.setObjectName("normSmothGrpRangeSlider")
        self.normSmothGrpRangeSldHLO.addWidget(self.normSmothGrpRangeSlider)
        self.checkSmothGrpRangeChk = QtWidgets.QCheckBox(self.SmoothNormal)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkSmothGrpRangeChk.setFont(font)
        self.checkSmothGrpRangeChk.setObjectName("checkSmothGrpRangeChk")
        self.normSmothGrpRangeSldHLO.addWidget(self.checkSmothGrpRangeChk)
        self.normSmothGrpVLO.addLayout(self.normSmothGrpRangeSldHLO)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.normSmothFaceAvgBtn = QtWidgets.QPushButton(self.SmoothNormal)
        self.normSmothFaceAvgBtn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normSmothFaceAvgBtn.setFont(font)
        self.normSmothFaceAvgBtn.setStyleSheet("#normSmothFaceAvgBtn{background-color:#b38080;color:#000;}")
        self.normSmothFaceAvgBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Japanese, QtCore.QLocale.Japan))
        self.normSmothFaceAvgBtn.setObjectName("normSmothFaceAvgBtn")
        self.horizontalLayout_2.addWidget(self.normSmothFaceAvgBtn)
        self.applyOnlyLockedVertexFaceNormalChk1 = QtWidgets.QCheckBox(self.SmoothNormal)
        self.applyOnlyLockedVertexFaceNormalChk1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.applyOnlyLockedVertexFaceNormalChk1.setFont(font)
        self.applyOnlyLockedVertexFaceNormalChk1.setChecked(True)
        self.applyOnlyLockedVertexFaceNormalChk1.setObjectName("applyOnlyLockedVertexFaceNormalChk1")
        self.horizontalLayout_2.addWidget(self.applyOnlyLockedVertexFaceNormalChk1)
        self.normSmothGrpVLO.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.normSmothVtxAvgBtn = QtWidgets.QPushButton(self.SmoothNormal)
        self.normSmothVtxAvgBtn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.normSmothVtxAvgBtn.setFont(font)
        self.normSmothVtxAvgBtn.setStyleSheet("#normSmothVtxAvgBtn{background-color:#b38080;color:#000;}")
        self.normSmothVtxAvgBtn.setObjectName("normSmothVtxAvgBtn")
        self.horizontalLayout_3.addWidget(self.normSmothVtxAvgBtn)
        self.applyOnlyLockedVertexFaceNormalChk2 = QtWidgets.QCheckBox(self.SmoothNormal)
        self.applyOnlyLockedVertexFaceNormalChk2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.applyOnlyLockedVertexFaceNormalChk2.setFont(font)
        self.applyOnlyLockedVertexFaceNormalChk2.setChecked(True)
        self.applyOnlyLockedVertexFaceNormalChk2.setObjectName("applyOnlyLockedVertexFaceNormalChk2")
        self.horizontalLayout_3.addWidget(self.applyOnlyLockedVertexFaceNormalChk2)
        self.normSmothGrpVLO.addLayout(self.horizontalLayout_3)
        self.gridLayout_15.addLayout(self.normSmothGrpVLO, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.SmoothNormal, 8, 0, 1, 1)
        self.slideNormGrpBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.slideNormGrpBtn.setStyleSheet("#slideNormGrpBtn{text-align: left;}")
        self.slideNormGrpBtn.setObjectName("slideNormGrpBtn")
        self.gridLayout_5.addWidget(self.slideNormGrpBtn, 4, 0, 1, 1)
        self.NumericEdit = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.NumericEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NumericEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NumericEdit.setObjectName("NumericEdit")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.NumericEdit)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.inputNumVLO = QtWidgets.QVBoxLayout()
        self.inputNumVLO.setContentsMargins(0, 0, -1, 0)
        self.inputNumVLO.setObjectName("inputNumVLO")
        self.inputNumXHLO = QtWidgets.QHBoxLayout()
        self.inputNumXHLO.setObjectName("inputNumXHLO")
        self.inputNumXLbl = QtWidgets.QLabel(self.NumericEdit)
        self.inputNumXLbl.setObjectName("inputNumXLbl")
        self.inputNumXHLO.addWidget(self.inputNumXLbl)
        self.inputNumXSpin = QtWidgets.QDoubleSpinBox(self.NumericEdit)
        self.inputNumXSpin.setFrame(True)
        self.inputNumXSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inputNumXSpin.setDecimals(4)
        self.inputNumXSpin.setMinimum(-1.0)
        self.inputNumXSpin.setMaximum(1.0)
        self.inputNumXSpin.setSingleStep(0.0001)
        self.inputNumXSpin.setProperty("value", 1.0)
        self.inputNumXSpin.setObjectName("inputNumXSpin")
        self.inputNumXHLO.addWidget(self.inputNumXSpin)
        self.inputNumXHSlider = QtWidgets.QSlider(self.NumericEdit)
        self.inputNumXHSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputNumXHSlider.setMinimum(-10000)
        self.inputNumXHSlider.setMaximum(10000)
        self.inputNumXHSlider.setProperty("value", 10000)
        self.inputNumXHSlider.setOrientation(QtCore.Qt.Horizontal)
        self.inputNumXHSlider.setObjectName("inputNumXHSlider")
        self.inputNumXHLO.addWidget(self.inputNumXHSlider)
        self.inputNumVLO.addLayout(self.inputNumXHLO)
        self.inputNumYHLO = QtWidgets.QHBoxLayout()
        self.inputNumYHLO.setContentsMargins(-1, 0, -1, 0)
        self.inputNumYHLO.setObjectName("inputNumYHLO")
        self.inputNumYLbl = QtWidgets.QLabel(self.NumericEdit)
        self.inputNumYLbl.setObjectName("inputNumYLbl")
        self.inputNumYHLO.addWidget(self.inputNumYLbl)
        self.inputNumYSpin = QtWidgets.QDoubleSpinBox(self.NumericEdit)
        self.inputNumYSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inputNumYSpin.setDecimals(4)
        self.inputNumYSpin.setMinimum(-1.0)
        self.inputNumYSpin.setMaximum(1.0)
        self.inputNumYSpin.setSingleStep(0.0001)
        self.inputNumYSpin.setObjectName("inputNumYSpin")
        self.inputNumYHLO.addWidget(self.inputNumYSpin)
        self.inputNumYHSlider = QtWidgets.QSlider(self.NumericEdit)
        self.inputNumYHSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputNumYHSlider.setMinimum(-10000)
        self.inputNumYHSlider.setMaximum(10000)
        self.inputNumYHSlider.setOrientation(QtCore.Qt.Horizontal)
        self.inputNumYHSlider.setObjectName("inputNumYHSlider")
        self.inputNumYHLO.addWidget(self.inputNumYHSlider)
        self.inputNumVLO.addLayout(self.inputNumYHLO)
        self.inputNumZHLO = QtWidgets.QHBoxLayout()
        self.inputNumZHLO.setContentsMargins(-1, 0, -1, 0)
        self.inputNumZHLO.setObjectName("inputNumZHLO")
        self.inputNumZLbl = QtWidgets.QLabel(self.NumericEdit)
        self.inputNumZLbl.setObjectName("inputNumZLbl")
        self.inputNumZHLO.addWidget(self.inputNumZLbl)
        self.inputNumZSpin = QtWidgets.QDoubleSpinBox(self.NumericEdit)
        self.inputNumZSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inputNumZSpin.setDecimals(4)
        self.inputNumZSpin.setMinimum(-1.0)
        self.inputNumZSpin.setMaximum(1.0)
        self.inputNumZSpin.setSingleStep(0.0001)
        self.inputNumZSpin.setObjectName("inputNumZSpin")
        self.inputNumZHLO.addWidget(self.inputNumZSpin)
        self.inputNumZHSlider = QtWidgets.QSlider(self.NumericEdit)
        self.inputNumZHSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputNumZHSlider.setMinimum(-10000)
        self.inputNumZHSlider.setMaximum(10000)
        self.inputNumZHSlider.setOrientation(QtCore.Qt.Horizontal)
        self.inputNumZHSlider.setObjectName("inputNumZHSlider")
        self.inputNumZHLO.addWidget(self.inputNumZHSlider)
        self.inputNumVLO.addLayout(self.inputNumZHLO)
        self.inputNumAbsBtn = QtWidgets.QPushButton(self.NumericEdit)
        self.inputNumAbsBtn.setStyleSheet("#inputNumAbsBtn{background-color:#b38080;color:#000;}")
        self.inputNumAbsBtn.setObjectName("inputNumAbsBtn")
        self.inputNumVLO.addWidget(self.inputNumAbsBtn)
        self.inputNumRelBtn = QtWidgets.QPushButton(self.NumericEdit)
        self.inputNumRelBtn.setStyleSheet("#inputNumRelBtn{background-color:#b38080;color:#000;}")
        self.inputNumRelBtn.setObjectName("inputNumRelBtn")
        self.inputNumVLO.addWidget(self.inputNumRelBtn)
        self.gridLayout_11.addLayout(self.inputNumVLO, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.NumericEdit, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)
        GallopNormalEditorWin.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(GallopNormalEditorWin)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 496, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        GallopNormalEditorWin.setMenuBar(self.menuBar)
        self.openManual = QtWidgets.QAction(GallopNormalEditorWin)
        self.openManual.setObjectName("openManual")
        self.menuOptions.addAction(self.openManual)
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(GallopNormalEditorWin)
        QtCore.QMetaObject.connectSlotsByName(GallopNormalEditorWin)

    def retranslateUi(self, GallopNormalEditorWin):
        GallopNormalEditorWin.setWindowTitle(QtWidgets.QApplication.translate("GallopNormalEditorWin", "GallopNormalEditor", None, -1))
        self.setNormWithSelectEdgeBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "選択エッジから法線を指定", None, -1))
        self.setNormWithSelectEdgeCB.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "選択エッジ両端の法線を変更しない", None, -1))
        self.slideNormSliderLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "加算値", None, -1))
        self.slideNormHGrpLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "水平方向", None, -1))
        self.slideNormHGrpDec.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "-", None, -1))
        self.slideNormHGrpAdd.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "+", None, -1))
        self.slideNormVGrpLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "垂直方向", None, -1))
        self.slideNormVGrpDec.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "-", None, -1))
        self.slideNormVGrpAdd.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "+", None, -1))
        self.normSmothGrpBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線スムース", None, -1))
        self.normSPBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "選択エッジ・頂点の法線を面にそわせる\n"
"(選択クリックでそわせる面を切り替え)", None, -1))
        self.normSPCheck.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "選択エッジ両端の法線を変更しない", None, -1))
        self.AdjustVtxNormalGrpBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線の特殊調整", None, -1))
        self.normBlendGrpBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線ブレンド", None, -1))
        self.basicNormToolGrpBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "基本法線ツール", None, -1))
        self.normCopyGrpBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線コピー", None, -1))
        self.setNormWithSelectEdgeGrpBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "選択エッジから法線を設定", None, -1))
        self.normCopyBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線をコピー", None, -1))
        self.normCopySetingOnlyLock.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ロックしている法線のみペースト", None, -1))
        self.normCopySetingkeepOrgEdge.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "転送先のエッジ状態を維持", None, -1))
        self.pasteWithSelectionBtn.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "頂点を選択した順番でペーストします。\n"
"複数の頂点で実行する場合はShiftを押しながら頂点を一個ずつ選択しコピー、Shiftを押しながら一個ずつ選択しペーストする必要があります。", None, -1))
        self.pasteWithSelectionBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "選択順でペースト", None, -1))
        self.pasteWithIndexBtn.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "コピーしたものとインデックスが同じものだけペーストします。\n"
"頂点インデックスはDisplay > Polygon > Component IDs > Vertices で表示できます。", None, -1))
        self.pasteWithIndexBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "頂点インデックスでペースト", None, -1))
        self.pasteWithPositionBtn.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "コピー元と位置が一番近い頂点の法線をペーストします。", None, -1))
        self.pasteWithPositionBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "頂点位置でペースト", None, -1))
        self.pasteSpaceBox.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ワールド空間での頂点座標か、メッシュごとのローカル頂点座標か", None, -1))
        self.pasteSpaceBox.setTitle(QtWidgets.QApplication.translate("GallopNormalEditorWin", "頂点位置でペースト： 座標空間", None, -1))
        self.pasteByWorldRadio.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "頂点位置をワールド空間の座標で比べてペーストします（モデルが重なっている時に使用）", None, -1))
        self.pasteByWorldRadio.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "World Space", None, -1))
        self.pasteByLocalRadio.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "頂点位置をメッシュのローカル空間の座標で比べてペーストします（モデルを並べた状態で使用）", None, -1))
        self.pasteByLocalRadio.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "Local Space", None, -1))
        self.mirrorOptionBox.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "コピーした頂点のミラーした位置に近い頂点にコピーした頂点の法線をペーストします。\n"
"法線自体はミラーしません。", None, -1))
        self.mirrorOptionBox.setTitle(QtWidgets.QApplication.translate("GallopNormalEditorWin", "頂点位置でペースト： ミラーした位置の頂点に対してペースト", None, -1))
        self.normCopyMirrorRadioNoMirror.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ミラーなし", None, -1))
        self.normCopyMirrorRadioXMirror.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "Xミラー", None, -1))
        self.normCopyMirrorRadioYMirror.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "Yミラー", None, -1))
        self.normCopyMirrorRadioZMirror.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "Zミラー", None, -1))
        self.normCopyMirrorNormal.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "頂点法線自体のミラーを行う", None, -1))
        self.showNormalLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線表示", None, -1))
        self.showNormalHideBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "非表示", None, -1))
        self.showNormalVtxBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "頂点表示", None, -1))
        self.showNormalFaceBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "フェース表示", None, -1))
        self.showNormalBothBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "両表示", None, -1))
        self.normalSizeLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線サイズ", None, -1))
        self.normalSizeDownBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ダウン", None, -1))
        self.normalSizeUpBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "アップ", None, -1))
        self.normalLockLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線ロック", None, -1))
        self.normalLockLockBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ロック", None, -1))
        self.normalLockUnlockBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "解除", None, -1))
        self.EdgeLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "エッジ", None, -1))
        self.EdgeHardBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ハード", None, -1))
        self.edgeSoftBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ソフト", None, -1))
        self.showEdgeLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "エッジを表示", None, -1))
        self.showEdgeBasicBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "基本", None, -1))
        self.showEdgeHardAndSoftBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ハードとソフト", None, -1))
        self.showEdgeColoredHardBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "色付きハード", None, -1))
        self.showEdgeOnlyHardBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ハードのみ", None, -1))
        self.normToolLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線ツール", None, -1))
        self.normToolActBtn.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "Menu Display > Vertex Normal Edit Tool と同じ", None, -1))
        self.normToolActBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "起動", None, -1))
        self.normToolDisableBtn.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "Move Tool に切り替えます", None, -1))
        self.normToolDisableBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "解除", None, -1))
        self.normToolActBtn2.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "マウスドラッグで法線を動かします", None, -1))
        self.normToolActBtn2.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ドラッグ起動", None, -1))
        self.normToolDisableBtn2.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "選択ツールに切り替え法線の表示を元に戻します", None, -1))
        self.normToolDisableBtn2.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ドラッグ解除", None, -1))
        self.inputNumGrpBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "数値入力", None, -1))
        self.normBlendSliderLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "元の法線とのブレンド値", None, -1))
        self.normBlendEdgBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "選択エッジの頂点法線を端の頂点法線でブレンド", None, -1))
        self.normSmothGrpBlendSldLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "元の法線とのブレンド値", None, -1))
        self.normSmothGrpBlendSldSpin.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "周辺の法線の平均値を選択中のコンポーネントの法線にブレンドする割合", None, -1))
        self.normSmothGrpRangeSldLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ブレンド法線の検索範囲", None, -1))
        self.normSmothGrpRangeSldSpin.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "平均値を取る範囲", None, -1))
        self.checkSmothGrpRangeChk.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "どの範囲の平均値が反映されるのか目視で確認してから実行できます", None, -1))
        self.checkSmothGrpRangeChk.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "範囲を確認", None, -1))
        self.normSmothFaceAvgBtn.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "周辺のフェイス法線の平均値を選択中のコンポーネントの法線にブレンド", None, -1))
        self.normSmothFaceAvgBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線をスムース\n"
"フェイス法線の平均とブレンド", None, -1))
        self.applyOnlyLockedVertexFaceNormalChk1.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ロックされた法線（黄色）だけスムースしたい場合にチェック\n"
"選択されていてもロックされていなければ実行しない。", None, -1))
        self.applyOnlyLockedVertexFaceNormalChk1.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ロック法線のみ", None, -1))
        self.normSmothVtxAvgBtn.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "周辺の頂点法線の平均値を選択中のコンポーネントの法線にブレンド", None, -1))
        self.normSmothVtxAvgBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線をスムース\n"
"頂点法線の平均とブレンド", None, -1))
        self.applyOnlyLockedVertexFaceNormalChk2.setToolTip(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ロックされた法線（黄色）だけスムースしたい場合にチェック\n"
"選択されていてもロックされていなければ実行しない。", None, -1))
        self.applyOnlyLockedVertexFaceNormalChk2.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "ロック法線のみ", None, -1))
        self.slideNormGrpBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "法線ずらし", None, -1))
        self.inputNumXLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "X方向", None, -1))
        self.inputNumYLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "Y方向", None, -1))
        self.inputNumZLbl.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "Z方向", None, -1))
        self.inputNumAbsBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "絶対値で指定", None, -1))
        self.inputNumRelBtn.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "加算で設定", None, -1))
        self.menuOptions.setTitle(QtWidgets.QApplication.translate("GallopNormalEditorWin", "Options", None, -1))
        self.openManual.setText(QtWidgets.QApplication.translate("GallopNormalEditorWin", "マニュアルを開く", None, -1))

