# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tech-designer\Maya\scripts\Project_Gallop\glp_place_obj_at_equal_itervels\ui\glp_place_obj_at_equal_itervals_window.ui'
#
# Created: Mon Nov  8 17:29:41 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 528)
        MainWindow.setMinimumSize(QtCore.QSize(600, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.place_target_mesh_list_widget = QtWidgets.QListWidget(self.groupBox)
        self.place_target_mesh_list_widget.setObjectName("place_target_mesh_list_widget")
        self.verticalLayout_2.addWidget(self.place_target_mesh_list_widget)
        self.add_place_target_mesh_list_button = QtWidgets.QPushButton(self.groupBox)
        self.add_place_target_mesh_list_button.setObjectName("add_place_target_mesh_list_button")
        self.verticalLayout_2.addWidget(self.add_place_target_mesh_list_button)
        self.remove_place_target_mesh_list_button = QtWidgets.QPushButton(self.groupBox)
        self.remove_place_target_mesh_list_button.setObjectName("remove_place_target_mesh_list_button")
        self.verticalLayout_2.addWidget(self.remove_place_target_mesh_list_button)
        self.verticalLayout.addWidget(self.groupBox)
        self.place_target_object_check_box = QtWidgets.QGroupBox(self.centralwidget)
        self.place_target_object_check_box.setCheckable(True)
        self.place_target_object_check_box.setChecked(False)
        self.place_target_object_check_box.setObjectName("place_target_object_check_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.place_target_object_check_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.place_target_object_check_box)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.place_target_object_line = QtWidgets.QLineEdit(self.place_target_object_check_box)
        self.place_target_object_line.setObjectName("place_target_object_line")
        self.horizontalLayout_3.addWidget(self.place_target_object_line)
        self.set_place_target_object_button = QtWidgets.QPushButton(self.place_target_object_check_box)
        self.set_place_target_object_button.setObjectName("set_place_target_object_button")
        self.horizontalLayout_3.addWidget(self.set_place_target_object_button)
        self.clear_place_target_object_button = QtWidgets.QPushButton(self.place_target_object_check_box)
        self.clear_place_target_object_button.setMinimumSize(QtCore.QSize(1, 0))
        self.clear_place_target_object_button.setObjectName("clear_place_target_object_button")
        self.horizontalLayout_3.addWidget(self.clear_place_target_object_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.not_export_json_check_box = QtWidgets.QCheckBox(self.place_target_object_check_box)
        self.not_export_json_check_box.setObjectName("not_export_json_check_box")
        self.verticalLayout_4.addWidget(self.not_export_json_check_box)
        self.verticalLayout.addWidget(self.place_target_object_check_box)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.place_iterverls_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.place_iterverls_spinbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.place_iterverls_spinbox.setMaximum(1000000)
        self.place_iterverls_spinbox.setProperty("value", 300)
        self.place_iterverls_spinbox.setObjectName("place_iterverls_spinbox")
        self.horizontalLayout.addWidget(self.place_iterverls_spinbox)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.search_distance_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.search_distance_spinbox.setMinimum(0)
        self.search_distance_spinbox.setMaximum(1000000)
        self.search_distance_spinbox.setProperty("value", 10000)
        self.search_distance_spinbox.setObjectName("search_distance_spinbox")
        self.horizontalLayout_2.addWidget(self.search_distance_spinbox)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.add_quaternion_info_check_box = QtWidgets.QCheckBox(self.groupBox_2)
        self.add_quaternion_info_check_box.setObjectName("add_quaternion_info_check_box")
        self.verticalLayout_3.addWidget(self.add_quaternion_info_check_box)
        self.add_random_id_info_check_box = QtWidgets.QGroupBox(self.groupBox_2)
        self.add_random_id_info_check_box.setCheckable(True)
        self.add_random_id_info_check_box.setChecked(False)
        self.add_random_id_info_check_box.setObjectName("add_random_id_info_check_box")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.add_random_id_info_check_box)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.add_random_id_info_check_box)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.random_id_range_spinbox = QtWidgets.QSpinBox(self.add_random_id_info_check_box)
        self.random_id_range_spinbox.setMaximum(100)
        self.random_id_range_spinbox.setObjectName("random_id_range_spinbox")
        self.horizontalLayout_4.addWidget(self.random_id_range_spinbox)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_3.addWidget(self.add_random_id_info_check_box)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.exec_command_button = QtWidgets.QPushButton(self.centralwidget)
        self.exec_command_button.setObjectName("exec_command_button")
        self.verticalLayout.addWidget(self.exec_command_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "メッシュにオブジェクトを等間隔に配置するツール(placeObjAtEqualItervals)", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "配置対象メッシュリスト", None, -1))
        self.add_place_target_mesh_list_button.setText(QtWidgets.QApplication.translate("MainWindow", "シーン上で選択しているオブジェクトを配置対象リストに追加", None, -1))
        self.remove_place_target_mesh_list_button.setText(QtWidgets.QApplication.translate("MainWindow", "リスト上で選択しているオブジェクトを配置対象リストから削除", None, -1))
        self.place_target_object_check_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "オブジェクトを配置する", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "複製元オブジェクト", None, -1))
        self.set_place_target_object_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択したオブジェクトを設定", None, -1))
        self.clear_place_target_object_button.setText(QtWidgets.QApplication.translate("MainWindow", "クリア", None, -1))
        self.not_export_json_check_box.setText(QtWidgets.QApplication.translate("MainWindow", "配置のみを行い、配置情報(json)を出力しない", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "オプション", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "配置間隔(cm)", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "探索距離(cm)", None, -1))
        self.add_quaternion_info_check_box.setText(QtWidgets.QApplication.translate("MainWindow", "配置場所に一番近いポリゴンの面法線のquaternion情報を付与", None, -1))
        self.add_random_id_info_check_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "ランダムID情報を付与", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "付与するIDのランダム幅", None, -1))
        self.exec_command_button.setText(QtWidgets.QApplication.translate("MainWindow", "ツール実行", None, -1))

