# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\maya_legacy\scripts\Project_Gallop\glp_bg_exporter\main_window.ui'
#
# Created: Thu Jul 20 18:53:00 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setContentsMargins(10, 2, 10, 10)
        self.mainLayout.setObjectName("mainLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(14)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileTypeComboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTypeComboBox.sizePolicy().hasHeightForWidth())
        self.fileTypeComboBox.setSizePolicy(sizePolicy)
        self.fileTypeComboBox.setMinimumSize(QtCore.QSize(125, 20))
        self.fileTypeComboBox.setMaximumSize(QtCore.QSize(125, 20))
        self.fileTypeComboBox.setObjectName("fileTypeComboBox")
        self.horizontalLayout_2.addWidget(self.fileTypeComboBox)
        self.makeDirCheckBox = QtWidgets.QCheckBox(self.widget)
        self.makeDirCheckBox.setObjectName("makeDirCheckBox")
        self.horizontalLayout_2.addWidget(self.makeDirCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.helpButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButton.sizePolicy().hasHeightForWidth())
        self.helpButton.setSizePolicy(sizePolicy)
        self.helpButton.setMinimumSize(QtCore.QSize(40, 20))
        self.helpButton.setMaximumSize(QtCore.QSize(40, 20))
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout_2.addWidget(self.helpButton)
        self.mainLayout.addWidget(self.widget)
        self.nodeListFrame = QtWidgets.QFrame(self.centralwidget)
        self.nodeListFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.nodeListFrame.setObjectName("nodeListFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.nodeListFrame)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.nodeListFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.refreshNodeListButton = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshNodeListButton.sizePolicy().hasHeightForWidth())
        self.refreshNodeListButton.setSizePolicy(sizePolicy)
        self.refreshNodeListButton.setMinimumSize(QtCore.QSize(120, 20))
        self.refreshNodeListButton.setMaximumSize(QtCore.QSize(120, 20))
        self.refreshNodeListButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(153, 153, 153);")
        self.refreshNodeListButton.setObjectName("refreshNodeListButton")
        self.horizontalLayout_5.addWidget(self.refreshNodeListButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.selectAllNodeButton = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectAllNodeButton.sizePolicy().hasHeightForWidth())
        self.selectAllNodeButton.setSizePolicy(sizePolicy)
        self.selectAllNodeButton.setMinimumSize(QtCore.QSize(120, 20))
        self.selectAllNodeButton.setMaximumSize(QtCore.QSize(120, 20))
        self.selectAllNodeButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(153, 153, 153);")
        self.selectAllNodeButton.setObjectName("selectAllNodeButton")
        self.horizontalLayout_5.addWidget(self.selectAllNodeButton)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.nodeListScrollArea = QtWidgets.QScrollArea(self.nodeListFrame)
        self.nodeListScrollArea.setStyleSheet("background-color: rgb(89, 89, 89);")
        self.nodeListScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nodeListScrollArea.setWidgetResizable(True)
        self.nodeListScrollArea.setObjectName("nodeListScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 566, 236))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.nodeListLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.nodeListLayout.setSpacing(0)
        self.nodeListLayout.setContentsMargins(0, 0, 0, 0)
        self.nodeListLayout.setObjectName("nodeListLayout")
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.nodeListLayout.addItem(spacerItem2)
        self.nodeListScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.nodeListScrollArea)
        self.mainLayout.addWidget(self.nodeListFrame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.mainLayout.addItem(spacerItem3)
        self.singleExportFrameLabel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleExportFrameLabel.sizePolicy().hasHeightForWidth())
        self.singleExportFrameLabel.setSizePolicy(sizePolicy)
        self.singleExportFrameLabel.setStyleSheet(".QFrame\n"
"{\n"
"    background-color: rgb(51, 77, 102);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 2px;\n"
"    border-color: rgb(34, 34, 34);\n"
"}")
        self.singleExportFrameLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.singleExportFrameLabel.setObjectName("singleExportFrameLabel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.singleExportFrameLabel)
        self.verticalLayout_2.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.singleExportFrameLabel)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.mainLayout.addWidget(self.singleExportFrameLabel)
        self.singleExportFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleExportFrame.sizePolicy().hasHeightForWidth())
        self.singleExportFrame.setSizePolicy(sizePolicy)
        self.singleExportFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.singleExportFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.singleExportFrame.setObjectName("singleExportFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.singleExportFrame)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.singleExportFrame)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setContentsMargins(3, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.folderPathLineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.folderPathLineEdit.setStyleSheet("QLineEdit {\n"
"    margin-left: 4px;\n"
"    margin-right: 4px;\n"
"    padding-left: 2px;\n"
"}\n"
"QLineEdit[dirExists=\"true\"] {\n"
"    background-color: rgb(42, 42, 42);\n"
"}\n"
"QLineEdit[dirExists=\"false\"] {\n"
"    background-color: rgb(51, 31, 31);\n"
"}\n"
"QLineEdit[dirExists=\"false\"][canMakeDir=\"true\"] {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(153, 153, 0);\n"
"}\n"
"")
        self.folderPathLineEdit.setObjectName("folderPathLineEdit")
        self.horizontalLayout_3.addWidget(self.folderPathLineEdit)
        self.selectFolderButton = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFolderButton.sizePolicy().hasHeightForWidth())
        self.selectFolderButton.setSizePolicy(sizePolicy)
        self.selectFolderButton.setMinimumSize(QtCore.QSize(35, 20))
        self.selectFolderButton.setMaximumSize(QtCore.QSize(35, 20))
        self.selectFolderButton.setObjectName("selectFolderButton")
        self.horizontalLayout_3.addWidget(self.selectFolderButton)
        self.openExplorerButton = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openExplorerButton.sizePolicy().hasHeightForWidth())
        self.openExplorerButton.setSizePolicy(sizePolicy)
        self.openExplorerButton.setMinimumSize(QtCore.QSize(60, 20))
        self.openExplorerButton.setMaximumSize(QtCore.QSize(60, 20))
        self.openExplorerButton.setObjectName("openExplorerButton")
        self.horizontalLayout_3.addWidget(self.openExplorerButton)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.singleExportFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.singleExportButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleExportButton.sizePolicy().hasHeightForWidth())
        self.singleExportButton.setSizePolicy(sizePolicy)
        self.singleExportButton.setMinimumSize(QtCore.QSize(95, 0))
        self.singleExportButton.setMaximumSize(QtCore.QSize(95, 16777215))
        self.singleExportButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(128, 153, 179);")
        self.singleExportButton.setObjectName("singleExportButton")
        self.horizontalLayout.addWidget(self.singleExportButton)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.mainLayout.addWidget(self.singleExportFrame)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.mainLayout.addItem(spacerItem5)
        self.multiExportFrameLabel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiExportFrameLabel.sizePolicy().hasHeightForWidth())
        self.multiExportFrameLabel.setSizePolicy(sizePolicy)
        self.multiExportFrameLabel.setStyleSheet(".QFrame\n"
"{\n"
"    background-color: rgb(51, 102, 77);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 2px;\n"
"    border-color: rgb(34, 34, 34);\n"
"}")
        self.multiExportFrameLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.multiExportFrameLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.multiExportFrameLabel.setObjectName("multiExportFrameLabel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.multiExportFrameLabel)
        self.verticalLayout.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.multiExportFrameLabel)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.mainLayout.addWidget(self.multiExportFrameLabel)
        self.multiExportFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiExportFrame.sizePolicy().hasHeightForWidth())
        self.multiExportFrame.setSizePolicy(sizePolicy)
        self.multiExportFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.multiExportFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.multiExportFrame.setObjectName("multiExportFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.multiExportFrame)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.multiExportFrame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.multiDstComboBox = QtWidgets.QComboBox(self.multiExportFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiDstComboBox.sizePolicy().hasHeightForWidth())
        self.multiDstComboBox.setSizePolicy(sizePolicy)
        self.multiDstComboBox.setMinimumSize(QtCore.QSize(170, 0))
        self.multiDstComboBox.setMaximumSize(QtCore.QSize(170, 16777215))
        self.multiDstComboBox.setObjectName("multiDstComboBox")
        self.multiDstComboBox.addItem("")
        self.multiDstComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.multiDstComboBox)
        spacerItem6 = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.multiExportButton = QtWidgets.QPushButton(self.multiExportFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiExportButton.sizePolicy().hasHeightForWidth())
        self.multiExportButton.setSizePolicy(sizePolicy)
        self.multiExportButton.setMinimumSize(QtCore.QSize(95, 0))
        self.multiExportButton.setMaximumSize(QtCore.QSize(95, 16777215))
        self.multiExportButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(128, 179, 153);")
        self.multiExportButton.setObjectName("multiExportButton")
        self.horizontalLayout_4.addWidget(self.multiExportButton)
        self.mainLayout.addWidget(self.multiExportFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.makeDirCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "保存先フォルダが存在しない場合は自動作成する", None, -1))
        self.helpButton.setText(QtWidgets.QApplication.translate("MainWindow", "ヘルプ", None, -1))
        self.refreshNodeListButton.setText(QtWidgets.QApplication.translate("MainWindow", "↓ノードリストを更新", None, -1))
        self.selectAllNodeButton.setText(QtWidgets.QApplication.translate("MainWindow", "↓ノードを全て選択", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "A : 全てのノードを同一の保存先にエクスポートする場合", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "メインの保存先", None, -1))
        self.folderPathLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "保存先フォルダパス", None, -1))
        self.selectFolderButton.setText(QtWidgets.QApplication.translate("MainWindow", "参照", None, -1))
        self.openExplorerButton.setText(QtWidgets.QApplication.translate("MainWindow", "Explorer", None, -1))
        self.singleExportButton.setText(QtWidgets.QApplication.translate("MainWindow", "A : Exportを実行", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "B : ノードごとに保存先が異なる場合", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "個別の保存先が未指定の場合 ：", None, -1))
        self.multiDstComboBox.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "何もしない", None, -1))
        self.multiDstComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "何もしない", None, -1))
        self.multiDstComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "「 A : メインの保存先 」 に保存", None, -1))
        self.multiExportButton.setText(QtWidgets.QApplication.translate("MainWindow", "B : Exportを実行", None, -1))

