// Copyright (C) 1997-2020 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.
//
// Author:		Steven T. L. Roselle
//
// Created:        ( 04/01/15 )


global proc bt_toggleParallelEval()
{
	//Toggle GPU Accel mode for selected models for if nothing selected toggle for all panels	
	
	$evalMode = `evaluationManager -q -enabled`;
		
	if ($evalMode == 1)
		{
        evaluationManager -mode "off";
        SetEvaluationManagerHUDVisibility 1 ;
        inViewMessage -smg "Parellel evalution disabled.  Evaluation mode set to DG." -pos midCenter -bkc 0x11111111 -alpha .5 -fade -fst 3000;
        }
	else
		{
        evaluationManager -mode "parallel";
        SetEvaluationManagerHUDVisibility 1 ;
        inViewMessage -smg "Parellel evalution enabled." -pos midCenter -bkc 0x11111111 -alpha .5 -fade -fst 3000;
        }
}
