RecentLoadedPresetFile:
- P:/production/team/character_model/config/postproc_set_editor/preset_character.yaml
- P:/production/team/animation/config/postproc_set_editor/maya/preset_animation.yaml
- P:/production/team/environment/config/postproc_set_editor/maya/preset_environment.yaml