# -*- coding: utf-8 -*-

try:
    # Maya 2022-
    from builtins import range
except Exception:
    pass

__key_list = (
    ttl_bc_bakelayername,
    ttl_bc_bakelayername_override,
    ttl_bc_ao_sampler_name,
    ttl_bc_ao_sampler_name_override,
    ttl_bc_orthreflect,
    ttl_bc_orthreflect_override,
    ttl_bc_bakeshadows,
    ttl_bc_bakeshadows_override,
    ttl_bc_bgcolor,
    ttl_bc_bgcolor_override,
    ttl_bc_ao_mincolor,
    ttl_bc_ao_mincolor_override,
    ttl_bc_ao_maxcolor,
    ttl_bc_ao_maxcolor_override,
    ttl_bc_ao_maxdistance,
    ttl_bc_ao_maxdistance_override,
    ttl_bc_ao_contrast,
    ttl_bc_ao_contrast_override,
    ttl_bc_ao_scale,
    ttl_bc_ao_scale_override,
    ttl_bc_ao_accuracy,
    ttl_bc_ao_accuracy_override,
    ttl_bc_ao_smooth,
    ttl_bc_ao_smooth_override,
    ttl_bv_samplemode,
    ttl_bv_samplemode_override,
    ttl_bv_minsample,
    ttl_bv_minsample_override,
    ttl_bv_maxsample,
    ttl_bv_maxsample_override,
    ttl_bv_vtxbias,
    ttl_bv_vtxbias_override,
    ttl_bv_rgbscale,
    ttl_bv_rgbscale_override,
    ttl_bv_clamp,
    ttl_bv_clamp_override,
    ttl_bv_rgbmin,
    ttl_bv_rgbmin_override,
    ttl_bv_rgbmax,
    ttl_bv_rgbmax_override,
    ttl_bv_enablefilter,
    ttl_bv_enablefilter_override,
    ttl_bv_filtersize,
    ttl_bv_filtersize_override,
    ttl_bv_filtershape,
    ttl_bv_filtershape_override,
    ttl_bv_filterdeviation,
    ttl_bv_filterdeviation_override,
    ttl_bt_width,
    ttl_bt_width_override,
    ttl_bt_height,
    ttl_bt_height_override,
    ttl_bt_bilinear,
    ttl_bt_bilinear_override,
    ttl_bt_edgedilation,
    ttl_bt_edgedilation_override,
    com_bt_lightmapuv,
    com_bt_lightmapuv_override,
    com_bt_customlightmapuv,
    com_bt_customlightmapuv_override,
    com_bt_unwrapuvmel,
    com_bt_unwrapuvmel_override,
    com_bt_layoutuvmel,
    com_bt_layoutuvmel_override,
    com_bt_texouptputpath,
    com_bt_texouptputpath_override,
    com_bt_width,
    com_bt_width_override,
    com_bt_height,
    com_bt_height_override,
    com_bt_testwidth,
    com_bt_testwidth_override,
    com_bt_testheight,
    com_bt_testheight_override,
    com_bt_materialsuffix,
    com_bt_materialsuffix_override,
    com_bt_settingmaterialsuffix,
    com_bt_settingmaterialsuffix_override,
    com_bt_groupmaterialsuffix,
    com_bt_groupmaterialsuffix_override,
    com_bt_textureprefix,
    com_bt_textureprefix_override,
    com_bt_settingtexturesuffix,
    com_bt_settingtexturesuffix_override,
    com_bt_grouptexturesuffix,
    com_bt_grouptexturesuffix_override,
    com_bc_colorsetprefix,
    com_bc_colorsetprefix_override,
    com_bc_settingcolorsetsuffix,
    com_bc_settingcolorsetsuffix_override,
    com_bc_groupcolorsetsuffix,
    com_bc_groupcolorsetsuffix_override,
    com_bc_common_colorset_multi,
    com_bc_common_colorset_multi_override,
    com_bc_common_colorset_add,
    com_bc_common_colorset_add_override,
    com_bc_common_colorset_overlay,
    com_bc_common_colorset_overlay_override,
    com_bc_common_colorset_alpha,
    com_bc_common_colorset_alpha_override,
    com_bc_common_colorset_gray,
    com_bc_common_colorset_gray_override,
    com_bc_export_object_dir_path,
    com_bc_export_object_dir_path_override,
    com_bc_export_texture_dir_path,
    com_bc_export_texture_dir_path_override,
    com_bc_light_enable,
    com_bc_light_enable_override,
    com_bc_light_alpha,
    com_bc_light_alpha_override,
    com_bc_light_color_multi,
    com_bc_light_color_multi_override,
    com_bc_light_color_offset,
    com_bc_light_color_offset_override,
    com_bc_ao_enable,
    com_bc_ao_enable_override,
    com_bc_ao_alpha,
    com_bc_ao_alpha_override,
    com_bc_ao_color_multi,
    com_bc_ao_color_multi_override,
    com_bc_ao_color_offset,
    com_bc_ao_color_offset_override,
    com_bc_indirect_enable,
    com_bc_indirect_enable_override,
    com_bc_indirect_alpha,
    com_bc_indirect_alpha_override,
    com_bc_indirect_color_multi,
    com_bc_indirect_color_multi_override,
    com_bc_indirect_color_offset,
    com_bc_indirect_color_offset_override,
) = list(range(0, 130))

__unwrap_uv_mel = \
    "polyAutoProjection -lm 1 -pb 0 -ibd 0 -cm 0 -l 2 -sc 1 -o 0 -p 6 -ps 0.25 -ws 0"
__layout_uv_mel = \
    "polyMultiLayoutUV -l 2 -rbf 1 -sc 1 -lm 1 -psc 2 -fr 1 -ps 0.4"

__value_list = (
    ("TurtleBcBakeLayerName", "string", "lmmTurtleBakeLayer00",
     "Turtle Bake Layer Name", None),
    ("TurtleBcBakeLayerNameOverride", "bool", False,
     "----", None),
    ("TurtleBcAoSamplerName", "string", "lmmTurtleAoSampler00",
     "Turtle AO Sampler Name", None),
    ("TurtleBcAoSamplerNameOverride", "bool",
     False, "----", None),
    ("TurtleBcOrthReflect", "bool", True,
     "Orthogonal Reflections", None),
    ("TurtleBcOrthReflectOverride", "bool", False,
     "----", None),
    ("TurtleBcBakeShadows", "bool", True,
     "Bake Shadows", None),
    ("TurtleBcBakeShadowsOverride", "bool", False,
     "----", None),
    ("TurtleBcBgColor", "color", (0.5, 0.5, 0.5),
     "Background Color", None),
    ("TurtleBcBgColorOverride", "bool", False,
     "----", None),

    ("TurtleBcAoMinColor", "color", (0, 0, 0), "AO Min Color", None),
    ("TurtleBcAoMinColorOverride", "bool", False, "----", None),
    ("TurtleBcAoMaxColor", "color", (1, 1, 1), "AO Max Color", None),
    ("TurtleBcAoMaxColorOverride", "bool", False, "----", None),
    ("TurtleBcAoMaxDistance", "float", 0, "AO Max Distance", ("slider", 0, 10, 0, 100)),
    ("TurtleBcAoMaxDistanceOverride", "bool", False, "----", None),
    ("TurtleBcAoContrast", "float", 1, "AO Contrast", ("slider", 0, 10, 0, 10)),
    ("TurtleBcAoContrastOverride", "bool", False, "----", None),
    ("TurtleBcAoScale", "float", 1, "AO Scale", ("slider", 0, 10, 0, 10)),
    ("TurtleBcAoScaleOverride", "bool", False, "----", None),
    ("TurtleBcAoAccuracy", "float", 1, "AO Accuracy", ("slider", 0, 10, 0, 10)),
    ("TurtleBcAoAccuracyOverride", "bool", False, "----", None),
    ("TurtleBcAoSmooth", "float", 1, "AO Smooth", ("slider", 0, 10, 0, 10)),
    ("TurtleBcAoSmoothOverride", "bool", False, "----", None),

    ("TurtleBvSampleMode", "list", "Triangle Subdiv",
     "Sample Mode", ("radio", ("Per Vertex", "Triangle Subdiv"))),
    ("TurtleBvSampleModeOverride", "bool", False,
     "----", None),
    ("TurtleBvMinSample", "int", 2,
     "Min Sample", ("slider", 1, 32, 1, 256)),
    ("TurtleBvMinSampleOverride", "bool", False,
     "----", None),
    ("TurtleBvMaxSample", "int", 16,
     "Max Sample", ("slider", 1, 32, 1, 256)),
    ("TurtleBvMaxSampleOverride", "bool", False,
     "----", None),
    ("TurtleBvVtxBias", "float", 0.01,
     "Vertex Bias", ("slider", 0.01, 1, 0.01, 1)),
    ("TurtleBvVtxBiasOverride", "bool", False,
     "----", None),
    ("TurtleBvRgbScale", "float", 1,
     "RGB Scale", ("slider", 0, 2, -100000, 100000)),
    ("TurtleBvRgbScaleOverride", "bool", False,
     "----", None),
    ("TurtleBvClamp", "bool", True,
     "Clamp", None),
    ("TurtleBvClampOverride", "bool", False,
     "----", None),
    ("TurtleBvRgbMin", "color", (0, 0, 0),
     "RGB Min", None),
    ("TurtleBvRgbMinOverride", "bool", False,
     "----", None),
    ("TurtleBvRgbMax", "color", (1, 1, 1),
     "RGB Max", None),
    ("TurtleBvRgbMaxOverride", "bool", False,
     "----", None),
    ("TurtleBvEnableFilter", "bool", True,
     "Enable Vertex Color Filter", None),
    ("TurtleBvEnableFilterOverride", "bool",
     False, "----", None),
    ("TurtleBvFilterSize", "float", 0.05,
     "Filter Size", ("slider", 0, 1, 0, 1)),
    ("TurtleBvFilterSizeOverride", "bool", False,
     "----", None),
    ("TurtleBvFilterShape", "float", 1.1,
     "Filter Shape", ("slider", 1, 2, 1, 100000)),
    ("TurtleBvFilterShapeOverride", "bool", False,
     "----", None),
    ("TurtleBvFilterDiviation", "float", 6,
     "Filter Normal Diviation", ("slider", 0, 90, 0, 180)),
    ("TurtleBvFilterDiviationOverride", "bool", False,
     "----", None),
    ("TurtleBtWidth", "int", 2048,
     "Width", ("slider", 1, 4096, 1, 100000)),
    ("TurtleBtWidthOverride", "bool", False,
     "----", None),
    ("TurtleBtHeight", "int", 2048,
     "Height", ("slider", 1, 4096, 1, 100000)),
    ("TurtleBtHeightOverride", "bool", False,
     "----", None),
    ("TurtleBtBilinear", "bool", False,
     "Bilinear Filter", None),
    ("TurtleBtBilinearOverride", "bool", False,
     "----", None),
    ("TurtleBtEdgeDilation", "int", 16,
     "Edge Dilation", ("slider", 0, 50, 0, 100000)),
    ("TurtleBtEdgeDilationOverride", "bool", False,
     "----", None),
    ("CommonBtBakeLightmapUVName", "string", "lmm_lightmap",
     "Bake Lightmap UV Name", None),
    ("CommonBtBakeLightmapUVNameOverride", "bool", False,
     "----", None),
    ("CommonBtCustomLightmapUVName", "string", "lightmap",
     "Custom Lightmap UV Name", None),
    ("CommonBtCustomLightmapUVNameOverride", "bool", False,
     "----", None),
    ("CommonBtUnwrapUVMel", "string", __unwrap_uv_mel,
     "UnWrap UV Mel", None),
    ("CommonBtUnwrapUVMelOverride", "bool", False,
     "----", None),
    ("CommonBtLayoutUVMel", "string", __layout_uv_mel,
     "Layout UV Mel", None),
    ("CommonBtLayoutUVMelOverride", "bool", False,
     "----", None),
    ("CommonBtTextureOutputPath", "string", "sourceimages/bake",
     "Output Folder Path", None),
    ("CommonBtTextureOutputPathOverride", "bool", False,
     "----", None),
    ("CommonBtWidth", "int", 2048,
     "Width", ("slider", 1, 4096, 1, 100000)),
    ("CommonBtWidthOverride", "bool", False,
     "----", None),
    ("CommonBtHeight", "int", 2048,
     "Height", ("slider", 1, 4096, 1, 100000)),
    ("CommonBtHeightOverride", "bool", False,
     "----", None),
    ("CommonBtTestWidth", "int", 256,
     "Test Width", ("slider", 1, 4096, 1, 100000)),
    ("CommonBtTestWidthOverride", "bool", False,
     "----", None),
    ("CommonBtTestHeight", "int", 256,
     "Test Height", ("slider", 1, 4096, 1, 100000)),
    ("CommonBtTestHeightOverride", "bool", False,
     "----", None),
    ("CommonBtMaterialSuffix", "string", "_bake",
     "Material Suffix", None),
    ("CommonBtMaterialSuffixOverride", "bool", False,
     "----", None),
    ("CommonBtSettingMaterialSuffix", "string", "****",
     "Setting Material Suffix", None),
    ("CommonBtSettingMaterialSuffixOverride", "bool", False,
     "----", None),
    ("CommonBtGroupMaterialSuffix", "string", "****",
     "Group Material Suffix", None),
    ("CommonBtGroupMaterialSuffixOverride", "bool", False,
     "----", None),
    ("CommonBtTexturePrefix", "string", "tex_bake",
     "Texture Prefix", None),
    ("CommonBtTexturePrefixOverride", "bool", False,
     "----", None),
    ("CommonBtSettingTextureSuffix", "string", "****",
     "Setting Texture Suffix", None),
    ("CommonBtSettingTextureSuffixOverride", "bool", False,
     "----", None),
    ("CommonBtGroupTextureSuffix", "string", "****",
     "Group Texture Suffix", None),
    ("CommonBtGroupTextureSuffixOverride", "bool", False,
     "----", None),
    ("CommonBcColorSetPrefix", "string", "lmm_colorset",
     "Color Set Prefix", None),
    ("CommonBcColorSetPrefixOverride", "bool", False,
     "----", None),
    ("CommonBcSettingColorSetSuffix", "string", "****",
     "Settting Color Set Suffix", None),
    ("CommonBcSettingColorSetSuffixOverride", "bool", False,
     "----", None),
    ("CommonBcBcGroupColorSetSuffix", "string", "****",
     "Group Color Set Suffix", None),
    ("CommonBcGroupColorSetSuffixOverride", "bool", False,
     "----", None),
    ("CommonBcCommonColorSetMulti", "string", "colorSet",
     "Common Color Set (Multi)", None),
    ("CommonBcCommonColorSetMultiOverride", "bool", False,
     "----", None),
    ("CommonBcCommonColorSetAdd", "string", "colorSetAdd",
     "Common Color Set (Add)", None),
    ("CommonBcCommonColorSetAddOverride", "bool", False,
     "----", None),
    ("CommonBcCommonColorSetOverlay", "string", "colorSetOverlay",
     "Common Color Set (Overlay)", None),
    ("CommonBcCommonColorSetOverlayOverride", "bool", False,
     "----", None),
    ("CommonBcCommonColorSetAlpha", "string", "colorSetAlpha",
     "Common Color Set (Alpha)", None),
    ("CommonBcCommonColorSetAlphaOverride", "bool", False,
     "----", None),
    ("CommonBcCommonColorSetGray", "string", "lmm_colorSetGray",
     "Common Color Set (Gray)", None),
    ("CommonBcCommonColorSetGrayOverride", "bool", False,
     "----", None),

    ("CommonBcExportObjectDirPath", "string", "fbx",
     "Export Object Folder Path", None),
    ("CommonBcExportObjectDirPathOverride", "bool", False,
     "----", None),
    ("CommonBcExportTextureDirPath", "string", "fbx/texture",
     "Export Texture Folder Path", None),
    ("CommonBcExportTextureDirPathOverride", "bool", False,
     "----", None),

    ("CommonBcLightEnable", "bool", True,
     "Light Enable", None),
    ("CommonBcLightEnableOverride", "bool", False,
     "----", None),
    ("CommonBcLightAlpha", "float", True,
     "Light Alpha", ("slider", 0, 1, 0, 1)),
    ("CommonBcLightAlphaOverride", "bool", False,
     "----", None),

    ("CommonBcLightColorMulti", "color", (1, 1, 1), "Light Color Multi", None),
    ("CommonBcLightColorMultiOverride", "bool", False, "----", None),
    ("CommonBcLightColorOffset", "color", (0, 0, 0), "Light Color Offset", None),
    ("CommonBcLightColorOffsetOverride", "bool", False, "----", None),

    ("CommonBcAoEnable", "bool", True, "AO Enable", None),
    ("CommonBcAoEnableOverride", "bool", False, "----", None),
    ("CommonBcAoAlpha", "float", True, "AO Alpha", ("slider", 0, 1, 0, 1)),
    ("CommonBcAoAlphaOverride", "bool", False, "----", None),

    ("CommonBcAoColorMulti", "color", (1, 1, 1), "AO Color Multi", None),
    ("CommonBcAoColorMultiOverride", "bool", False, "----", None),
    ("CommonBcAoColorOffset", "color", (0, 0, 0), "AO Color Offset", None),
    ("CommonBcAoColorOffsetOverride", "bool", False, "----", None),

    ("CommonBcIndirectEnable", "bool", True,
     "Indirect Enable", None),
    ("CommonBcIndirectEnableOverride", "bool", False,
     "----", None),
    ("CommonBcIndirectAlpha", "float", True,
     "Indirect Alpha", ("slider", 0, 1, 0, 1)),
    ("CommonBcIndirectAlphaOverride", "bool", False,
     "----", None),

    ("CommonBcIndirectColorMulti", "color",
     (1, 1, 1), "Indirect Color Multi", None),
    ("CommonBcIndirectColorMultiOverride", "bool", False, "----", None),
    ("CommonBcIndirectColorOffset", "color",
     (0, 0, 0), "Indirect Color Offset", None),
    ("CommonBcIndirectColorOffsetOverride", "bool", False, "----", None),
)


def get_name(key):

    return __value_list[key][0]


def get_type(key):

    return __value_list[key][1]


def get_value(key):

    return __value_list[key][2]


def get_ui_label(key):

    return __value_list[key][3]


def get_ui_type(key):

    return __value_list[key][4]
