# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\maya_legacy\scripts\Project_Farm\farm_chara_facial_tool\farm_chara_facial_tool.ui'
#
# Created: Thu Jul 29 18:04:20 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

try:
    # Maya 2022-
    from builtins import object
except:
    pass

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.order_index_box = QtWidgets.QGroupBox(self.centralwidget)
        self.order_index_box.setObjectName("order_index_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.order_index_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.order_index_button = QtWidgets.QPushButton(self.order_index_box)
        self.order_index_button.setObjectName("order_index_button")
        self.verticalLayout.addWidget(self.order_index_button)
        self.verticalLayout_7.addWidget(self.order_index_box)
        self.facial_check_box = QtWidgets.QGroupBox(self.centralwidget)
        self.facial_check_box.setObjectName("facial_check_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.facial_check_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.open_shape_editor_button = QtWidgets.QPushButton(self.facial_check_box)
        self.open_shape_editor_button.setObjectName("open_shape_editor_button")
        self.verticalLayout_2.addWidget(self.open_shape_editor_button)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.facial_box = QtWidgets.QGroupBox(self.facial_check_box)
        self.facial_box.setObjectName("facial_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.facial_box)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.facial_item_frame = QtWidgets.QFrame(self.facial_box)
        self.facial_item_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.facial_item_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.facial_item_frame.setObjectName("facial_item_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.facial_item_frame)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.facial_default_button = QtWidgets.QPushButton(self.facial_item_frame)
        self.facial_default_button.setObjectName("facial_default_button")
        self.verticalLayout_6.addWidget(self.facial_default_button)
        self.verticalLayout_5.addWidget(self.facial_item_frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.create_facial_key_button = QtWidgets.QPushButton(self.facial_box)
        self.create_facial_key_button.setMinimumSize(QtCore.QSize(80, 0))
        self.create_facial_key_button.setObjectName("create_facial_key_button")
        self.horizontalLayout_2.addWidget(self.create_facial_key_button)
        self.delete_facial_key_button = QtWidgets.QPushButton(self.facial_box)
        self.delete_facial_key_button.setMinimumSize(QtCore.QSize(80, 0))
        self.delete_facial_key_button.setObjectName("delete_facial_key_button")
        self.horizontalLayout_2.addWidget(self.delete_facial_key_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_11.addWidget(self.facial_box)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.look_box = QtWidgets.QGroupBox(self.facial_check_box)
        self.look_box.setObjectName("look_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.look_box)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.look_item_frame = QtWidgets.QFrame(self.look_box)
        self.look_item_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.look_item_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.look_item_frame.setObjectName("look_item_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.look_item_frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.look_default_button = QtWidgets.QPushButton(self.look_item_frame)
        self.look_default_button.setObjectName("look_default_button")
        self.verticalLayout_4.addWidget(self.look_default_button)
        self.verticalLayout_3.addWidget(self.look_item_frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_look_key_button = QtWidgets.QPushButton(self.look_box)
        self.create_look_key_button.setMinimumSize(QtCore.QSize(80, 0))
        self.create_look_key_button.setObjectName("create_look_key_button")
        self.horizontalLayout.addWidget(self.create_look_key_button)
        self.delete_look_key_button = QtWidgets.QPushButton(self.look_box)
        self.delete_look_key_button.setMinimumSize(QtCore.QSize(80, 0))
        self.delete_look_key_button.setObjectName("delete_look_key_button")
        self.horizontalLayout.addWidget(self.delete_look_key_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_10.addWidget(self.look_box)
        self.mouth_box = QtWidgets.QGroupBox(self.facial_check_box)
        self.mouth_box.setObjectName("mouth_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.mouth_box)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mouth_item_frame = QtWidgets.QFrame(self.mouth_box)
        self.mouth_item_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mouth_item_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mouth_item_frame.setObjectName("mouth_item_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mouth_item_frame)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.mouth_default_button = QtWidgets.QPushButton(self.mouth_item_frame)
        self.mouth_default_button.setObjectName("mouth_default_button")
        self.verticalLayout_9.addWidget(self.mouth_default_button)
        self.verticalLayout_8.addWidget(self.mouth_item_frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.create_mouth_key_button = QtWidgets.QPushButton(self.mouth_box)
        self.create_mouth_key_button.setMinimumSize(QtCore.QSize(80, 0))
        self.create_mouth_key_button.setObjectName("create_mouth_key_button")
        self.horizontalLayout_3.addWidget(self.create_mouth_key_button)
        self.delete_mouth_key_button = QtWidgets.QPushButton(self.mouth_box)
        self.delete_mouth_key_button.setMinimumSize(QtCore.QSize(80, 0))
        self.delete_mouth_key_button.setObjectName("delete_mouth_key_button")
        self.horizontalLayout_3.addWidget(self.delete_mouth_key_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_10.addWidget(self.mouth_box)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addWidget(self.facial_check_box)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.order_index_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "ブレンドシェイプindexの修正", None, -1))
        self.order_index_button.setText(QtWidgets.QApplication.translate("MainWindow", "indexの修正", None, -1))
        self.facial_check_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "確認ツール", None, -1))
        self.open_shape_editor_button.setText(QtWidgets.QApplication.translate("MainWindow", "ShapeEditorを開く", None, -1))
        self.facial_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "表情確認", None, -1))
        self.facial_default_button.setText(QtWidgets.QApplication.translate("MainWindow", "デフォルト", None, -1))
        self.create_facial_key_button.setText(QtWidgets.QApplication.translate("MainWindow", "表情キー作成", None, -1))
        self.delete_facial_key_button.setText(QtWidgets.QApplication.translate("MainWindow", "キー削除", None, -1))
        self.look_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "視線確認", None, -1))
        self.look_default_button.setText(QtWidgets.QApplication.translate("MainWindow", "デフォルト", None, -1))
        self.create_look_key_button.setText(QtWidgets.QApplication.translate("MainWindow", "視線キー作成", None, -1))
        self.delete_look_key_button.setText(QtWidgets.QApplication.translate("MainWindow", "キー削除", None, -1))
        self.mouth_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "発音確認", None, -1))
        self.mouth_default_button.setText(QtWidgets.QApplication.translate("MainWindow", "デフォルト", None, -1))
        self.create_mouth_key_button.setText(QtWidgets.QApplication.translate("MainWindow", "発音キー作成", None, -1))
        self.delete_mouth_key_button.setText(QtWidgets.QApplication.translate("MainWindow", "キー削除", None, -1))

