# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\CyDesignerTools_Legacy\Maya\scripts\Project_Gallop\cdt_compress_playblast\cdt_compress_playblast.ui'
#
# Created: Tue Mar 23 15:56:50 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 306)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.target_dir = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.target_dir.sizePolicy().hasHeightForWidth())
        self.target_dir.setSizePolicy(sizePolicy)
        self.target_dir.setMinimumSize(QtCore.QSize(200, 0))
        self.target_dir.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.target_dir.setObjectName("target_dir")
        self.horizontalLayout.addWidget(self.target_dir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.should_keep_original = QtWidgets.QCheckBox(self.groupBox)
        self.should_keep_original.setObjectName("should_keep_original")
        self.verticalLayout.addWidget(self.should_keep_original)
        self.should_open_mp4 = QtWidgets.QCheckBox(self.groupBox)
        self.should_open_mp4.setObjectName("should_open_mp4")
        self.verticalLayout.addWidget(self.should_open_mp4)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.info_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.info_text.setReadOnly(True)
        self.info_text.setObjectName("info_text")
        self.verticalLayout_3.addWidget(self.info_text)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.compress_switch = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compress_switch.sizePolicy().hasHeightForWidth())
        self.compress_switch.setSizePolicy(sizePolicy)
        self.compress_switch.setMinimumSize(QtCore.QSize(0, 50))
        self.compress_switch.setObjectName("compress_switch")
        self.horizontalLayout_6.addWidget(self.compress_switch)
        self.open_dir = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_dir.sizePolicy().hasHeightForWidth())
        self.open_dir.setSizePolicy(sizePolicy)
        self.open_dir.setMinimumSize(QtCore.QSize(0, 50))
        self.open_dir.setMaximumSize(QtCore.QSize(200, 16777215))
        self.open_dir.setObjectName("open_dir")
        self.horizontalLayout_6.addWidget(self.open_dir)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "ツール設定", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "圧縮対象ディレクトリ", None, -1))
        self.should_keep_original.setText(QtWidgets.QApplication.translate("MainWindow", "元のaviファイルを保持する", None, -1))
        self.should_open_mp4.setText(QtWidgets.QApplication.translate("MainWindow", "mp4を圧縮後に再生（バッチ実行時は再生しません）", None, -1))
        self.compress_switch.setText(QtWidgets.QApplication.translate("MainWindow", "圧縮設定の適用", None, -1))
        self.open_dir.setText(QtWidgets.QApplication.translate("MainWindow", "圧縮対象ディレクトリを開く", None, -1))

