sub_settings_path:
  - C:\cygames\wiz2\tools\maya\settings\chara_tools_launcher\chara_tools_launcher_settings_3dcg.yaml
  - C:\cygames\wiz2\tools\maya\settings\chara_tools_launcher\chara_tools_launcher_settings_user.yaml

tools:
  # カテゴリの作成
  # - name: //カテゴリ名
  #   label: //separatorとして表示されるlabel
  #   type: category
  
  # コマンドの作成
  # - name: //ツール名
  #   label: //ボタンに表示されるラベル
  #   type: command
  #   icon: //iconに使用するテクスチャ名 fbxReview.png
  #   category: //ボタンをどのカテゴリに表示するか（指定しなければ最後に追加されたカテゴリを自動的に指定）
  #   tooltip: //ボタンにカーソルを併せた際に表示されるtips
  #   command: //実行するコマンド //import Project_Wizard2.chara.fbx_tool_wrapper_ui.controller as controller;controller.main()
  #   enable: //ツールが有効かどうか Falseでreadonly

  # ネストの作成
  # - name: //ネストされたツール名
  #   label: //ツールのラベル
  #   type : nest
  #   icon: ネストされたツールのラベルに表示されるアイコン
  #   tools :　#commandを配列で指定する。
  #     - name: wiz2 bind
  #       label: バインド
  #       type: command
  #       tooltip: wiz2でのみ動作する skinning用 tool
  #       command: import Project_Wizard2.chara.chara_rebinder.main;Project_Wizard2.chara.chara_rebinder.bind_rebind.BindSkinCmd.project_bind()
  #       enable: True

  #     - name: wiz2 rebind
  #       label: リバインド
  #       type: command
  #       tooltip: wiz2でのみ動作する skinning用 tool
  #       command: import Project_Wizard2.chara.chara_rebinder.main;Project_Wizard2.chara.chara_rebinder.bind_rebind.BindSkinCmd.rebind()
  #       enable: True

  - name: exporter
    label: エクスポーター
    type: category

  - name: fbx tools
    label: FBX Tools
    type: command
    icon: fbxReview.png
    tooltip: Wiz2でのみ動作する、FBX関連ツールの起動
    command: import Project_Wizard2.chara.fbx_tool_wrapper_ui.controller as controller;controller.main()
    enable: True
  
  - name: skinning
    label: スキニング
    type: category

  - name: bind
    label: wiz2設定でバインド
    type : nest
    icon: smoothSkin.png
    tools :
      - name: wiz2 bind
        label: バインド
        type: command
        tooltip: wiz2でのみ動作する skinning用 tool
        command: import Project_Wizard2.chara.chara_rebinder.main;Project_Wizard2.chara.chara_rebinder.bind_rebind.BindSkinCmd.project_bind()
        enable: True

      - name: wiz2 rebind
        label: リバインド
        type: command
        tooltip: wiz2でのみ動作する skinning用 tool
        command: import Project_Wizard2.chara.chara_rebinder.main;Project_Wizard2.chara.chara_rebinder.bind_rebind.BindSkinCmd.rebind()
        enable: True

  # - name: bone_importer
  #   label: キャラクター骨のインポート
  #   type : nest
  #   icon: joint.svg
  #   tools :
  #     - name: chara_bone_importer
  #       label: インポートのみ
  #       tooltip: "シーンに適した骨のインポート"
  #       type: command
  #       command: import Project_Wizard2.chara.chara_bone_importer as chara_bone_importer;chara_bone_importer.exec_import_only()
  #       enable: True

  #     - name: chara_bone_importer
  #       label: インポート＆再バインド(β版)
  #       tooltip: "シーンに適した骨のインポート"
  #       type: command
  #       command: import Project_Wizard2.chara.chara_bone_importer as chara_bone_importer;chara_bone_importer.exec_recreate_bone()
  #       enable: True

  - name: demo_animation
    label: ウエイト確認/アニメーション
    type : nest
    icon: animateSnapshot.png
    tools :
      - name: create_demo_animation
        label: 作成
        tooltip: "デモアニメーションを作成する"
        type: command
        command: from Project_Wizard2.chara import chara_check_animation_importer;chara_check_animation_importer.create()
        enable: True

      - name: switch_demo_animation
        label: 切り替え
        tooltip: "体操と移動のアニメーションを切り替えます。"
        type: command
        command: from Project_Wizard2.chara import chara_check_animation_importer;chara_check_animation_importer.switch_animation()
        enable: True

      - name: remove_demo_animation
        label: 削除
        tooltip: "unityへfbx,textureのいデータ転送するツール\n現在はfbxのみ"
        type: command
        command: from Project_Wizard2.chara import chara_check_animation_importer;chara_check_animation_importer.remove()
        enable: True

  - name: CyWeightEditor
    label: CyWeightEditor
    icon: exportSmoothSkin.png
    type: command
    tooltip: "Cygames標準のweight editor"
    type: command
    command: import CyWeightEditor;import importlib;importlib.reload(CyWeightEditor);CyWeightEditor.UI()
    enable: True

  - name: joint
    label: ジョイント
    type: category

  - name: segment_scale_off
    label: SegmentScaleをオフ
    icon: joint.svg
    type: command
    tooltip: "選択ジョイントのsegment scaleをオフ\n選択していなければすべての骨のsegment scaleをオフ"
    type: command
    command: from Project_Wizard2.chara.chara_utility.other_tools import OtherTools;selected = cmds.ls(sl=True);OtherTools.set_segment_scale(False, selected)
    enable: True

  - name: model
    label: モデル
    type: category

  - name: animation_convert_mtk_to_shr
    label: アウトラインの作成・更新
    icon: character.svg
    type: command
    tooltip: 選択したメッシュのアウトラインメッシュを生成
    command: import Project_Wizard2.chara.chara_utility.outline as chara_outline;chara_outline.create_outline()
    enable: True
    
  - name: hidden_vertex_color
    label: 足先非表示の頂点カラー設定
    icon: paintVertexColour.png
    type: command
    tooltip: 頂点カラーの設定
    command: import Project_Wizard2.chara.hidden_vertex_color.main;Project_Wizard2.chara.hidden_vertex_color.main.main()
    enable: True

  - name: normal_settings
    label: 法線設定ツール
    icon: polyNormalsConform.png
    type: command
    tooltip: 頂点カラーの設定
    command: import Project_Wizard2.chara.normal_editor.main;import importlib;importlib.reload(Project_Wizard2.chara.normal_editor.main);Project_Wizard2.chara.normal_editor.main.main()
    enable: True

  - name: diff_selector
    label: 差分選択ツール
    icon: textureList.svg
    type: command
    tooltip: 差分切り替えを行うツール
    command: import Project_Wizard2.chara.chara_diff_selector as chara_diff_selector;chara_diff_selector.show()
    enable: True

  - name: edge_set_creator
    label: edge setの作成/編集
    icon: edges_NEX.png
    type: command
    tooltip: "wiz2のキャラクターの各パーツの接合部の情報を保持するedge setを作成/編集するツール"
    type: command
    command: import Project_Wizard2.chara.edge_set_creator as edge_set_creator;edge_set_creator.show()
    enable: True

  - name: prop
    label: プロップ
    type: category

  - name: prop_offset_tool
    label: Prop Offset ツール
    type : command
    tooltip: "プロップ用、オフセットの作成ツール"
    icon: offsetSurface.png
    command: import Project_Wizard2.chara.prop_offset_tools as prop_offset_tools;prop_offset_tools.show();
    enable: True
    # tools :
    #   - name: create_offset
    #     label: オフセットの作成/原点へ
    #     type: command
    #     tooltip: 骨を選択して実行/prop用offset保持transformの作成
    #     command: import Project_Wizard2.chara.prop_offset_tools as prop_offset_tools;prop_offset_tools.create_offset()
    #     enable: True

    #   - name: offset_root_joint
    #     label: オフセット
    #     type: command
    #     tooltip: 骨を選択して実行/ 保持しているオフセットのtransform値骨にをセット
    #     command: import Project_Wizard2.chara.prop_offset_tools as prop_offset_tools;prop_offset_tools.reset_offset()
    #     enable: True

  - name: checker
    label: チェッカー
    type: category

  - name: avatar_checker
    label: アバターチェッカー
    icon: checkboxOn.png
    type: command
    tooltip: アバターのデータチェッカー
    command: import Project_Wizard2.chara.character_checker as chr_checker;chr_checker.show_chr_checker()
    enable: True
  
  - name: prop_checker
    label: プロップチェッカー
    icon: checkboxOn.png
    type: command
    tooltip: プロップチェッカー
    command: import Project_Wizard2.chara.character_checker as chr_checker;chr_checker.show_prp_checker()
    enable: True

  - name: GallopSymmetricalWeightChecker
    label: ウエイトの対称チェッカー
    icon: mirrorSkinWeight.png
    type: command
    tooltip: ウエイトの対称性チェックツール/glpから転用
    command: import Project_Wizard2.chara.glp_symmetrical_weight_checker.main as main;import importlib;importlib.reload(main);main.Main().show_ui()
    enable: True
  
  - name: GallopSymmetricalPositionChecker
    label: 頂点の対称チェッカー
    icon: symmetrize.png
    type: command
    tooltip: 頂点位置の対称性チェックツール/glpから転用
    command: import Project_Wizard2.chara.glp_symmetrical_position_checker.main as main;import importlib;importlib.reload(main);main.Main().show_ui()
    enable: True

  - name: compare_bone_tool
    label: 骨比較ツール
    icon: joint.svg
    type: command
    tooltip: 頂点位置の対称性チェックツール/glpから転用
    command: from Project_Wizard2.chara import compare_bone_tool;compare_bone_tool.show()
    enable: True