# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tech-designer\Maya\scripts\Project_Gallop\glp_maya_to_shotgrid\ui\shotgun_tool_window.ui'
#
# Created: Wed Nov 10 18:57:20 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtWidgets
try:
    # Maya2022-
    from builtins import object
except Exception:
    pass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 721)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sg_asset_data_view = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.sg_asset_data_view.setEnabled(False)
        self.sg_asset_data_view.setObjectName("sg_asset_data_view")
        self.verticalLayout_5.addWidget(self.sg_asset_data_view)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.target_dir_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.target_dir_line.setObjectName("target_dir_line")
        self.horizontalLayout.addWidget(self.target_dir_line)
        self.open_target_dir_button = QtWidgets.QPushButton(self.groupBox_3)
        self.open_target_dir_button.setObjectName("open_target_dir_button")
        self.horizontalLayout.addWidget(self.open_target_dir_button)
        self.set_target_dir_button = QtWidgets.QPushButton(self.groupBox_3)
        self.set_target_dir_button.setObjectName("set_target_dir_button")
        self.horizontalLayout.addWidget(self.set_target_dir_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pb_width_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.pb_width_spinbox.setMaximum(10000)
        self.pb_width_spinbox.setProperty("value", 256)
        self.pb_width_spinbox.setObjectName("pb_width_spinbox")
        self.horizontalLayout_3.addWidget(self.pb_width_spinbox)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.pb_height_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.pb_height_spinbox.setMaximum(10000)
        self.pb_height_spinbox.setProperty("value", 256)
        self.pb_height_spinbox.setObjectName("pb_height_spinbox")
        self.horizontalLayout_3.addWidget(self.pb_height_spinbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.pb_is_remove_org_avi = QtWidgets.QCheckBox(self.groupBox_2)
        self.pb_is_remove_org_avi.setObjectName("pb_is_remove_org_avi")
        self.verticalLayout_2.addWidget(self.pb_is_remove_org_avi)
        self.pb_is_should_view_mp4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.pb_is_should_view_mp4.setObjectName("pb_is_should_view_mp4")
        self.verticalLayout_2.addWidget(self.pb_is_should_view_mp4)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.sg_asset_add_button = QtWidgets.QPushButton(self.groupBox)
        self.sg_asset_add_button.setObjectName("sg_asset_add_button")
        self.verticalLayout.addWidget(self.sg_asset_add_button)
        self.ss_register_sg_button = QtWidgets.QPushButton(self.groupBox)
        self.ss_register_sg_button.setObjectName("ss_register_sg_button")
        self.verticalLayout.addWidget(self.ss_register_sg_button)
        self.pb_register_sg_button = QtWidgets.QPushButton(self.groupBox)
        self.pb_register_sg_button.setObjectName("pb_register_sg_button")
        self.verticalLayout.addWidget(self.pb_register_sg_button)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_3.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 705, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.login_status = QtWidgets.QAction(MainWindow)
        self.login_status.setObjectName("login_status")
        self.menu.addAction(self.login_status)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "GlpMayaToShotgrid", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "情報", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "撮影", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "共通設定", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "保存/読込用フォルダ", None, -1))
        self.open_target_dir_button.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.set_target_dir_button.setText(QtWidgets.QApplication.translate("MainWindow", "設定", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Playblast", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Width", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Height", None, -1))
        self.pb_is_remove_org_avi.setText(QtWidgets.QApplication.translate("MainWindow", "元のaviを保持する", None, -1))
        self.pb_is_should_view_mp4.setText(QtWidgets.QApplication.translate("MainWindow", "撮影後動画ファイルを開く", None, -1))
        self.sg_asset_add_button.setText(QtWidgets.QApplication.translate("MainWindow", "現在のシーンをShotgridに新規登録", None, -1))
        self.ss_register_sg_button.setText(QtWidgets.QApplication.translate("MainWindow", "スクリーンショットを撮影し、Shotgridに登録/更新", None, -1))
        self.pb_register_sg_button.setText(QtWidgets.QApplication.translate("MainWindow", "直前に選択したパネルでPlayBlastを撮影し、Shotgridに登録/更新", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "メニュー", None, -1))
        self.login_status.setText(QtWidgets.QApplication.translate("MainWindow", "ログイン情報", None, -1))
