# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tech-designer\Maya\scripts\Project_Gallop\glp_mob_audience_setting\ui\mob_audience_setting_window.ui'
#
# Created: Wed Jan 12 12:16:24 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 827)
        MainWindow.setMinimumSize(QtCore.QSize(600, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.limit_tgt_to_loc_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.limit_tgt_to_loc_cb.setChecked(True)
        self.limit_tgt_to_loc_cb.setObjectName("limit_tgt_to_loc_cb")
        self.horizontalLayout_6.addWidget(self.limit_tgt_to_loc_cb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setContentsMargins(2, 5, 2, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rein_gear_setting_cb = QtWidgets.QGroupBox(self.frame)
        self.rein_gear_setting_cb.setCheckable(False)
        self.rein_gear_setting_cb.setChecked(False)
        self.rein_gear_setting_cb.setObjectName("rein_gear_setting_cb")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rein_gear_setting_cb)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rein_gear_distance_setting_cb = QtWidgets.QGroupBox(self.rein_gear_setting_cb)
        self.rein_gear_distance_setting_cb.setCheckable(True)
        self.rein_gear_distance_setting_cb.setChecked(False)
        self.rein_gear_distance_setting_cb.setObjectName("rein_gear_distance_setting_cb")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rein_gear_distance_setting_cb)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.rein_gear_distance_setting_cb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.rein_gear_distance_setting_cb)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.audience_distance_setting_sb = QtWidgets.QDoubleSpinBox(self.rein_gear_distance_setting_cb)
        self.audience_distance_setting_sb.setDecimals(2)
        self.audience_distance_setting_sb.setMaximum(1000.0)
        self.audience_distance_setting_sb.setProperty("value", 70.0)
        self.audience_distance_setting_sb.setObjectName("audience_distance_setting_sb")
        self.horizontalLayout.addWidget(self.audience_distance_setting_sb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.rein_gear_distance_setting_cb)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.minus_x_rb = QtWidgets.QRadioButton(self.rein_gear_distance_setting_cb)
        self.minus_x_rb.setChecked(True)
        self.minus_x_rb.setObjectName("minus_x_rb")
        self.horizontalLayout_2.addWidget(self.minus_x_rb)
        self.plus_x_rb = QtWidgets.QRadioButton(self.rein_gear_distance_setting_cb)
        self.plus_x_rb.setObjectName("plus_x_rb")
        self.horizontalLayout_2.addWidget(self.plus_x_rb)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.rein_gear_distance_setting_cb)
        self.exec_set_setting_button = QtWidgets.QPushButton(self.rein_gear_setting_cb)
        self.exec_set_setting_button.setObjectName("exec_set_setting_button")
        self.verticalLayout_2.addWidget(self.exec_set_setting_button)
        self.verticalLayout_6.addWidget(self.rein_gear_setting_cb)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setContentsMargins(2, 5, 2, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.rain_gear_ratio_sb = QtWidgets.QSpinBox(self.groupBox)
        self.rain_gear_ratio_sb.setProperty("value", 1)
        self.rain_gear_ratio_sb.setObjectName("rain_gear_ratio_sb")
        self.horizontalLayout_4.addWidget(self.rain_gear_ratio_sb)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.normal_gear_ratio_sb = QtWidgets.QSpinBox(self.groupBox)
        self.normal_gear_ratio_sb.setProperty("value", 1)
        self.normal_gear_ratio_sb.setObjectName("normal_gear_ratio_sb")
        self.horizontalLayout_4.addWidget(self.normal_gear_ratio_sb)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.exec_set_random_setting_button = QtWidgets.QPushButton(self.groupBox)
        self.exec_set_random_setting_button.setObjectName("exec_set_random_setting_button")
        self.verticalLayout_8.addWidget(self.exec_set_random_setting_button)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.aim_const_container_box = QtWidgets.QGroupBox(self.tab_3)
        self.aim_const_container_box.setObjectName("aim_const_container_box")
        self.aim_const_container_layout = QtWidgets.QVBoxLayout(self.aim_const_container_box)
        self.aim_const_container_layout.setObjectName("aim_const_container_layout")
        self.label_4 = QtWidgets.QLabel(self.aim_const_container_box)
        self.label_4.setObjectName("label_4")
        self.aim_const_container_layout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aim_target_object_list_wedget = QtWidgets.QListWidget(self.aim_const_container_box)
        self.aim_target_object_list_wedget.setMinimumSize(QtCore.QSize(0, 80))
        self.aim_target_object_list_wedget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.aim_target_object_list_wedget.setObjectName("aim_target_object_list_wedget")
        self.horizontalLayout_3.addWidget(self.aim_target_object_list_wedget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.add_aim_target_object_button = QtWidgets.QPushButton(self.aim_const_container_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_aim_target_object_button.sizePolicy().hasHeightForWidth())
        self.add_aim_target_object_button.setSizePolicy(sizePolicy)
        self.add_aim_target_object_button.setObjectName("add_aim_target_object_button")
        self.verticalLayout_5.addWidget(self.add_aim_target_object_button)
        self.del_aim_target_object_button = QtWidgets.QPushButton(self.aim_const_container_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_aim_target_object_button.sizePolicy().hasHeightForWidth())
        self.del_aim_target_object_button.setSizePolicy(sizePolicy)
        self.del_aim_target_object_button.setObjectName("del_aim_target_object_button")
        self.verticalLayout_5.addWidget(self.del_aim_target_object_button)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.aim_const_container_layout.addLayout(self.horizontalLayout_3)
        self.exec_aim_const_button = QtWidgets.QPushButton(self.aim_const_container_box)
        self.exec_aim_const_button.setObjectName("exec_aim_const_button")
        self.aim_const_container_layout.addWidget(self.exec_aim_const_button)
        self.verticalLayout.addWidget(self.aim_const_container_box)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.select_normal_locator_button = QtWidgets.QPushButton(self.groupBox_4)
        self.select_normal_locator_button.setObjectName("select_normal_locator_button")
        self.horizontalLayout_9.addWidget(self.select_normal_locator_button)
        self.select_rein_gear_button = QtWidgets.QPushButton(self.groupBox_4)
        self.select_rein_gear_button.setObjectName("select_rein_gear_button")
        self.horizontalLayout_9.addWidget(self.select_rein_gear_button)
        self.select_reincort_button = QtWidgets.QPushButton(self.groupBox_4)
        self.select_reincort_button.setObjectName("select_reincort_button")
        self.horizontalLayout_9.addWidget(self.select_reincort_button)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.select_mob_audience_on_mesh_button = QtWidgets.QPushButton(self.groupBox_4)
        self.select_mob_audience_on_mesh_button.setObjectName("select_mob_audience_on_mesh_button")
        self.verticalLayout_13.addWidget(self.select_mob_audience_on_mesh_button)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_3.setEnabled(False)
        self.textEdit_3.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_14.addWidget(self.textEdit_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.shave_ratio_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.shave_ratio_sb.setMaximum(10)
        self.shave_ratio_sb.setProperty("value", 0)
        self.shave_ratio_sb.setObjectName("shave_ratio_sb")
        self.horizontalLayout_13.addWidget(self.shave_ratio_sb)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.shave_count_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.shave_count_sb.setMaximum(999999)
        self.shave_count_sb.setObjectName("shave_count_sb")
        self.horizontalLayout_13.addWidget(self.shave_count_sb)
        self.reset_shave_ui_value_button = QtWidgets.QPushButton(self.groupBox_5)
        self.reset_shave_ui_value_button.setObjectName("reset_shave_ui_value_button")
        self.horizontalLayout_13.addWidget(self.reset_shave_ui_value_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        self.exec_shave_mob_audience_button = QtWidgets.QPushButton(self.groupBox_5)
        self.exec_shave_mob_audience_button.setObjectName("exec_shave_mob_audience_button")
        self.verticalLayout_14.addWidget(self.exec_shave_mob_audience_button)
        self.verticalLayout.addWidget(self.groupBox_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout.setStretch(4, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.rp_container_box = QtWidgets.QGroupBox(self.tab_4)
        self.rp_container_box.setObjectName("rp_container_box")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.rp_container_box)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.add_rpt_button_layout = QtWidgets.QHBoxLayout()
        self.add_rpt_button_layout.setSpacing(6)
        self.add_rpt_button_layout.setObjectName("add_rpt_button_layout")
        self.label_3 = QtWidgets.QLabel(self.rp_container_box)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName("label_3")
        self.add_rpt_button_layout.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.add_rpt_button_layout.addItem(spacerItem6)
        self.max_placement_value_sb = QtWidgets.QSpinBox(self.rp_container_box)
        self.max_placement_value_sb.setMaximum(1000000)
        self.max_placement_value_sb.setProperty("value", 30000)
        self.max_placement_value_sb.setObjectName("max_placement_value_sb")
        self.add_rpt_button_layout.addWidget(self.max_placement_value_sb)
        self.label_13 = QtWidgets.QLabel(self.rp_container_box)
        self.label_13.setObjectName("label_13")
        self.add_rpt_button_layout.addWidget(self.label_13)
        self.verticalLayout_11.addLayout(self.add_rpt_button_layout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.rp_container_box)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.rpt_obj_distance_sb = QtWidgets.QDoubleSpinBox(self.rp_container_box)
        self.rpt_obj_distance_sb.setDecimals(1)
        self.rpt_obj_distance_sb.setMaximum(99999.0)
        self.rpt_obj_distance_sb.setProperty("value", 50.0)
        self.rpt_obj_distance_sb.setObjectName("rpt_obj_distance_sb")
        self.horizontalLayout_5.addWidget(self.rpt_obj_distance_sb)
        self.label_15 = QtWidgets.QLabel(self.rp_container_box)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.rp_container_box)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.surface_area_ratio_sb = QtWidgets.QSpinBox(self.rp_container_box)
        self.surface_area_ratio_sb.setMaximum(99999)
        self.surface_area_ratio_sb.setProperty("value", 10000)
        self.surface_area_ratio_sb.setObjectName("surface_area_ratio_sb")
        self.horizontalLayout_7.addWidget(self.surface_area_ratio_sb)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.rp_container_box)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.rpt_scalex_toggle_button = QtWidgets.QPushButton(self.rp_container_box)
        self.rpt_scalex_toggle_button.setMinimumSize(QtCore.QSize(60, 0))
        self.rpt_scalex_toggle_button.setStyleSheet("background-color: gray")
        self.rpt_scalex_toggle_button.setObjectName("rpt_scalex_toggle_button")
        self.horizontalLayout_11.addWidget(self.rpt_scalex_toggle_button)
        self.rpt_scaley_toggle_button = QtWidgets.QPushButton(self.rp_container_box)
        self.rpt_scaley_toggle_button.setMinimumSize(QtCore.QSize(60, 0))
        self.rpt_scaley_toggle_button.setStyleSheet("background-color: red")
        self.rpt_scaley_toggle_button.setObjectName("rpt_scaley_toggle_button")
        self.horizontalLayout_11.addWidget(self.rpt_scaley_toggle_button)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.reset_rpt_setting_button = QtWidgets.QPushButton(self.rp_container_box)
        self.reset_rpt_setting_button.setObjectName("reset_rpt_setting_button")
        self.horizontalLayout_11.addWidget(self.reset_rpt_setting_button)
        self.add_rpt_button = QtWidgets.QPushButton(self.rp_container_box)
        self.add_rpt_button.setObjectName("add_rpt_button")
        self.horizontalLayout_11.addWidget(self.add_rpt_button)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.rpt_scroll_area = QtWidgets.QScrollArea(self.rp_container_box)
        self.rpt_scroll_area.setWidgetResizable(True)
        self.rpt_scroll_area.setObjectName("rpt_scroll_area")
        self.rpt_widget_area = QtWidgets.QWidget()
        self.rpt_widget_area.setGeometry(QtCore.QRect(0, 0, 536, 290))
        self.rpt_widget_area.setObjectName("rpt_widget_area")
        self.rpt_widget_lauout = QtWidgets.QVBoxLayout(self.rpt_widget_area)
        self.rpt_widget_lauout.setObjectName("rpt_widget_lauout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 445, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rpt_widget_lauout.addItem(spacerItem10)
        self.rpt_scroll_area.setWidget(self.rpt_widget_area)
        self.verticalLayout_11.addWidget(self.rpt_scroll_area)
        self.groupBox_3 = QtWidgets.QGroupBox(self.rp_container_box)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_10.addWidget(self.textEdit_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.add_avoidance_obj_button = QtWidgets.QPushButton(self.groupBox_3)
        self.add_avoidance_obj_button.setObjectName("add_avoidance_obj_button")
        self.horizontalLayout_10.addWidget(self.add_avoidance_obj_button)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.avoidance_obj_widget_area = QtWidgets.QWidget()
        self.avoidance_obj_widget_area.setGeometry(QtCore.QRect(0, 0, 514, 169))
        self.avoidance_obj_widget_area.setObjectName("avoidance_obj_widget_area")
        self.avoidance_obj_widget_layout = QtWidgets.QVBoxLayout(self.avoidance_obj_widget_area)
        self.avoidance_obj_widget_layout.setObjectName("avoidance_obj_widget_layout")
        spacerItem12 = QtWidgets.QSpacerItem(20, 93, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.avoidance_obj_widget_layout.addItem(spacerItem12)
        self.scrollArea.setWidget(self.avoidance_obj_widget_area)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.exec_rp_button = QtWidgets.QPushButton(self.rp_container_box)
        self.exec_rp_button.setObjectName("exec_rp_button")
        self.verticalLayout_11.addWidget(self.exec_rp_button)
        self.verticalLayout_9.addWidget(self.rp_container_box)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_12.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "モブ観客設定ツール", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "オブジェクトに特殊設定セット", None, -1))
        self.limit_tgt_to_loc_cb.setText(QtWidgets.QApplication.translate("MainWindow", "対象をロケーターに限定する", None, -1))
        self.rein_gear_setting_cb.setTitle(QtWidgets.QApplication.translate("MainWindow", "選択したオブジェクトを雨具設定(ScaleY=2)にする", None, -1))
        self.rein_gear_distance_setting_cb.setTitle(QtWidgets.QApplication.translate("MainWindow", "傘を差した観客同士の距離制限を設定する", None, -1))
        self.textEdit.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS UI Gothic\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">この項目をONにすると、傘を持てる観客の距離内のロケーターの雨具設定をカッパ限定(ScaleY=3)にします。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "傘を差した観客同士の制限距離(cm)", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "距離制限を行う順番", None, -1))
        self.minus_x_rb.setText(QtWidgets.QApplication.translate("MainWindow", "-X方向から", None, -1))
        self.plus_x_rb.setText(QtWidgets.QApplication.translate("MainWindow", "X方向から", None, -1))
        self.exec_set_setting_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択したオブジェクトを雨具設定を実行", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "選択したオブジェクトに雨具有り(ScaleY=2)無し(ScaleY=1)をランダムに割り振る", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "雨具有り無しの割合", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "有り", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "：", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "無し", None, -1))
        self.exec_set_random_setting_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択したオブジェクトに雨具有り(ScaleY=2)無し(ScaleY=1)のランダム割り振りを実行", None, -1))
        self.aim_const_container_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "選択したオブジェクトから近い対象オブジェクトにエイムさせて向かせる", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "対象オブジェクトリスト", None, -1))
        self.add_aim_target_object_button.setText(QtWidgets.QApplication.translate("MainWindow", "追加", None, -1))
        self.del_aim_target_object_button.setText(QtWidgets.QApplication.translate("MainWindow", "削除", None, -1))
        self.exec_aim_const_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択したオブジェクトから近い対象オブジェクトに対してエイム", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "特殊選択", None, -1))
        self.select_normal_locator_button.setText(QtWidgets.QApplication.translate("MainWindow", "雨具無(ScaleY=1)を選択", None, -1))
        self.select_rein_gear_button.setText(QtWidgets.QApplication.translate("MainWindow", "雨具有(ScaleY=2)を選択", None, -1))
        self.select_reincort_button.setText(QtWidgets.QApplication.translate("MainWindow", "雨合羽(ScaleY=3)を選択", None, -1))
        self.select_mob_audience_on_mesh_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択したメッシュ上にあるモブ観客ロケーター(pos*****)を選択", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "モブ観客ロケーターを間引く", None, -1))
        self.textEdit_3.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS UI Gothic\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">選択したモブ観客ロケーター(pos*****)を「割合」または「実数」で削減します。割合と実数両方とも入力されている場合は割合を優先します。実数削除の場合、ロケーターより多い数が入力されている時は全て削除されます。</p></body></html>", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "割合(0-10)", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "実数", None, -1))
        self.reset_shave_ui_value_button.setText(QtWidgets.QApplication.translate("MainWindow", "割合値/実数値をリセット", None, -1))
        self.exec_shave_mob_audience_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択したモブ観客ロケーター(pos*****)を割合または実数で間引く", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "オブジェクト特殊設定/エイム/間引き", None, -1))
        self.rp_container_box.setTitle(QtWidgets.QApplication.translate("MainWindow", "面積比率でランダム配置", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "配置MAX個数", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "(個)", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "オブジェクト間の距離", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "(cm) 以上", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "表面積算出の割り率(値が小さくなると面積あたりに置くロケーターの数が増えます)", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "天候スイッチ(トグル)", None, -1))
        self.rpt_scalex_toggle_button.setText(QtWidgets.QApplication.translate("MainWindow", "日向(X=1)", None, -1))
        self.rpt_scaley_toggle_button.setText(QtWidgets.QApplication.translate("MainWindow", "晴れ(Y=1)", None, -1))
        self.reset_rpt_setting_button.setText(QtWidgets.QApplication.translate("MainWindow", "メッシュリストのクリア/天候リセット", None, -1))
        self.add_rpt_button.setText(QtWidgets.QApplication.translate("MainWindow", "ターゲットを追加", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "重複回避オブジェクリスト", None, -1))
        self.textEdit_2.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS UI Gothic\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">重複回避を行うオブジェクトを登録して、オブジェクトの「原点」からの回避距離を設定することで回避距離以内にオブジェクトが配置されないようにする。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">登録するだけでは回避されないので要注意。</p></body></html>", None, -1))
        self.add_avoidance_obj_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択したオブジェクトを回避用オブジェクトを追加", None, -1))
        self.exec_rp_button.setText(QtWidgets.QApplication.translate("MainWindow", "ランダム配置を実行", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "面積比率ランダム配置", None, -1))

