DEV_MODE: true

Hair_Tools_Path: //cydrive01/104_projects/149_shenron/30_design/05_character/03_data_store/00_tools/Hair_tools

GS_Cruve_Tools_Name: gs_curvetools
GS_Curve_Tools_Helpers_Name: BCM_GS_CurveToolsHelpers
GS_Curve_Tools_Helpers_Inside_Name: BCM_GSCurvetoolsHelpers
Helper_Plugin_Directory: BCM_manip_plugin
Helper_XRay_Directory: BCM_XRayCvs
Helper_Plugin_Name: bcmCurveWarpManip.py
Helper_XRay_Name: BCM_DrawXRayCvs.py

HAIR_MATERIAL_NAME: HairMat

BUTTONS:
  'colorButtonA': [85, 170, 255]
  'colorButtonB': [255, 85, 127]
  'colorButtonC': [255, 170, 127]
  'colorButtonD': [85, 85, 255]
  'colorButtonE': [170, 170, 255]
  'colorButtonF': [170, 255, 127]
  'colorButtonG': [255, 255, 127]
  'colorButtonH': [255, 170, 0]
  'colorButtonI': [214, 65, 3]
  'colorButtonJ': [144, 221, 72]

FILE_NODE_NAME: file_node
FILE_PATH_NAME: file_path
IMAGE_FILE_TYPES:
  - "tga"
  - "png"
  - "jpg"
  - "jpeg"
  - "tif"
  - "tiff"

TEXTURE_FILE_TYPES:
 depth: depthTexture
 alpha: alphaTexture




