# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tech-designer\priari\inhouse\maya\share\python\file\animation_exporter\main_window.ui'
#
# Created: Fri Jan 14 19:20:17 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

try:
    # Maya 2022-
    from builtins import object
except:
    pass

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 128)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setContentsMargins(8, 0, 8, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.InitButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InitButton.sizePolicy().hasHeightForWidth())
        self.InitButton.setSizePolicy(sizePolicy)
        self.InitButton.setMinimumSize(QtCore.QSize(80, 0))
        self.InitButton.setObjectName("InitButton")
        self.horizontalLayout_6.addWidget(self.InitButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(55, 55, 55, 255);\n"
"    border-radius: 2px;\n"
"}")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.StFrame = QtWidgets.QFrame(self.horizontalWidget_2)
        self.StFrame.setEnabled(False)
        self.StFrame.setObjectName("StFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.StFrame)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.StFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.StFrame)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.StStartText = QtWidgets.QSpinBox(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StStartText.sizePolicy().hasHeightForWidth())
        self.StStartText.setSizePolicy(sizePolicy)
        self.StStartText.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.StStartText.setMaximum(9999)
        self.StStartText.setProperty("value", 3)
        self.StStartText.setObjectName("StStartText")
        self.verticalLayout_5.addWidget(self.StStartText)
        self.StStartButton = QtWidgets.QPushButton(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StStartButton.sizePolicy().hasHeightForWidth())
        self.StStartButton.setSizePolicy(sizePolicy)
        self.StStartButton.setStyleSheet("margin: 4px;")
        self.StStartButton.setObjectName("StStartButton")
        self.verticalLayout_5.addWidget(self.StStartButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("margin-top: 2px;")
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.StEndText = QtWidgets.QSpinBox(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StEndText.sizePolicy().hasHeightForWidth())
        self.StEndText.setSizePolicy(sizePolicy)
        self.StEndText.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.StEndText.setMaximum(9999)
        self.StEndText.setObjectName("StEndText")
        self.verticalLayout_6.addWidget(self.StEndText)
        self.StEndButton = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.StEndButton.setStyleSheet("margin: 4px;")
        self.StEndButton.setObjectName("StEndButton")
        self.verticalLayout_6.addWidget(self.StEndButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addWidget(self.horizontalWidget_3)
        self.horizontalLayout_2.addWidget(self.StFrame)
        self.LpFrame = QtWidgets.QFrame(self.horizontalWidget_2)
        self.LpFrame.setEnabled(False)
        self.LpFrame.setObjectName("LpFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.LpFrame)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.LpFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalWidget_4 = QtWidgets.QWidget(self.LpFrame)
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.LpStartText = QtWidgets.QSpinBox(self.horizontalWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LpStartText.sizePolicy().hasHeightForWidth())
        self.LpStartText.setSizePolicy(sizePolicy)
        self.LpStartText.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LpStartText.setMaximum(9999)
        self.LpStartText.setObjectName("LpStartText")
        self.verticalLayout_8.addWidget(self.LpStartText)
        self.LpStartButton = QtWidgets.QPushButton(self.horizontalWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LpStartButton.sizePolicy().hasHeightForWidth())
        self.LpStartButton.setSizePolicy(sizePolicy)
        self.LpStartButton.setMinimumSize(QtCore.QSize(0, 0))
        self.LpStartButton.setBaseSize(QtCore.QSize(0, 0))
        self.LpStartButton.setStyleSheet("margin: 4px;")
        self.LpStartButton.setObjectName("LpStartButton")
        self.verticalLayout_8.addWidget(self.LpStartButton)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.label_5 = QtWidgets.QLabel(self.horizontalWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("margin-top: 2px;")
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LpEndText = QtWidgets.QSpinBox(self.horizontalWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LpEndText.sizePolicy().hasHeightForWidth())
        self.LpEndText.setSizePolicy(sizePolicy)
        self.LpEndText.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LpEndText.setMaximum(9999)
        self.LpEndText.setObjectName("LpEndText")
        self.verticalLayout_7.addWidget(self.LpEndText)
        self.LpEndButton = QtWidgets.QPushButton(self.horizontalWidget_4)
        self.LpEndButton.setStyleSheet("margin: 4px;")
        self.LpEndButton.setObjectName("LpEndButton")
        self.verticalLayout_7.addWidget(self.LpEndButton)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_3.addWidget(self.horizontalWidget_4)
        self.horizontalLayout_2.addWidget(self.LpFrame)
        self.EdFrame = QtWidgets.QFrame(self.horizontalWidget_2)
        self.EdFrame.setEnabled(False)
        self.EdFrame.setObjectName("EdFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.EdFrame)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.EdFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalWidget_5 = QtWidgets.QWidget(self.EdFrame)
        self.horizontalWidget_5.setObjectName("horizontalWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget_5)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.EdStartText = QtWidgets.QSpinBox(self.horizontalWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EdStartText.sizePolicy().hasHeightForWidth())
        self.EdStartText.setSizePolicy(sizePolicy)
        self.EdStartText.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.EdStartText.setMaximum(9999)
        self.EdStartText.setObjectName("EdStartText")
        self.verticalLayout_9.addWidget(self.EdStartText)
        self.EdStartButton = QtWidgets.QPushButton(self.horizontalWidget_5)
        self.EdStartButton.setStyleSheet("margin: 4px;")
        self.EdStartButton.setObjectName("EdStartButton")
        self.verticalLayout_9.addWidget(self.EdStartButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.label_6 = QtWidgets.QLabel(self.horizontalWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("margin-top: 2px;")
        self.label_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.EdEndText = QtWidgets.QSpinBox(self.horizontalWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EdEndText.sizePolicy().hasHeightForWidth())
        self.EdEndText.setSizePolicy(sizePolicy)
        self.EdEndText.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.EdEndText.setMaximum(9999)
        self.EdEndText.setObjectName("EdEndText")
        self.verticalLayout_10.addWidget(self.EdEndText)
        self.EdEndButton = QtWidgets.QPushButton(self.horizontalWidget_5)
        self.EdEndButton.setStyleSheet("margin: 4px;")
        self.EdEndButton.setObjectName("EdEndButton")
        self.verticalLayout_10.addWidget(self.EdEndButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_4.addWidget(self.horizontalWidget_5)
        self.horizontalLayout_2.addWidget(self.EdFrame)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "AnimationExporterOption", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "分割出力設定", None, -1))
        self.InitButton.setText(QtWidgets.QApplication.translate("MainWindow", "初期化", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "st", None, -1))
        self.StStartButton.setText(QtWidgets.QApplication.translate("MainWindow", "現在", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "～", None, -1))
        self.StEndButton.setText(QtWidgets.QApplication.translate("MainWindow", "現在", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "lp", None, -1))
        self.LpStartButton.setText(QtWidgets.QApplication.translate("MainWindow", "現在", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "～", None, -1))
        self.LpEndButton.setText(QtWidgets.QApplication.translate("MainWindow", "現在", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "ed", None, -1))
        self.EdStartButton.setText(QtWidgets.QApplication.translate("MainWindow", "現在", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "～", None, -1))
        self.EdEndButton.setText(QtWidgets.QApplication.translate("MainWindow", "現在", None, -1))

