# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\maya_legacy\scripts\Project_Gallop\glp_symmetrical_position_checker\ui\symmetricalPositionCheckerWindow.ui'
#
# Created: Tue Oct 19 17:41:01 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

try:
    # Maya 2022-
    from builtins import object
except Exception:
    pass
from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 365)
        MainWindow.setMinimumSize(QtCore.QSize(400, 365))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingGBox = QtWidgets.QGroupBox(self.centralwidget)
        self.settingGBox.setObjectName("settingGBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.settingGBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.posAllowranceLbl = QtWidgets.QLabel(self.settingGBox)
        self.posAllowranceLbl.setObjectName("posAllowranceLbl")
        self.horizontalLayout_2.addWidget(self.posAllowranceLbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.posAllowranceBox = QtWidgets.QDoubleSpinBox(self.settingGBox)
        self.posAllowranceBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posAllowranceBox.sizePolicy().hasHeightForWidth())
        self.posAllowranceBox.setSizePolicy(sizePolicy)
        self.posAllowranceBox.setMinimumSize(QtCore.QSize(70, 0))
        self.posAllowranceBox.setFrame(True)
        self.posAllowranceBox.setReadOnly(False)
        self.posAllowranceBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.posAllowranceBox.setKeyboardTracking(True)
        self.posAllowranceBox.setDecimals(3)
        self.posAllowranceBox.setProperty("value", 0.001)
        self.posAllowranceBox.setObjectName("posAllowranceBox")
        self.horizontalLayout_2.addWidget(self.posAllowranceBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.baseAxisLbl = QtWidgets.QLabel(self.settingGBox)
        self.baseAxisLbl.setObjectName("baseAxisLbl")
        self.horizontalLayout_3.addWidget(self.baseAxisLbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.XAxisRadio = QtWidgets.QRadioButton(self.settingGBox)
        self.XAxisRadio.setChecked(True)
        self.XAxisRadio.setObjectName("XAxisRadio")
        self.horizontalLayout_3.addWidget(self.XAxisRadio)
        self.YAxisRadio = QtWidgets.QRadioButton(self.settingGBox)
        self.YAxisRadio.setObjectName("YAxisRadio")
        self.horizontalLayout_3.addWidget(self.YAxisRadio)
        self.ZAxisRadio = QtWidgets.QRadioButton(self.settingGBox)
        self.ZAxisRadio.setObjectName("ZAxisRadio")
        self.horizontalLayout_3.addWidget(self.ZAxisRadio)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.settingGBox)
        self.selectAssymetryGBox = QtWidgets.QGroupBox(self.centralwidget)
        self.selectAssymetryGBox.setObjectName("selectAssymetryGBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.selectAssymetryGBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.selectAsymmetryBtn = QtWidgets.QPushButton(self.selectAssymetryGBox)
        self.selectAsymmetryBtn.setObjectName("selectAsymmetryBtn")
        self.gridLayout_5.addWidget(self.selectAsymmetryBtn, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.selectAssymetryGBox)
        self.execGrp = QtWidgets.QGroupBox(self.centralwidget)
        self.execGrp.setObjectName("execGrp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.execGrp)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toMinusBySelectionBtn = QtWidgets.QPushButton(self.execGrp)
        self.toMinusBySelectionBtn.setObjectName("toMinusBySelectionBtn")
        self.horizontalLayout.addWidget(self.toMinusBySelectionBtn)
        self.toPlusBySelectionBtn = QtWidgets.QPushButton(self.execGrp)
        self.toPlusBySelectionBtn.setObjectName("toPlusBySelectionBtn")
        self.horizontalLayout.addWidget(self.toPlusBySelectionBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.execGrp)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.statusLabel = QtWidgets.QLabel(self.groupBox)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_3.addWidget(self.statusLabel, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "GlpSymmetricalPositionChecker", None, -1))
        self.settingGBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "設定", None, -1))
        self.posAllowranceLbl.setText(QtWidgets.QApplication.translate("MainWindow", "近似頂点検出の誤差範囲", None, -1))
        self.baseAxisLbl.setText(QtWidgets.QApplication.translate("MainWindow", "対称座標選択", None, -1))
        self.XAxisRadio.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.YAxisRadio.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.ZAxisRadio.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.selectAssymetryGBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "非対称頂点の選択", None, -1))
        self.selectAsymmetryBtn.setText(QtWidgets.QApplication.translate("MainWindow", "非対称な頂点を選択", None, -1))
        self.execGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "非対称頂点の修正", None, -1))
        self.toMinusBySelectionBtn.setText(QtWidgets.QApplication.translate("MainWindow", "選択頂点を「-」に合わせる", None, -1))
        self.toPlusBySelectionBtn.setText(QtWidgets.QApplication.translate("MainWindow", "選択頂点を「+」に合わせる", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Status", None, -1))
        self.statusLabel.setText(QtWidgets.QApplication.translate("MainWindow", "頂点かメッシュを選択して実行してください", None, -1))

