# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'z:\mtk\tools\maya\modules\mtku\scripts\mtku\maya\menus\cutscene\camerasequencer_storyboard_render\ui\storyBoadrdRenderOption.ui'
#
# Created: Mon Jul 26 19:20:23 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_StoryboardPatchRenderWindow(object):
    def setupUi(self, StoryboardPatchRenderWindow):
        StoryboardPatchRenderWindow.setObjectName("StoryboardPatchRenderWindow")
        StoryboardPatchRenderWindow.resize(690, 753)
        StoryboardPatchRenderWindow.setStyleSheet("QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    padding: 0 10px;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    border: 1px solid #1d1d1d;\n"
"    padding: 2px;\n"
"    margin-top: 2ex;\n"
"}\n"
"QListWidget{\n"
"    background-color:#383838;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(StoryboardPatchRenderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.firstClipList = QtWidgets.QListWidget(self.groupBox)
        self.firstClipList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.firstClipList.setObjectName("firstClipList")
        self.verticalLayout_3.addWidget(self.firstClipList)
        self.updateButton = QtWidgets.QPushButton(self.groupBox)
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout_3.addWidget(self.updateButton)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.customClipList = QtWidgets.QListWidget(self.groupBox_2)
        self.customClipList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.customClipList.setObjectName("customClipList")
        self.verticalLayout_4.addWidget(self.customClipList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.AddcustomClipListButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddcustomClipListButton.sizePolicy().hasHeightForWidth())
        self.AddcustomClipListButton.setSizePolicy(sizePolicy)
        self.AddcustomClipListButton.setMinimumSize(QtCore.QSize(50, 0))
        self.AddcustomClipListButton.setMaximumSize(QtCore.QSize(0, 16777215))
        self.AddcustomClipListButton.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.AddcustomClipListButton.setFont(font)
        self.AddcustomClipListButton.setObjectName("AddcustomClipListButton")
        self.horizontalLayout.addWidget(self.AddcustomClipListButton)
        self.removeCustomClipListButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeCustomClipListButton.sizePolicy().hasHeightForWidth())
        self.removeCustomClipListButton.setSizePolicy(sizePolicy)
        self.removeCustomClipListButton.setMinimumSize(QtCore.QSize(50, 0))
        self.removeCustomClipListButton.setMaximumSize(QtCore.QSize(0, 16777215))
        self.removeCustomClipListButton.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.removeCustomClipListButton.setFont(font)
        self.removeCustomClipListButton.setObjectName("removeCustomClipListButton")
        self.horizontalLayout.addWidget(self.removeCustomClipListButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.directory = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directory.sizePolicy().hasHeightForWidth())
        self.directory.setSizePolicy(sizePolicy)
        self.directory.setMinimumSize(QtCore.QSize(0, 22))
        self.directory.setReadOnly(True)
        self.directory.setObjectName("directory")
        self.horizontalLayout_7.addWidget(self.directory)
        self.openFolderButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFolderButton.sizePolicy().hasHeightForWidth())
        self.openFolderButton.setSizePolicy(sizePolicy)
        self.openFolderButton.setMinimumSize(QtCore.QSize(0, 0))
        self.openFolderButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.openFolderButton.setObjectName("openFolderButton")
        self.horizontalLayout_7.addWidget(self.openFolderButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.width = QtWidgets.QSpinBox(self.groupBox_3)
        self.width.setMinimumSize(QtCore.QSize(70, 0))
        self.width.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.width.setMinimum(1)
        self.width.setMaximum(4096)
        self.width.setProperty("value", 1920)
        self.width.setObjectName("width")
        self.horizontalLayout_3.addWidget(self.width)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.height = QtWidgets.QSpinBox(self.groupBox_3)
        self.height.setMinimumSize(QtCore.QSize(70, 0))
        self.height.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.height.setMinimum(1)
        self.height.setMaximum(4096)
        self.height.setProperty("value", 1080)
        self.height.setObjectName("height")
        self.horizontalLayout_4.addWidget(self.height)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.isOutline = QtWidgets.QCheckBox(self.groupBox_3)
        self.isOutline.setMinimumSize(QtCore.QSize(125, 0))
        self.isOutline.setChecked(True)
        self.isOutline.setObjectName("isOutline")
        self.horizontalLayout_5.addWidget(self.isOutline)
        self.isOpenExplorer = QtWidgets.QCheckBox(self.groupBox_3)
        self.isOpenExplorer.setChecked(True)
        self.isOpenExplorer.setObjectName("isOpenExplorer")
        self.horizontalLayout_5.addWidget(self.isOpenExplorer)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.isCutName = QtWidgets.QCheckBox(self.groupBox_4)
        self.isCutName.setMinimumSize(QtCore.QSize(96, 0))
        self.isCutName.setChecked(True)
        self.isCutName.setObjectName("isCutName")
        self.gridLayout_2.addWidget(self.isCutName, 1, 0, 1, 1)
        self.isFocalLength = QtWidgets.QCheckBox(self.groupBox_4)
        self.isFocalLength.setChecked(True)
        self.isFocalLength.setObjectName("isFocalLength")
        self.gridLayout_2.addWidget(self.isFocalLength, 0, 1, 1, 1)
        self.isSceneName = QtWidgets.QCheckBox(self.groupBox_4)
        self.isSceneName.setMinimumSize(QtCore.QSize(96, 0))
        self.isSceneName.setChecked(True)
        self.isSceneName.setObjectName("isSceneName")
        self.gridLayout_2.addWidget(self.isSceneName, 0, 0, 1, 1)
        self.isFrame = QtWidgets.QCheckBox(self.groupBox_4)
        self.isFrame.setChecked(True)
        self.isFrame.setObjectName("isFrame")
        self.gridLayout_2.addWidget(self.isFrame, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.startCurrentFrameRendering = QtWidgets.QPushButton(self.groupBox_3)
        self.startCurrentFrameRendering.setObjectName("startCurrentFrameRendering")
        self.verticalLayout.addWidget(self.startCurrentFrameRendering)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.startRenderButton = QtWidgets.QPushButton(self.centralwidget)
        self.startRenderButton.setObjectName("startRenderButton")
        self.horizontalLayout_12.addWidget(self.startRenderButton)
        self.applyButton = QtWidgets.QPushButton(self.centralwidget)
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout_12.addWidget(self.applyButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_12.addWidget(self.closeButton)
        self.gridLayout.addLayout(self.horizontalLayout_12, 3, 0, 1, 1)
        StoryboardPatchRenderWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StoryboardPatchRenderWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
        self.menubar.setObjectName("menubar")
        StoryboardPatchRenderWindow.setMenuBar(self.menubar)

        self.retranslateUi(StoryboardPatchRenderWindow)
        QtCore.QMetaObject.connectSlotsByName(StoryboardPatchRenderWindow)

    def retranslateUi(self, StoryboardPatchRenderWindow):
        StoryboardPatchRenderWindow.setWindowTitle(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "StoryboardPatchRender", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "FirstClipList", None, -1))
        self.updateButton.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Update Clip", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "CustomClipList", None, -1))
        self.AddcustomClipListButton.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "+", None, -1))
        self.removeCustomClipListButton.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "-", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "RenderSettings", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Directory:", None, -1))
        self.openFolderButton.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "📁", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Image format:", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "png", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Width:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Height:", None, -1))
        self.isOutline.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Draw Outline", None, -1))
        self.isOpenExplorer.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Open explorer later", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "DrawOption", None, -1))
        self.isCutName.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "CutName", None, -1))
        self.isFocalLength.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "FocalLength", None, -1))
        self.isSceneName.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "SceneName", None, -1))
        self.isFrame.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Frame", None, -1))
        self.startCurrentFrameRendering.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Current Frame Rendering", None, -1))
        self.startRenderButton.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Start Render", None, -1))
        self.applyButton.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Apply", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("StoryboardPatchRenderWindow", "Close", None, -1))

