# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\S14054\Documents\maya\scripts\gl_test\glp_chara_body_difference\ui\charaBodyDifferenceWindow.ui'
#
# Created: Fri Jun  4 10:41:24 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(280, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(280, 280))
        MainWindow.setMaximumSize(QtCore.QSize(280, 280))
        MainWindow.setWhatsThis("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.mainVLO = QtWidgets.QVBoxLayout()
        self.mainVLO.setContentsMargins(5, 5, 5, 5)
        self.mainVLO.setObjectName("mainVLO")
        self.createBodyDiffGrp = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.createBodyDiffGrp.setFont(font)
        self.createBodyDiffGrp.setStyleSheet("")
        self.createBodyDiffGrp.setObjectName("createBodyDiffGrp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.createBodyDiffGrp)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.createBodyDiffFrame = QtWidgets.QFrame(self.createBodyDiffGrp)
        self.createBodyDiffFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createBodyDiffFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createBodyDiffFrame.setLineWidth(2)
        self.createBodyDiffFrame.setObjectName("createBodyDiffFrame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.createBodyDiffFrame)
        self.gridLayout_9.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.createBodyDiffBtn = QtWidgets.QPushButton(self.createBodyDiffFrame)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.createBodyDiffBtn.setFont(font)
        self.createBodyDiffBtn.setObjectName("createBodyDiffBtn")
        self.gridLayout_9.addWidget(self.createBodyDiffBtn, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.createBodyDiffFrame, 0, 0, 1, 1)
        self.mainVLO.addWidget(self.createBodyDiffGrp)
        self.moveBodyDiffForPosGrp = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.moveBodyDiffForPosGrp.setFont(font)
        self.moveBodyDiffForPosGrp.setObjectName("moveBodyDiffForPosGrp")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.moveBodyDiffForPosGrp)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.moveBodyDiffForPosFrame = QtWidgets.QFrame(self.moveBodyDiffForPosGrp)
        self.moveBodyDiffForPosFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.moveBodyDiffForPosFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.moveBodyDiffForPosFrame.setLineWidth(2)
        self.moveBodyDiffForPosFrame.setObjectName("moveBodyDiffForPosFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.moveBodyDiffForPosFrame)
        self.gridLayout_6.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_6.setHorizontalSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.moveBodyDiffForPosHLO = QtWidgets.QHBoxLayout()
        self.moveBodyDiffForPosHLO.setSpacing(1)
        self.moveBodyDiffForPosHLO.setObjectName("moveBodyDiffForPosHLO")
        self.moveBodyDiffForPosContractBtn = QtWidgets.QPushButton(self.moveBodyDiffForPosFrame)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.moveBodyDiffForPosContractBtn.setFont(font)
        self.moveBodyDiffForPosContractBtn.setObjectName("moveBodyDiffForPosContractBtn")
        self.moveBodyDiffForPosHLO.addWidget(self.moveBodyDiffForPosContractBtn)
        self.moveBodyDiffForPosExpandBtn = QtWidgets.QPushButton(self.moveBodyDiffForPosFrame)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.moveBodyDiffForPosExpandBtn.setFont(font)
        self.moveBodyDiffForPosExpandBtn.setObjectName("moveBodyDiffForPosExpandBtn")
        self.moveBodyDiffForPosHLO.addWidget(self.moveBodyDiffForPosExpandBtn)
        self.gridLayout_6.addLayout(self.moveBodyDiffForPosHLO, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.moveBodyDiffForPosFrame, 0, 0, 1, 1)
        self.mainVLO.addWidget(self.moveBodyDiffForPosGrp)
        self.moveBodyDiffForGrpNodeGrp = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.moveBodyDiffForGrpNodeGrp.setFont(font)
        self.moveBodyDiffForGrpNodeGrp.setObjectName("moveBodyDiffForGrpNodeGrp")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.moveBodyDiffForGrpNodeGrp)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.moveBodyDiffForGrpNodeFrame = QtWidgets.QFrame(self.moveBodyDiffForGrpNodeGrp)
        self.moveBodyDiffForGrpNodeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.moveBodyDiffForGrpNodeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.moveBodyDiffForGrpNodeFrame.setLineWidth(2)
        self.moveBodyDiffForGrpNodeFrame.setObjectName("moveBodyDiffForGrpNodeFrame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.moveBodyDiffForGrpNodeFrame)
        self.gridLayout_8.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_8.setHorizontalSpacing(2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.moveBodyDiffForGrpNodeHLO = QtWidgets.QHBoxLayout()
        self.moveBodyDiffForGrpNodeHLO.setSpacing(1)
        self.moveBodyDiffForGrpNodeHLO.setObjectName("moveBodyDiffForGrpNodeHLO")
        self.moveBodyDiffForGrpNodeContractBtn = QtWidgets.QPushButton(self.moveBodyDiffForGrpNodeFrame)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.moveBodyDiffForGrpNodeContractBtn.setFont(font)
        self.moveBodyDiffForGrpNodeContractBtn.setObjectName("moveBodyDiffForGrpNodeContractBtn")
        self.moveBodyDiffForGrpNodeHLO.addWidget(self.moveBodyDiffForGrpNodeContractBtn)
        self.moveBodyDiffForGrpNodeExpandBtn = QtWidgets.QPushButton(self.moveBodyDiffForGrpNodeFrame)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.moveBodyDiffForGrpNodeExpandBtn.setFont(font)
        self.moveBodyDiffForGrpNodeExpandBtn.setObjectName("moveBodyDiffForGrpNodeExpandBtn")
        self.moveBodyDiffForGrpNodeHLO.addWidget(self.moveBodyDiffForGrpNodeExpandBtn)
        self.gridLayout_8.addLayout(self.moveBodyDiffForGrpNodeHLO, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.moveBodyDiffForGrpNodeFrame, 0, 0, 1, 1)
        self.mainVLO.addWidget(self.moveBodyDiffForGrpNodeGrp)
        self.changeBodyDiffSkiningStateGrp = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.changeBodyDiffSkiningStateGrp.setFont(font)
        self.changeBodyDiffSkiningStateGrp.setObjectName("changeBodyDiffSkiningStateGrp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.changeBodyDiffSkiningStateGrp)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.changeBodyDiffSkiningStateFrame = QtWidgets.QFrame(self.changeBodyDiffSkiningStateGrp)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.changeBodyDiffSkiningStateFrame.setFont(font)
        self.changeBodyDiffSkiningStateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.changeBodyDiffSkiningStateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.changeBodyDiffSkiningStateFrame.setLineWidth(2)
        self.changeBodyDiffSkiningStateFrame.setObjectName("changeBodyDiffSkiningStateFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.changeBodyDiffSkiningStateFrame)
        self.gridLayout_7.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.changeBodyDiffSkiningStateHLO = QtWidgets.QHBoxLayout()
        self.changeBodyDiffSkiningStateHLO.setSpacing(1)
        self.changeBodyDiffSkiningStateHLO.setObjectName("changeBodyDiffSkiningStateHLO")
        self.changeBodyDiffSkiningStateDetachBtn = QtWidgets.QPushButton(self.changeBodyDiffSkiningStateFrame)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.changeBodyDiffSkiningStateDetachBtn.setFont(font)
        self.changeBodyDiffSkiningStateDetachBtn.setObjectName("changeBodyDiffSkiningStateDetachBtn")
        self.changeBodyDiffSkiningStateHLO.addWidget(self.changeBodyDiffSkiningStateDetachBtn)
        self.changeBodyDiffSkiningStateBindBtn = QtWidgets.QPushButton(self.changeBodyDiffSkiningStateFrame)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.changeBodyDiffSkiningStateBindBtn.setFont(font)
        self.changeBodyDiffSkiningStateBindBtn.setObjectName("changeBodyDiffSkiningStateBindBtn")
        self.changeBodyDiffSkiningStateHLO.addWidget(self.changeBodyDiffSkiningStateBindBtn)
        self.gridLayout_7.addLayout(self.changeBodyDiffSkiningStateHLO, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.changeBodyDiffSkiningStateFrame, 0, 0, 1, 1)
        self.mainVLO.addWidget(self.changeBodyDiffSkiningStateGrp)
        self.gridLayout.addLayout(self.mainVLO, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "GallopCharaBodyDifference", None, -1))
        self.createBodyDiffGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "体型差分作成", None, -1))
        self.createBodyDiffBtn.setText(QtWidgets.QApplication.translate("MainWindow", "体型差分を作成する", None, -1))
        self.moveBodyDiffForPosGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "体型差分の位置移動(Position用)", None, -1))
        self.moveBodyDiffForPosContractBtn.setText(QtWidgets.QApplication.translate("MainWindow", "まとめる", None, -1))
        self.moveBodyDiffForPosExpandBtn.setText(QtWidgets.QApplication.translate("MainWindow", "ひろげる", None, -1))
        self.moveBodyDiffForGrpNodeGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "体型差分の位置移動(グループノード用)", None, -1))
        self.moveBodyDiffForGrpNodeContractBtn.setText(QtWidgets.QApplication.translate("MainWindow", "まとめる", None, -1))
        self.moveBodyDiffForGrpNodeExpandBtn.setText(QtWidgets.QApplication.translate("MainWindow", "ひろげる", None, -1))
        self.changeBodyDiffSkiningStateGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "体型差分のスキニング状態の変更", None, -1))
        self.changeBodyDiffSkiningStateDetachBtn.setText(QtWidgets.QApplication.translate("MainWindow", "デタッチ", None, -1))
        self.changeBodyDiffSkiningStateBindBtn.setText(QtWidgets.QApplication.translate("MainWindow", "バインド", None, -1))

