RecentLoadedPresetFile:
- C:/cygames/shrshare/tools/config/postproc_set_editor/maya/preset_character.yaml
- C:/cygames/shrshare/tools/config/postproc_set_editor/maya/preset_environment.yaml
- C:/cygames/shrshare/tools/config/postproc_set_editor/maya/preset_animation.yaml