# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_chara_copy_work_data\ui\glp_copy_work_data_gui.ui'
#
# Created: Thu Mar 30 19:00:43 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 421)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.src_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.src_icon_label.setText("")
        self.src_icon_label.setObjectName("src_icon_label")
        self.horizontalLayout.addWidget(self.src_icon_label)
        self.src_label = QtWidgets.QLabel(self.centralwidget)
        self.src_label.setObjectName("src_label")
        self.horizontalLayout.addWidget(self.src_label)
        self.src_folder_line = QtWidgets.QLineEdit(self.centralwidget)
        self.src_folder_line.setObjectName("src_folder_line")
        self.horizontalLayout.addWidget(self.src_folder_line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.get_scene_root_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_scene_root_button.setMinimumSize(QtCore.QSize(100, 0))
        self.get_scene_root_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.get_scene_root_button.setObjectName("get_scene_root_button")
        self.horizontalLayout_5.addWidget(self.get_scene_root_button)
        self.src_folder_select_button = QtWidgets.QPushButton(self.centralwidget)
        self.src_folder_select_button.setMinimumSize(QtCore.QSize(40, 0))
        self.src_folder_select_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.src_folder_select_button.setObjectName("src_folder_select_button")
        self.horizontalLayout_5.addWidget(self.src_folder_select_button)
        self.src_folder_open_button = QtWidgets.QPushButton(self.centralwidget)
        self.src_folder_open_button.setMinimumSize(QtCore.QSize(40, 0))
        self.src_folder_open_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.src_folder_open_button.setObjectName("src_folder_open_button")
        self.horizontalLayout_5.addWidget(self.src_folder_open_button)
        self.horizontalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.replace_str_frame = QtWidgets.QFrame(self.centralwidget)
        self.replace_str_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.replace_str_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.replace_str_frame.setObjectName("replace_str_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.replace_str_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.replace_h_layout = QtWidgets.QHBoxLayout()
        self.replace_h_layout.setObjectName("replace_h_layout")
        self.copy_icon_label = QtWidgets.QLabel(self.replace_str_frame)
        self.copy_icon_label.setMinimumSize(QtCore.QSize(30, 0))
        self.copy_icon_label.setText("")
        self.copy_icon_label.setObjectName("copy_icon_label")
        self.replace_h_layout.addWidget(self.copy_icon_label)
        self.label_3 = QtWidgets.QLabel(self.replace_str_frame)
        self.label_3.setObjectName("label_3")
        self.replace_h_layout.addWidget(self.label_3)
        self.replace_old_line = QtWidgets.QLineEdit(self.replace_str_frame)
        self.replace_old_line.setEnabled(False)
        self.replace_old_line.setReadOnly(False)
        self.replace_old_line.setObjectName("replace_old_line")
        self.replace_h_layout.addWidget(self.replace_old_line)
        self.replace_icon_label = QtWidgets.QLabel(self.replace_str_frame)
        self.replace_icon_label.setText("")
        self.replace_icon_label.setObjectName("replace_icon_label")
        self.replace_h_layout.addWidget(self.replace_icon_label)
        self.replace_new_line = QtWidgets.QLineEdit(self.replace_str_frame)
        self.replace_new_line.setObjectName("replace_new_line")
        self.replace_h_layout.addWidget(self.replace_new_line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.replace_h_layout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.replace_h_layout)
        self.verticalLayout.addWidget(self.replace_str_frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dst_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.dst_icon_label.setText("")
        self.dst_icon_label.setObjectName("dst_icon_label")
        self.horizontalLayout_2.addWidget(self.dst_icon_label)
        self.dst_label = QtWidgets.QLabel(self.centralwidget)
        self.dst_label.setObjectName("dst_label")
        self.horizontalLayout_2.addWidget(self.dst_label)
        self.dst_folder_line = QtWidgets.QLineEdit(self.centralwidget)
        self.dst_folder_line.setObjectName("dst_folder_line")
        self.horizontalLayout_2.addWidget(self.dst_folder_line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sync_src_parent_button = QtWidgets.QPushButton(self.centralwidget)
        self.sync_src_parent_button.setMinimumSize(QtCore.QSize(140, 0))
        self.sync_src_parent_button.setMaximumSize(QtCore.QSize(140, 16777215))
        self.sync_src_parent_button.setObjectName("sync_src_parent_button")
        self.horizontalLayout_6.addWidget(self.sync_src_parent_button)
        self.dst_folder_open_button = QtWidgets.QPushButton(self.centralwidget)
        self.dst_folder_open_button.setMinimumSize(QtCore.QSize(40, 0))
        self.dst_folder_open_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.dst_folder_open_button.setObjectName("dst_folder_open_button")
        self.horizontalLayout_6.addWidget(self.dst_folder_open_button)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.all_select_button = QtWidgets.QPushButton(self.centralwidget)
        self.all_select_button.setObjectName("all_select_button")
        self.horizontalLayout_4.addWidget(self.all_select_button)
        self.no_select_button = QtWidgets.QPushButton(self.centralwidget)
        self.no_select_button.setObjectName("no_select_button")
        self.horizontalLayout_4.addWidget(self.no_select_button)
        self.default_select_button = QtWidgets.QPushButton(self.centralwidget)
        self.default_select_button.setObjectName("default_select_button")
        self.horizontalLayout_4.addWidget(self.default_select_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.table_refresh_button = QtWidgets.QPushButton(self.centralwidget)
        self.table_refresh_button.setObjectName("table_refresh_button")
        self.horizontalLayout_4.addWidget(self.table_refresh_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.info_table_view = QtWidgets.QTableView(self.centralwidget)
        self.info_table_view.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.info_table_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.info_table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.info_table_view.setObjectName("info_table_view")
        self.info_table_view.horizontalHeader().setDefaultSectionSize(270)
        self.info_table_view.horizontalHeader().setStretchLastSection(True)
        self.info_table_view.verticalHeader().setDefaultSectionSize(23)
        self.verticalLayout.addWidget(self.info_table_view)
        self.replace_check_frame = QtWidgets.QFrame(self.centralwidget)
        self.replace_check_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.replace_check_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.replace_check_frame.setObjectName("replace_check_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.replace_check_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.replace_check_frame)
        self.exec_copy_button = QtWidgets.QPushButton(self.centralwidget)
        self.exec_copy_button.setObjectName("exec_copy_button")
        self.verticalLayout.addWidget(self.exec_copy_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "1, 「コピー元フォルダ」にコピーするフォルダを指定します. データIDのフォルダ（bdy1001_00等）を指定した場合はIDの置換を行うことができます.", None, -1))
        self.src_label.setText(QtWidgets.QApplication.translate("MainWindow", "コピー元フォルダ", None, -1))
        self.get_scene_root_button.setText(QtWidgets.QApplication.translate("MainWindow", "シーンから取得", None, -1))
        self.src_folder_select_button.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.src_folder_open_button.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "置換ID（=フォルダ名）", None, -1))
        self.dst_label.setText(QtWidgets.QApplication.translate("MainWindow", "コピー先フォルダ", None, -1))
        self.sync_src_parent_button.setText(QtWidgets.QApplication.translate("MainWindow", "コピー元と親を合わせる", None, -1))
        self.dst_folder_open_button.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "2, コピーしたいデータにチェックを入れ「作業データコピー開始」ボタンを押してください.", None, -1))
        self.all_select_button.setText(QtWidgets.QApplication.translate("MainWindow", "すべて選択", None, -1))
        self.no_select_button.setText(QtWidgets.QApplication.translate("MainWindow", "すべて解除", None, -1))
        self.default_select_button.setText(QtWidgets.QApplication.translate("MainWindow", "初期選択に戻す", None, -1))
        self.table_refresh_button.setText(QtWidgets.QApplication.translate("MainWindow", "リスト更新", None, -1))
        self.exec_copy_button.setText(QtWidgets.QApplication.translate("MainWindow", "作業データコピー開始", None, -1))

