# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\CyGeneral\CySceneExplorer\ui\cy_scene_explorer_gui.ui'
#
# Created: Mon Nov 20 18:57:01 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.main_tab.setObjectName("main_tab")
        self.explorer_tab = QtWidgets.QWidget()
        self.explorer_tab.setObjectName("explorer_tab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.explorer_tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.main_splitter = QtWidgets.QSplitter(self.explorer_tab)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.sub_splitter = QtWidgets.QSplitter(self.main_splitter)
        self.sub_splitter.setOrientation(QtCore.Qt.Vertical)
        self.sub_splitter.setObjectName("sub_splitter")
        self.dir_tree = QtWidgets.QTreeView(self.sub_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dir_tree.sizePolicy().hasHeightForWidth())
        self.dir_tree.setSizePolicy(sizePolicy)
        self.dir_tree.setBaseSize(QtCore.QSize(0, 0))
        self.dir_tree.setItemsExpandable(True)
        self.dir_tree.setExpandsOnDoubleClick(False)
        self.dir_tree.setObjectName("dir_tree")
        self.operation_tab = QtWidgets.QTabWidget(self.sub_splitter)
        self.operation_tab.setBaseSize(QtCore.QSize(0, 0))
        self.operation_tab.setObjectName("operation_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bookmark_list = QtWidgets.QListWidget(self.tab)
        self.bookmark_list.setObjectName("bookmark_list")
        self.verticalLayout_2.addWidget(self.bookmark_list)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.up_button = QtWidgets.QPushButton(self.tab)
        self.up_button.setText("")
        self.up_button.setFlat(True)
        self.up_button.setObjectName("up_button")
        self.horizontalLayout_4.addWidget(self.up_button)
        self.down_button = QtWidgets.QPushButton(self.tab)
        self.down_button.setText("")
        self.down_button.setFlat(True)
        self.down_button.setObjectName("down_button")
        self.horizontalLayout_4.addWidget(self.down_button)
        self.add_button = QtWidgets.QPushButton(self.tab)
        self.add_button.setText("")
        self.add_button.setFlat(True)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_4.addWidget(self.add_button)
        self.del_button = QtWidgets.QPushButton(self.tab)
        self.del_button.setText("")
        self.del_button.setFlat(True)
        self.del_button.setObjectName("del_button")
        self.horizontalLayout_4.addWidget(self.del_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.operation_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.recent_file_list_2 = QtWidgets.QListWidget(self.tab_2)
        self.recent_file_list_2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.recent_file_list_2.setObjectName("recent_file_list_2")
        self.verticalLayout.addWidget(self.recent_file_list_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.update_recent_file_button = QtWidgets.QPushButton(self.tab_2)
        self.update_recent_file_button.setText("")
        self.update_recent_file_button.setFlat(True)
        self.update_recent_file_button.setObjectName("update_recent_file_button")
        self.horizontalLayout_5.addWidget(self.update_recent_file_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.operation_tab.addTab(self.tab_2, "")
        self.layoutWidget = QtWidgets.QWidget(self.main_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.root_dir_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.root_dir_line.setStyleSheet("")
        self.root_dir_line.setObjectName("root_dir_line")
        self.horizontalLayout.addWidget(self.root_dir_line)
        self.set_root_button = QtWidgets.QPushButton(self.layoutWidget)
        self.set_root_button.setText("")
        self.set_root_button.setFlat(True)
        self.set_root_button.setObjectName("set_root_button")
        self.horizontalLayout.addWidget(self.set_root_button)
        self.update_button = QtWidgets.QPushButton(self.layoutWidget)
        self.update_button.setText("")
        self.update_button.setIconSize(QtCore.QSize(16, 16))
        self.update_button.setFlat(True)
        self.update_button.setObjectName("update_button")
        self.horizontalLayout.addWidget(self.update_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.search_line.setStyleSheet("")
        self.search_line.setClearButtonEnabled(False)
        self.search_line.setObjectName("search_line")
        self.horizontalLayout_2.addWidget(self.search_line)
        self.filter_button_group = QtWidgets.QGroupBox(self.layoutWidget)
        self.filter_button_group.setTitle("")
        self.filter_button_group.setObjectName("filter_button_group")
        self.horizontalLayout_2.addWidget(self.filter_button_group)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.file_table = QtWidgets.QTableView(self.layoutWidget)
        self.file_table.setAutoFillBackground(False)
        self.file_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.file_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.file_table.setShowGrid(False)
        self.file_table.setSortingEnabled(True)
        self.file_table.setObjectName("file_table")
        self.file_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.file_table)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selection_path_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.selection_path_line.setReadOnly(True)
        self.selection_path_line.setObjectName("selection_path_line")
        self.horizontalLayout_6.addWidget(self.selection_path_line)
        self.copy_to_clipboard_button = QtWidgets.QPushButton(self.layoutWidget)
        self.copy_to_clipboard_button.setText("")
        self.copy_to_clipboard_button.setFlat(True)
        self.copy_to_clipboard_button.setObjectName("copy_to_clipboard_button")
        self.horizontalLayout_6.addWidget(self.copy_to_clipboard_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.info_label = QtWidgets.QLabel(self.layoutWidget)
        self.info_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_4.addWidget(self.info_label)
        self.horizontalLayout_7.addWidget(self.main_splitter)
        self.main_tab.addTab(self.explorer_tab, "")
        self.collection_tab = QtWidgets.QWidget()
        self.collection_tab.setObjectName("collection_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.collection_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.col_new_button = QtWidgets.QPushButton(self.collection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_new_button.sizePolicy().hasHeightForWidth())
        self.col_new_button.setSizePolicy(sizePolicy)
        self.col_new_button.setMinimumSize(QtCore.QSize(80, 0))
        self.col_new_button.setObjectName("col_new_button")
        self.horizontalLayout_3.addWidget(self.col_new_button)
        self.col_load_button = QtWidgets.QPushButton(self.collection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_load_button.sizePolicy().hasHeightForWidth())
        self.col_load_button.setSizePolicy(sizePolicy)
        self.col_load_button.setMinimumSize(QtCore.QSize(80, 0))
        self.col_load_button.setObjectName("col_load_button")
        self.horizontalLayout_3.addWidget(self.col_load_button)
        self.col_save_button = QtWidgets.QPushButton(self.collection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_save_button.sizePolicy().hasHeightForWidth())
        self.col_save_button.setSizePolicy(sizePolicy)
        self.col_save_button.setMinimumSize(QtCore.QSize(80, 0))
        self.col_save_button.setObjectName("col_save_button")
        self.horizontalLayout_3.addWidget(self.col_save_button)
        self.col_save_as_button = QtWidgets.QPushButton(self.collection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_save_as_button.sizePolicy().hasHeightForWidth())
        self.col_save_as_button.setSizePolicy(sizePolicy)
        self.col_save_as_button.setMinimumSize(QtCore.QSize(80, 0))
        self.col_save_as_button.setObjectName("col_save_as_button")
        self.horizontalLayout_3.addWidget(self.col_save_as_button)
        self.dirty_label = QtWidgets.QLabel(self.collection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirty_label.sizePolicy().hasHeightForWidth())
        self.dirty_label.setSizePolicy(sizePolicy)
        self.dirty_label.setText("")
        self.dirty_label.setObjectName("dirty_label")
        self.horizontalLayout_3.addWidget(self.dirty_label)
        self.col_json_path_label = QtWidgets.QLabel(self.collection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_json_path_label.sizePolicy().hasHeightForWidth())
        self.col_json_path_label.setSizePolicy(sizePolicy)
        self.col_json_path_label.setText("")
        self.col_json_path_label.setObjectName("col_json_path_label")
        self.horizontalLayout_3.addWidget(self.col_json_path_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.collection_splitter = QtWidgets.QSplitter(self.collection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collection_splitter.sizePolicy().hasHeightForWidth())
        self.collection_splitter.setSizePolicy(sizePolicy)
        self.collection_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.collection_splitter.setObjectName("collection_splitter")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.collection_splitter)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.col_list_layout = QtWidgets.QVBoxLayout()
        self.col_list_layout.setObjectName("col_list_layout")
        self.verticalLayout_8.addLayout(self.col_list_layout)
        self.col_add_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.col_add_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.col_add_button.setFont(font)
        self.col_add_button.setObjectName("col_add_button")
        self.verticalLayout_8.addWidget(self.col_add_button)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.collection_splitter)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.item_search_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.item_search_line.setStyleSheet("")
        self.item_search_line.setClearButtonEnabled(False)
        self.item_search_line.setObjectName("item_search_line")
        self.horizontalLayout_8.addWidget(self.item_search_line)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_9.addWidget(self.line_2)
        self.col_file_list_layout = QtWidgets.QVBoxLayout()
        self.col_file_list_layout.setObjectName("col_file_list_layout")
        self.verticalLayout_9.addLayout(self.col_file_list_layout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.selection_item_path_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.selection_item_path_line.setObjectName("selection_item_path_line")
        self.horizontalLayout_10.addWidget(self.selection_item_path_line)
        self.copy_item_to_clipboard_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.copy_item_to_clipboard_button.setText("")
        self.copy_item_to_clipboard_button.setFlat(True)
        self.copy_item_to_clipboard_button.setObjectName("copy_item_to_clipboard_button")
        self.horizontalLayout_10.addWidget(self.copy_item_to_clipboard_button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout_5.addWidget(self.collection_splitter)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.main_tab.addTab(self.collection_tab, "")
        self.verticalLayout_6.addWidget(self.main_tab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.setting_action = QtWidgets.QAction(MainWindow)
        self.setting_action.setObjectName("setting_action")
        self.setting_dir_open_action = QtWidgets.QAction(MainWindow)
        self.setting_dir_open_action.setObjectName("setting_dir_open_action")
        self.menu.addAction(self.setting_action)
        self.menu.addAction(self.setting_dir_open_action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        self.operation_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.up_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "ブックマークを上に移動", None, -1))
        self.down_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "ブックマークを下に移動", None, -1))
        self.del_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "ブックマークを削除", None, -1))
        self.operation_tab.setTabText(self.operation_tab.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "ブックマーク", None, -1))
        self.update_recent_file_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "リストを更新", None, -1))
        self.operation_tab.setTabText(self.operation_tab.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "最近使ったファイル", None, -1))
        self.root_dir_line.setToolTip(QtWidgets.QApplication.translate("MainWindow", "ファイル検索を行うルートフォルダを指定", None, -1))
        self.root_dir_line.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "　ルートフォルダ", None, -1))
        self.set_root_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "選択しているパスをルートフォルダにセット", None, -1))
        self.update_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "検索結果を更新", None, -1))
        self.search_line.setToolTip(QtWidgets.QApplication.translate("MainWindow", "検索ワードの入力. \' \'でAND検索、\' OR \'でOR検索ができます.", None, -1))
        self.search_line.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "　検索ワード", None, -1))
        self.copy_to_clipboard_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "クリップボードにコピー", None, -1))
        self.info_label.setText(QtWidgets.QApplication.translate("MainWindow", "info label", None, -1))
        self.main_tab.setTabText(self.main_tab.indexOf(self.explorer_tab), QtWidgets.QApplication.translate("MainWindow", "エクスプローラー", None, -1))
        self.col_new_button.setText(QtWidgets.QApplication.translate("MainWindow", "新規", None, -1))
        self.col_load_button.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.col_save_button.setText(QtWidgets.QApplication.translate("MainWindow", "保存", None, -1))
        self.col_save_as_button.setText(QtWidgets.QApplication.translate("MainWindow", "別名保存", None, -1))
        self.col_add_button.setText(QtWidgets.QApplication.translate("MainWindow", "新規コレクションを追加", None, -1))
        self.item_search_line.setToolTip(QtWidgets.QApplication.translate("MainWindow", "検索ワードの入力. \' \'でAND検索、\' OR \'でOR検索ができます.", None, -1))
        self.item_search_line.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "　検索ワード", None, -1))
        self.main_tab.setTabText(self.main_tab.indexOf(self.collection_tab), QtWidgets.QApplication.translate("MainWindow", "コレクション", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "メニュー", None, -1))
        self.setting_action.setText(QtWidgets.QApplication.translate("MainWindow", "設定", None, -1))
        self.setting_dir_open_action.setText(QtWidgets.QApplication.translate("MainWindow", "設定ファイルのフォルダを開く", None, -1))

