# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_eye_cover_tool\ui\glp_eye_cover_tool_ui.ui'
#
# Created: Fri Jun 24 16:23:46 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

try:
    # Maya 2022-
    from builtins import object
except Exception:
    pass

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(382, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MeshSetupGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.MeshSetupGroup.setObjectName("MeshSetupGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MeshSetupGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TexBakeGroup = QtWidgets.QGroupBox(self.MeshSetupGroup)
        self.TexBakeGroup.setObjectName("TexBakeGroup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.TexBakeGroup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.BakeLabel = QtWidgets.QLabel(self.TexBakeGroup)
        self.BakeLabel.setObjectName("BakeLabel")
        self.verticalLayout_6.addWidget(self.BakeLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BakeDstLabel = QtWidgets.QLabel(self.TexBakeGroup)
        self.BakeDstLabel.setObjectName("BakeDstLabel")
        self.horizontalLayout_2.addWidget(self.BakeDstLabel)
        self.BakeDstEditLabel = QtWidgets.QLabel(self.TexBakeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BakeDstEditLabel.sizePolicy().hasHeightForWidth())
        self.BakeDstEditLabel.setSizePolicy(sizePolicy)
        self.BakeDstEditLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.BakeDstEditLabel.setObjectName("BakeDstEditLabel")
        self.horizontalLayout_2.addWidget(self.BakeDstEditLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.BakeSrcLabel = QtWidgets.QLabel(self.TexBakeGroup)
        self.BakeSrcLabel.setObjectName("BakeSrcLabel")
        self.horizontalLayout_2.addWidget(self.BakeSrcLabel)
        self.BakeSrcEditLabel = QtWidgets.QLabel(self.TexBakeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BakeSrcEditLabel.sizePolicy().hasHeightForWidth())
        self.BakeSrcEditLabel.setSizePolicy(sizePolicy)
        self.BakeSrcEditLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.BakeSrcEditLabel.setObjectName("BakeSrcEditLabel")
        self.horizontalLayout_2.addWidget(self.BakeSrcEditLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.TexBakeButton = QtWidgets.QPushButton(self.TexBakeGroup)
        self.TexBakeButton.setMinimumSize(QtCore.QSize(0, 40))
        self.TexBakeButton.setObjectName("TexBakeButton")
        self.verticalLayout_6.addWidget(self.TexBakeButton)
        self.verticalLayout.addWidget(self.TexBakeGroup)
        self.NormalColorSetupGroup = QtWidgets.QGroupBox(self.MeshSetupGroup)
        self.NormalColorSetupGroup.setAutoFillBackground(False)
        self.NormalColorSetupGroup.setStyleSheet("")
        self.NormalColorSetupGroup.setFlat(False)
        self.NormalColorSetupGroup.setObjectName("NormalColorSetupGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.NormalColorSetupGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.NormalColorSetupLabel = QtWidgets.QLabel(self.NormalColorSetupGroup)
        self.NormalColorSetupLabel.setObjectName("NormalColorSetupLabel")
        self.verticalLayout_3.addWidget(self.NormalColorSetupLabel)
        self.NormalColorSetupButton = QtWidgets.QPushButton(self.NormalColorSetupGroup)
        self.NormalColorSetupButton.setMinimumSize(QtCore.QSize(0, 40))
        self.NormalColorSetupButton.setToolTip("")
        self.NormalColorSetupButton.setObjectName("NormalColorSetupButton")
        self.verticalLayout_3.addWidget(self.NormalColorSetupButton)
        self.verticalLayout.addWidget(self.NormalColorSetupGroup)
        self.MFaceSetupGroup = QtWidgets.QGroupBox(self.MeshSetupGroup)
        self.MFaceSetupGroup.setObjectName("MFaceSetupGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.MFaceSetupGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MFaceSetupLabel = QtWidgets.QLabel(self.MFaceSetupGroup)
        self.MFaceSetupLabel.setObjectName("MFaceSetupLabel")
        self.verticalLayout_4.addWidget(self.MFaceSetupLabel)
        self.MFaceSetupLabel2 = QtWidgets.QLabel(self.MFaceSetupGroup)
        self.MFaceSetupLabel2.setObjectName("MFaceSetupLabel2")
        self.verticalLayout_4.addWidget(self.MFaceSetupLabel2)
        self.MFaceSetupButton = QtWidgets.QPushButton(self.MFaceSetupGroup)
        self.MFaceSetupButton.setMinimumSize(QtCore.QSize(0, 40))
        self.MFaceSetupButton.setToolTip("")
        self.MFaceSetupButton.setObjectName("MFaceSetupButton")
        self.verticalLayout_4.addWidget(self.MFaceSetupButton)
        self.verticalLayout.addWidget(self.MFaceSetupGroup)
        self.verticalLayout_2.addWidget(self.MeshSetupGroup)
        self.FacialSetupGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.FacialSetupGroup.setObjectName("FacialSetupGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.FacialSetupGroup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.GetDataButton = QtWidgets.QPushButton(self.FacialSetupGroup)
        self.GetDataButton.setObjectName("GetDataButton")
        self.verticalLayout_5.addWidget(self.GetDataButton)
        self.DataInfoLabel = QtWidgets.QLabel(self.FacialSetupGroup)
        self.DataInfoLabel.setObjectName("DataInfoLabel")
        self.verticalLayout_5.addWidget(self.DataInfoLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BindLabel = QtWidgets.QLabel(self.FacialSetupGroup)
        self.BindLabel.setObjectName("BindLabel")
        self.horizontalLayout.addWidget(self.BindLabel)
        self.BindLineEdit = QtWidgets.QLineEdit(self.FacialSetupGroup)
        self.BindLineEdit.setObjectName("BindLineEdit")
        self.horizontalLayout.addWidget(self.BindLineEdit)
        self.XOffsetLabel = QtWidgets.QLabel(self.FacialSetupGroup)
        self.XOffsetLabel.setObjectName("XOffsetLabel")
        self.horizontalLayout.addWidget(self.XOffsetLabel)
        self.XOffsetSpinBox = QtWidgets.QDoubleSpinBox(self.FacialSetupGroup)
        self.XOffsetSpinBox.setDecimals(1)
        self.XOffsetSpinBox.setMinimum(-100.0)
        self.XOffsetSpinBox.setSingleStep(0.1)
        self.XOffsetSpinBox.setObjectName("XOffsetSpinBox")
        self.horizontalLayout.addWidget(self.XOffsetSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.FacialSetupButton = QtWidgets.QPushButton(self.FacialSetupGroup)
        self.FacialSetupButton.setMinimumSize(QtCore.QSize(0, 40))
        self.FacialSetupButton.setObjectName("FacialSetupButton")
        self.verticalLayout_5.addWidget(self.FacialSetupButton)
        self.CreateNewDataButton = QtWidgets.QPushButton(self.FacialSetupGroup)
        self.CreateNewDataButton.setObjectName("CreateNewDataButton")
        self.verticalLayout_5.addWidget(self.CreateNewDataButton)
        self.verticalLayout_2.addWidget(self.FacialSetupGroup)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.MeshSetupGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "目隠しメッシュのセットアップ", None, -1))
        self.TexBakeGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "目隠しメッシュへのテクスチャベイク", None, -1))
        self.BakeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "ベイク元・ベイク先の順で選択して実行してください", None, -1))
        self.BakeDstLabel.setText(QtWidgets.QApplication.translate("MainWindow", "ベイク先 : ", None, -1))
        self.BakeDstEditLabel.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.BakeSrcLabel.setText(QtWidgets.QApplication.translate("MainWindow", "ベイク元 : ", None, -1))
        self.BakeSrcEditLabel.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.TexBakeButton.setText(QtWidgets.QApplication.translate("MainWindow", "実行", None, -1))
        self.NormalColorSetupGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "M_Faceから法線・頂点カラーの転送", None, -1))
        self.NormalColorSetupLabel.setText(QtWidgets.QApplication.translate("MainWindow", "目隠しメッシュを選択して実行してください", None, -1))
        self.NormalColorSetupButton.setText(QtWidgets.QApplication.translate("MainWindow", "実行", None, -1))
        self.MFaceSetupGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "M_Faceへの仕込み", None, -1))
        self.MFaceSetupLabel.setText(QtWidgets.QApplication.translate("MainWindow", "目隠しメッシュとバインドするジョイントを選択して実行してください", None, -1))
        self.MFaceSetupLabel2.setText(QtWidgets.QApplication.translate("MainWindow", "※同時にフェイシャルで必要なセットアップデータが出力されます", None, -1))
        self.MFaceSetupButton.setText(QtWidgets.QApplication.translate("MainWindow", "実行＆セットアップデータ生成", None, -1))
        self.FacialSetupGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "フェイシャルのセットアップ", None, -1))
        self.GetDataButton.setText(QtWidgets.QApplication.translate("MainWindow", "セットアップデータ取得", None, -1))
        self.DataInfoLabel.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.BindLabel.setText(QtWidgets.QApplication.translate("MainWindow", "バインドジョイント", None, -1))
        self.XOffsetLabel.setText(QtWidgets.QApplication.translate("MainWindow", "オフセット", None, -1))
        self.FacialSetupButton.setText(QtWidgets.QApplication.translate("MainWindow", "実行", None, -1))
        self.CreateNewDataButton.setText(QtWidgets.QApplication.translate("MainWindow", "UIからセットアップデータ新規生成", None, -1))

