# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tech-designer\Maya\scripts\Project_DesignerDivision\designer_div_facial_tool\ui\main_window.ui'
#
# Created: Mon Apr  4 14:43:03 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from builtins import object
from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 825)
        MainWindow.setMinimumSize(QtCore.QSize(500, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -492, 663, 1315))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.facial_target_type_tool_frame_layout = QtWidgets.QVBoxLayout()
        self.facial_target_type_tool_frame_layout.setSpacing(0)
        self.facial_target_type_tool_frame_layout.setObjectName("facial_target_type_tool_frame_layout")
        self.facial_target_type_tool_frame_btn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.facial_target_type_tool_frame_btn.sizePolicy().hasHeightForWidth())
        self.facial_target_type_tool_frame_btn.setSizePolicy(sizePolicy)
        self.facial_target_type_tool_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.facial_target_type_tool_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.facial_target_type_tool_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.facial_target_type_tool_frame_btn.setObjectName("facial_target_type_tool_frame_btn")
        self.facial_target_type_tool_frame_layout.addWidget(self.facial_target_type_tool_frame_btn)
        self.facial_target_type_tool_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.facial_target_type_tool_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.facial_target_type_tool_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.facial_target_type_tool_frame.setObjectName("facial_target_type_tool_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.facial_target_type_tool_frame)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.edit_rig_frame_layout = QtWidgets.QVBoxLayout()
        self.edit_rig_frame_layout.setSpacing(0)
        self.edit_rig_frame_layout.setObjectName("edit_rig_frame_layout")
        self.edit_rig_frame_btn = QtWidgets.QToolButton(self.facial_target_type_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_rig_frame_btn.sizePolicy().hasHeightForWidth())
        self.edit_rig_frame_btn.setSizePolicy(sizePolicy)
        self.edit_rig_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.edit_rig_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.edit_rig_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.edit_rig_frame_btn.setObjectName("edit_rig_frame_btn")
        self.edit_rig_frame_layout.addWidget(self.edit_rig_frame_btn)
        self.edit_rig_frame = QtWidgets.QFrame(self.facial_target_type_tool_frame)
        self.edit_rig_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_rig_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_rig_frame.setObjectName("edit_rig_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.edit_rig_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.exec_attach_head_rig_btn = QtWidgets.QPushButton(self.edit_rig_frame)
        self.exec_attach_head_rig_btn.setObjectName("exec_attach_head_rig_btn")
        self.verticalLayout_6.addWidget(self.exec_attach_head_rig_btn)
        self.exec_detach_head_rig_btn = QtWidgets.QPushButton(self.edit_rig_frame)
        self.exec_detach_head_rig_btn.setObjectName("exec_detach_head_rig_btn")
        self.verticalLayout_6.addWidget(self.exec_detach_head_rig_btn)
        self.exec_reset_head_rig_controller_btn = QtWidgets.QPushButton(self.edit_rig_frame)
        self.exec_reset_head_rig_controller_btn.setObjectName("exec_reset_head_rig_controller_btn")
        self.verticalLayout_6.addWidget(self.exec_reset_head_rig_controller_btn)
        self.exec_edit_eye_highlight_rig_btn = QtWidgets.QPushButton(self.edit_rig_frame)
        self.exec_edit_eye_highlight_rig_btn.setObjectName("exec_edit_eye_highlight_rig_btn")
        self.verticalLayout_6.addWidget(self.exec_edit_eye_highlight_rig_btn)
        self.edit_rig_frame_layout.addWidget(self.edit_rig_frame)
        self.verticalLayout_8.addLayout(self.edit_rig_frame_layout)
        self.facial_check_frame_layout = QtWidgets.QVBoxLayout()
        self.facial_check_frame_layout.setSpacing(0)
        self.facial_check_frame_layout.setContentsMargins(0, 0, 0, 0)
        self.facial_check_frame_layout.setObjectName("facial_check_frame_layout")
        self.facial_check_frame_btn = QtWidgets.QToolButton(self.facial_target_type_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.facial_check_frame_btn.sizePolicy().hasHeightForWidth())
        self.facial_check_frame_btn.setSizePolicy(sizePolicy)
        self.facial_check_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.facial_check_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.facial_check_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.facial_check_frame_btn.setObjectName("facial_check_frame_btn")
        self.facial_check_frame_layout.addWidget(self.facial_check_frame_btn)
        self.facial_check_frame = QtWidgets.QFrame(self.facial_target_type_tool_frame)
        self.facial_check_frame.setObjectName("facial_check_frame")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.facial_check_frame)
        self.verticalLayout_33.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.eyebrow_check_frame_layout = QtWidgets.QVBoxLayout()
        self.eyebrow_check_frame_layout.setSpacing(0)
        self.eyebrow_check_frame_layout.setObjectName("eyebrow_check_frame_layout")
        self.eyebrow_check_frame_btn = QtWidgets.QToolButton(self.facial_check_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyebrow_check_frame_btn.sizePolicy().hasHeightForWidth())
        self.eyebrow_check_frame_btn.setSizePolicy(sizePolicy)
        self.eyebrow_check_frame_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.eyebrow_check_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.eyebrow_check_frame_btn.setAutoRepeat(False)
        self.eyebrow_check_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.eyebrow_check_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.eyebrow_check_frame_btn.setObjectName("eyebrow_check_frame_btn")
        self.eyebrow_check_frame_layout.addWidget(self.eyebrow_check_frame_btn)
        self.eyebrow_check_frame = QtWidgets.QFrame(self.facial_check_frame)
        self.eyebrow_check_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eyebrow_check_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eyebrow_check_frame.setObjectName("eyebrow_check_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.eyebrow_check_frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.eyebrow_check_top_layout = QtWidgets.QVBoxLayout()
        self.eyebrow_check_top_layout.setSpacing(0)
        self.eyebrow_check_top_layout.setObjectName("eyebrow_check_top_layout")
        self.verticalLayout_13.addLayout(self.eyebrow_check_top_layout)
        self.eyebrow_check_frame_line_1 = QtWidgets.QFrame(self.eyebrow_check_frame)
        self.eyebrow_check_frame_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.eyebrow_check_frame_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.eyebrow_check_frame_line_1.setObjectName("eyebrow_check_frame_line_1")
        self.verticalLayout_13.addWidget(self.eyebrow_check_frame_line_1)
        self.eyebrow_check_mid_layout = QtWidgets.QVBoxLayout()
        self.eyebrow_check_mid_layout.setSpacing(0)
        self.eyebrow_check_mid_layout.setObjectName("eyebrow_check_mid_layout")
        self.verticalLayout_13.addLayout(self.eyebrow_check_mid_layout)
        self.eyebrow_check_frame_line_2 = QtWidgets.QFrame(self.eyebrow_check_frame)
        self.eyebrow_check_frame_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.eyebrow_check_frame_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.eyebrow_check_frame_line_2.setObjectName("eyebrow_check_frame_line_2")
        self.verticalLayout_13.addWidget(self.eyebrow_check_frame_line_2)
        self.eyebrow_check_btm_layout = QtWidgets.QHBoxLayout()
        self.eyebrow_check_btm_layout.setSpacing(6)
        self.eyebrow_check_btm_layout.setObjectName("eyebrow_check_btm_layout")
        self.exec_prev_eyebrow_btn = QtWidgets.QPushButton(self.eyebrow_check_frame)
        self.exec_prev_eyebrow_btn.setObjectName("exec_prev_eyebrow_btn")
        self.eyebrow_check_btm_layout.addWidget(self.exec_prev_eyebrow_btn)
        self.exec_next_eyebrow_btn = QtWidgets.QPushButton(self.eyebrow_check_frame)
        self.exec_next_eyebrow_btn.setObjectName("exec_next_eyebrow_btn")
        self.eyebrow_check_btm_layout.addWidget(self.exec_next_eyebrow_btn)
        self.verticalLayout_13.addLayout(self.eyebrow_check_btm_layout)
        self.eyebrow_check_frame_layout.addWidget(self.eyebrow_check_frame)
        self.verticalLayout_33.addLayout(self.eyebrow_check_frame_layout)
        self.eye_check_frame_layout = QtWidgets.QVBoxLayout()
        self.eye_check_frame_layout.setSpacing(0)
        self.eye_check_frame_layout.setObjectName("eye_check_frame_layout")
        self.eye_check_frame_btn = QtWidgets.QToolButton(self.facial_check_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eye_check_frame_btn.sizePolicy().hasHeightForWidth())
        self.eye_check_frame_btn.setSizePolicy(sizePolicy)
        self.eye_check_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.eye_check_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.eye_check_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.eye_check_frame_btn.setObjectName("eye_check_frame_btn")
        self.eye_check_frame_layout.addWidget(self.eye_check_frame_btn)
        self.eye_check_frame = QtWidgets.QFrame(self.facial_check_frame)
        self.eye_check_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eye_check_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eye_check_frame.setObjectName("eye_check_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.eye_check_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.eye_check_top_layout = QtWidgets.QVBoxLayout()
        self.eye_check_top_layout.setSpacing(0)
        self.eye_check_top_layout.setObjectName("eye_check_top_layout")
        self.verticalLayout_4.addLayout(self.eye_check_top_layout)
        self.eye_check_frame_line_1 = QtWidgets.QFrame(self.eye_check_frame)
        self.eye_check_frame_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.eye_check_frame_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.eye_check_frame_line_1.setObjectName("eye_check_frame_line_1")
        self.verticalLayout_4.addWidget(self.eye_check_frame_line_1)
        self.eye_check_mid_layout = QtWidgets.QVBoxLayout()
        self.eye_check_mid_layout.setSpacing(0)
        self.eye_check_mid_layout.setObjectName("eye_check_mid_layout")
        self.verticalLayout_4.addLayout(self.eye_check_mid_layout)
        self.eye_check_frame_line_2 = QtWidgets.QFrame(self.eye_check_frame)
        self.eye_check_frame_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.eye_check_frame_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.eye_check_frame_line_2.setObjectName("eye_check_frame_line_2")
        self.verticalLayout_4.addWidget(self.eye_check_frame_line_2)
        self.eye_check_btm_layout = QtWidgets.QHBoxLayout()
        self.eye_check_btm_layout.setObjectName("eye_check_btm_layout")
        self.exec_prev_eye_btn = QtWidgets.QPushButton(self.eye_check_frame)
        self.exec_prev_eye_btn.setObjectName("exec_prev_eye_btn")
        self.eye_check_btm_layout.addWidget(self.exec_prev_eye_btn)
        self.exec_next_eye_btn = QtWidgets.QPushButton(self.eye_check_frame)
        self.exec_next_eye_btn.setObjectName("exec_next_eye_btn")
        self.eye_check_btm_layout.addWidget(self.exec_next_eye_btn)
        self.verticalLayout_4.addLayout(self.eye_check_btm_layout)
        self.eye_check_frame_layout.addWidget(self.eye_check_frame)
        self.verticalLayout_33.addLayout(self.eye_check_frame_layout)
        self.mouth_check_frame_layout = QtWidgets.QVBoxLayout()
        self.mouth_check_frame_layout.setSpacing(0)
        self.mouth_check_frame_layout.setObjectName("mouth_check_frame_layout")
        self.mouth_check_frame_btn = QtWidgets.QToolButton(self.facial_check_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mouth_check_frame_btn.sizePolicy().hasHeightForWidth())
        self.mouth_check_frame_btn.setSizePolicy(sizePolicy)
        self.mouth_check_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.mouth_check_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mouth_check_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.mouth_check_frame_btn.setObjectName("mouth_check_frame_btn")
        self.mouth_check_frame_layout.addWidget(self.mouth_check_frame_btn)
        self.mouth_check_frame = QtWidgets.QFrame(self.facial_check_frame)
        self.mouth_check_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.mouth_check_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mouth_check_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mouth_check_frame.setObjectName("mouth_check_frame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.mouth_check_frame)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.mouth_check_top_layout = QtWidgets.QVBoxLayout()
        self.mouth_check_top_layout.setSpacing(0)
        self.mouth_check_top_layout.setObjectName("mouth_check_top_layout")
        self.verticalLayout_18.addLayout(self.mouth_check_top_layout)
        self.mouth_check_frame_line_1 = QtWidgets.QFrame(self.mouth_check_frame)
        self.mouth_check_frame_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.mouth_check_frame_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mouth_check_frame_line_1.setObjectName("mouth_check_frame_line_1")
        self.verticalLayout_18.addWidget(self.mouth_check_frame_line_1)
        self.mouth_check_mid_layout = QtWidgets.QVBoxLayout()
        self.mouth_check_mid_layout.setSpacing(0)
        self.mouth_check_mid_layout.setObjectName("mouth_check_mid_layout")
        self.verticalLayout_18.addLayout(self.mouth_check_mid_layout)
        self.mouth_check_frame_line_2 = QtWidgets.QFrame(self.mouth_check_frame)
        self.mouth_check_frame_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.mouth_check_frame_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mouth_check_frame_line_2.setObjectName("mouth_check_frame_line_2")
        self.verticalLayout_18.addWidget(self.mouth_check_frame_line_2)
        self.mouth_check_btm_layout = QtWidgets.QHBoxLayout()
        self.mouth_check_btm_layout.setObjectName("mouth_check_btm_layout")
        self.exec_prev_mouth_btn = QtWidgets.QPushButton(self.mouth_check_frame)
        self.exec_prev_mouth_btn.setObjectName("exec_prev_mouth_btn")
        self.mouth_check_btm_layout.addWidget(self.exec_prev_mouth_btn)
        self.exec_next_mouth_btn = QtWidgets.QPushButton(self.mouth_check_frame)
        self.exec_next_mouth_btn.setObjectName("exec_next_mouth_btn")
        self.mouth_check_btm_layout.addWidget(self.exec_next_mouth_btn)
        self.verticalLayout_18.addLayout(self.mouth_check_btm_layout)
        self.mouth_check_frame_layout.addWidget(self.mouth_check_frame)
        self.verticalLayout_33.addLayout(self.mouth_check_frame_layout)
        self.exec_reset_animation_layer_btn = QtWidgets.QPushButton(self.facial_check_frame)
        self.exec_reset_animation_layer_btn.setObjectName("exec_reset_animation_layer_btn")
        self.verticalLayout_33.addWidget(self.exec_reset_animation_layer_btn)
        self.exec_back_facial_btn = QtWidgets.QPushButton(self.facial_check_frame)
        self.exec_back_facial_btn.setObjectName("exec_back_facial_btn")
        self.verticalLayout_33.addWidget(self.exec_back_facial_btn)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.exec_all_prev_facial_btn = QtWidgets.QPushButton(self.facial_check_frame)
        self.exec_all_prev_facial_btn.setObjectName("exec_all_prev_facial_btn")
        self.horizontalLayout_16.addWidget(self.exec_all_prev_facial_btn)
        self.exec_all_next_facial_btn = QtWidgets.QPushButton(self.facial_check_frame)
        self.exec_all_next_facial_btn.setObjectName("exec_all_next_facial_btn")
        self.horizontalLayout_16.addWidget(self.exec_all_next_facial_btn)
        self.verticalLayout_33.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.prev_facial_list_label = QtWidgets.QLabel(self.facial_check_frame)
        self.prev_facial_list_label.setObjectName("prev_facial_list_label")
        self.horizontalLayout_22.addWidget(self.prev_facial_list_label)
        self.prev_facial_list_count_label = QtWidgets.QLabel(self.facial_check_frame)
        self.prev_facial_list_count_label.setObjectName("prev_facial_list_count_label")
        self.horizontalLayout_22.addWidget(self.prev_facial_list_count_label)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_22)
        self.prev_facial_list_edit = QtWidgets.QPlainTextEdit(self.facial_check_frame)
        self.prev_facial_list_edit.setObjectName("prev_facial_list_edit")
        self.verticalLayout_19.addWidget(self.prev_facial_list_edit)
        self.horizontalLayout_17.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.next_facial_list_label = QtWidgets.QLabel(self.facial_check_frame)
        self.next_facial_list_label.setObjectName("next_facial_list_label")
        self.horizontalLayout_23.addWidget(self.next_facial_list_label)
        self.now_facial_list_count_label = QtWidgets.QLabel(self.facial_check_frame)
        self.now_facial_list_count_label.setObjectName("now_facial_list_count_label")
        self.horizontalLayout_23.addWidget(self.now_facial_list_count_label)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 2)
        self.verticalLayout_20.addLayout(self.horizontalLayout_23)
        self.now_facial_list_edit = QtWidgets.QPlainTextEdit(self.facial_check_frame)
        self.now_facial_list_edit.setObjectName("now_facial_list_edit")
        self.verticalLayout_20.addWidget(self.now_facial_list_edit)
        self.horizontalLayout_17.addLayout(self.verticalLayout_20)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 1)
        self.verticalLayout_33.addLayout(self.horizontalLayout_17)
        self.facial_check_frame_layout.addWidget(self.facial_check_frame)
        self.verticalLayout_8.addLayout(self.facial_check_frame_layout)
        self.export_facial_target_frame_layout = QtWidgets.QVBoxLayout()
        self.export_facial_target_frame_layout.setSpacing(0)
        self.export_facial_target_frame_layout.setObjectName("export_facial_target_frame_layout")
        self.export_facial_target_frame_btn = QtWidgets.QToolButton(self.facial_target_type_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_facial_target_frame_btn.sizePolicy().hasHeightForWidth())
        self.export_facial_target_frame_btn.setSizePolicy(sizePolicy)
        self.export_facial_target_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.export_facial_target_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.export_facial_target_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.export_facial_target_frame_btn.setObjectName("export_facial_target_frame_btn")
        self.export_facial_target_frame_layout.addWidget(self.export_facial_target_frame_btn)
        self.export_facial_target_frame = QtWidgets.QFrame(self.facial_target_type_tool_frame)
        self.export_facial_target_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.export_facial_target_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_facial_target_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_facial_target_frame.setObjectName("export_facial_target_frame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.export_facial_target_frame)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.exec_export_facial_target_btn = QtWidgets.QPushButton(self.export_facial_target_frame)
        self.exec_export_facial_target_btn.setObjectName("exec_export_facial_target_btn")
        self.verticalLayout_15.addWidget(self.exec_export_facial_target_btn)
        self.export_facial_target_frame_layout.addWidget(self.export_facial_target_frame)
        self.verticalLayout_8.addLayout(self.export_facial_target_frame_layout)
        self.facial_target_type_tool_frame_layout.addWidget(self.facial_target_type_tool_frame)
        self.verticalLayout.addLayout(self.facial_target_type_tool_frame_layout)
        self.ear_target_type_too_frame_layout = QtWidgets.QVBoxLayout()
        self.ear_target_type_too_frame_layout.setSpacing(0)
        self.ear_target_type_too_frame_layout.setObjectName("ear_target_type_too_frame_layout")
        self.ear_target_type_tool_frame_btn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ear_target_type_tool_frame_btn.sizePolicy().hasHeightForWidth())
        self.ear_target_type_tool_frame_btn.setSizePolicy(sizePolicy)
        self.ear_target_type_tool_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.ear_target_type_tool_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ear_target_type_tool_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.ear_target_type_tool_frame_btn.setObjectName("ear_target_type_tool_frame_btn")
        self.ear_target_type_too_frame_layout.addWidget(self.ear_target_type_tool_frame_btn)
        self.ear_target_type_tool_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.ear_target_type_tool_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.ear_target_type_tool_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ear_target_type_tool_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ear_target_type_tool_frame.setObjectName("ear_target_type_tool_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ear_target_type_tool_frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ear_target_check_frame_layout = QtWidgets.QVBoxLayout()
        self.ear_target_check_frame_layout.setSpacing(0)
        self.ear_target_check_frame_layout.setContentsMargins(0, 0, 0, 0)
        self.ear_target_check_frame_layout.setObjectName("ear_target_check_frame_layout")
        self.ear_target_check_frame_btn = QtWidgets.QToolButton(self.ear_target_type_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ear_target_check_frame_btn.sizePolicy().hasHeightForWidth())
        self.ear_target_check_frame_btn.setSizePolicy(sizePolicy)
        self.ear_target_check_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.ear_target_check_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ear_target_check_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.ear_target_check_frame_btn.setObjectName("ear_target_check_frame_btn")
        self.ear_target_check_frame_layout.addWidget(self.ear_target_check_frame_btn)
        self.ear_target_check_frame = QtWidgets.QFrame(self.ear_target_type_tool_frame)
        self.ear_target_check_frame.setObjectName("ear_target_check_frame")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.ear_target_check_frame)
        self.verticalLayout_34.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.ear_check_frame_layout = QtWidgets.QVBoxLayout()
        self.ear_check_frame_layout.setSpacing(0)
        self.ear_check_frame_layout.setObjectName("ear_check_frame_layout")
        self.ear_check_frame_btn = QtWidgets.QToolButton(self.ear_target_check_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ear_check_frame_btn.sizePolicy().hasHeightForWidth())
        self.ear_check_frame_btn.setSizePolicy(sizePolicy)
        self.ear_check_frame_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ear_check_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.ear_check_frame_btn.setAutoRepeat(False)
        self.ear_check_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ear_check_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.ear_check_frame_btn.setObjectName("ear_check_frame_btn")
        self.ear_check_frame_layout.addWidget(self.ear_check_frame_btn)
        self.ear_check_frame = QtWidgets.QFrame(self.ear_target_check_frame)
        self.ear_check_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ear_check_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ear_check_frame.setObjectName("ear_check_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ear_check_frame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.ear_check_top_layout = QtWidgets.QVBoxLayout()
        self.ear_check_top_layout.setSpacing(0)
        self.ear_check_top_layout.setObjectName("ear_check_top_layout")
        self.verticalLayout_14.addLayout(self.ear_check_top_layout)
        self.ear_check_frame_line_1 = QtWidgets.QFrame(self.ear_check_frame)
        self.ear_check_frame_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.ear_check_frame_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ear_check_frame_line_1.setObjectName("ear_check_frame_line_1")
        self.verticalLayout_14.addWidget(self.ear_check_frame_line_1)
        self.ear_check_mid_layout = QtWidgets.QVBoxLayout()
        self.ear_check_mid_layout.setSpacing(0)
        self.ear_check_mid_layout.setObjectName("ear_check_mid_layout")
        self.verticalLayout_14.addLayout(self.ear_check_mid_layout)
        self.ear_check_frame_line_2 = QtWidgets.QFrame(self.ear_check_frame)
        self.ear_check_frame_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.ear_check_frame_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ear_check_frame_line_2.setObjectName("ear_check_frame_line_2")
        self.verticalLayout_14.addWidget(self.ear_check_frame_line_2)
        self.ear_check_btm_layout = QtWidgets.QHBoxLayout()
        self.ear_check_btm_layout.setSpacing(6)
        self.ear_check_btm_layout.setObjectName("ear_check_btm_layout")
        self.exec_prev_ear_btn = QtWidgets.QPushButton(self.ear_check_frame)
        self.exec_prev_ear_btn.setObjectName("exec_prev_ear_btn")
        self.ear_check_btm_layout.addWidget(self.exec_prev_ear_btn)
        self.exec_next_ear_btn = QtWidgets.QPushButton(self.ear_check_frame)
        self.exec_next_ear_btn.setObjectName("exec_next_ear_btn")
        self.ear_check_btm_layout.addWidget(self.exec_next_ear_btn)
        self.verticalLayout_14.addLayout(self.ear_check_btm_layout)
        self.ear_check_frame_layout.addWidget(self.ear_check_frame)
        self.verticalLayout_34.addLayout(self.ear_check_frame_layout)
        self.exec_reset_ear_animation_layer_btn = QtWidgets.QPushButton(self.ear_target_check_frame)
        self.exec_reset_ear_animation_layer_btn.setObjectName("exec_reset_ear_animation_layer_btn")
        self.verticalLayout_34.addWidget(self.exec_reset_ear_animation_layer_btn)
        self.exec_back_ear_btn = QtWidgets.QPushButton(self.ear_target_check_frame)
        self.exec_back_ear_btn.setObjectName("exec_back_ear_btn")
        self.verticalLayout_34.addWidget(self.exec_back_ear_btn)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.exec_all_prev_ear_btn = QtWidgets.QPushButton(self.ear_target_check_frame)
        self.exec_all_prev_ear_btn.setObjectName("exec_all_prev_ear_btn")
        self.horizontalLayout_19.addWidget(self.exec_all_prev_ear_btn)
        self.exec_all_next_ear_btn = QtWidgets.QPushButton(self.ear_target_check_frame)
        self.exec_all_next_ear_btn.setObjectName("exec_all_next_ear_btn")
        self.horizontalLayout_19.addWidget(self.exec_all_next_ear_btn)
        self.verticalLayout_34.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.prev_ear_list_label = QtWidgets.QLabel(self.ear_target_check_frame)
        self.prev_ear_list_label.setObjectName("prev_ear_list_label")
        self.horizontalLayout_24.addWidget(self.prev_ear_list_label)
        self.prev_ear_list_count_label = QtWidgets.QLabel(self.ear_target_check_frame)
        self.prev_ear_list_count_label.setObjectName("prev_ear_list_count_label")
        self.horizontalLayout_24.addWidget(self.prev_ear_list_count_label)
        self.horizontalLayout_24.setStretch(0, 1)
        self.horizontalLayout_24.setStretch(1, 2)
        self.verticalLayout_23.addLayout(self.horizontalLayout_24)
        self.prev_ear_list_edit = QtWidgets.QPlainTextEdit(self.ear_target_check_frame)
        self.prev_ear_list_edit.setObjectName("prev_ear_list_edit")
        self.verticalLayout_23.addWidget(self.prev_ear_list_edit)
        self.horizontalLayout_20.addLayout(self.verticalLayout_23)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.next_facial_list_label_2 = QtWidgets.QLabel(self.ear_target_check_frame)
        self.next_facial_list_label_2.setObjectName("next_facial_list_label_2")
        self.horizontalLayout_25.addWidget(self.next_facial_list_label_2)
        self.now_ear_list_count_label = QtWidgets.QLabel(self.ear_target_check_frame)
        self.now_ear_list_count_label.setObjectName("now_ear_list_count_label")
        self.horizontalLayout_25.addWidget(self.now_ear_list_count_label)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_25)
        self.now_ear_list_edit = QtWidgets.QPlainTextEdit(self.ear_target_check_frame)
        self.now_ear_list_edit.setObjectName("now_ear_list_edit")
        self.verticalLayout_25.addWidget(self.now_ear_list_edit)
        self.horizontalLayout_20.addLayout(self.verticalLayout_25)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 1)
        self.verticalLayout_34.addLayout(self.horizontalLayout_20)
        self.ear_target_check_frame_layout.addWidget(self.ear_target_check_frame)
        self.verticalLayout_11.addLayout(self.ear_target_check_frame_layout)
        self.export_ear_target_frame_layout = QtWidgets.QVBoxLayout()
        self.export_ear_target_frame_layout.setSpacing(0)
        self.export_ear_target_frame_layout.setObjectName("export_ear_target_frame_layout")
        self.export_ear_target_frame_btn = QtWidgets.QToolButton(self.ear_target_type_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_ear_target_frame_btn.sizePolicy().hasHeightForWidth())
        self.export_ear_target_frame_btn.setSizePolicy(sizePolicy)
        self.export_ear_target_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.export_ear_target_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.export_ear_target_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.export_ear_target_frame_btn.setObjectName("export_ear_target_frame_btn")
        self.export_ear_target_frame_layout.addWidget(self.export_ear_target_frame_btn)
        self.export_ear_target_frame = QtWidgets.QFrame(self.ear_target_type_tool_frame)
        self.export_ear_target_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.export_ear_target_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_ear_target_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_ear_target_frame.setObjectName("export_ear_target_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.export_ear_target_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.exec_export_ear_target_btn = QtWidgets.QPushButton(self.export_ear_target_frame)
        self.exec_export_ear_target_btn.setObjectName("exec_export_ear_target_btn")
        self.verticalLayout_7.addWidget(self.exec_export_ear_target_btn)
        self.export_ear_target_frame_layout.addWidget(self.export_ear_target_frame)
        self.verticalLayout_11.addLayout(self.export_ear_target_frame_layout)
        self.ear_target_type_too_frame_layout.addWidget(self.ear_target_type_tool_frame)
        self.verticalLayout.addLayout(self.ear_target_type_too_frame_layout)
        self.export_facial_blend_target_frame_layout = QtWidgets.QVBoxLayout()
        self.export_facial_blend_target_frame_layout.setSpacing(0)
        self.export_facial_blend_target_frame_layout.setObjectName("export_facial_blend_target_frame_layout")
        self.export_facial_blend_target_frame_btn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_facial_blend_target_frame_btn.sizePolicy().hasHeightForWidth())
        self.export_facial_blend_target_frame_btn.setSizePolicy(sizePolicy)
        self.export_facial_blend_target_frame_btn.setIconSize(QtCore.QSize(4, 4))
        self.export_facial_blend_target_frame_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.export_facial_blend_target_frame_btn.setArrowType(QtCore.Qt.DownArrow)
        self.export_facial_blend_target_frame_btn.setObjectName("export_facial_blend_target_frame_btn")
        self.export_facial_blend_target_frame_layout.addWidget(self.export_facial_blend_target_frame_btn)
        self.export_facial_blend_target_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.export_facial_blend_target_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.export_facial_blend_target_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.export_facial_blend_target_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.export_facial_blend_target_frame.setObjectName("export_facial_blend_target_frame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.export_facial_blend_target_frame)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.exec_export_facial_blend_target_btn = QtWidgets.QPushButton(self.export_facial_blend_target_frame)
        self.exec_export_facial_blend_target_btn.setObjectName("exec_export_facial_blend_target_btn")
        self.verticalLayout_17.addWidget(self.exec_export_facial_blend_target_btn)
        self.export_facial_blend_target_frame_layout.addWidget(self.export_facial_blend_target_frame)
        self.verticalLayout.addLayout(self.export_facial_blend_target_frame_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(3, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_21.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.facial_target_type_tool_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "フェイシャルターゲット系ツール", None, -1))
        self.edit_rig_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "リグ編集ツール", None, -1))
        self.exec_attach_head_rig_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Head_rigのジョイントのアタッチ", None, -1))
        self.exec_detach_head_rig_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Head_rigのジョイントのデタッチ", None, -1))
        self.exec_reset_head_rig_controller_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Head_rigのコントローラーのリセット", None, -1))
        self.exec_edit_eye_highlight_rig_btn.setText(QtWidgets.QApplication.translate("MainWindow", "目のハイライトリグを作成・更新", None, -1))
        self.facial_check_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "確認ツール", None, -1))
        self.eyebrow_check_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "眉", None, -1))
        self.exec_prev_eyebrow_btn.setText(QtWidgets.QApplication.translate("MainWindow", "前の表情", None, -1))
        self.exec_next_eyebrow_btn.setText(QtWidgets.QApplication.translate("MainWindow", "次の表情", None, -1))
        self.eye_check_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "目", None, -1))
        self.exec_prev_eye_btn.setText(QtWidgets.QApplication.translate("MainWindow", "前の表情", None, -1))
        self.exec_next_eye_btn.setText(QtWidgets.QApplication.translate("MainWindow", "次の表情", None, -1))
        self.mouth_check_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "口", None, -1))
        self.exec_prev_mouth_btn.setText(QtWidgets.QApplication.translate("MainWindow", "前の表情", None, -1))
        self.exec_next_mouth_btn.setText(QtWidgets.QApplication.translate("MainWindow", "次の表情", None, -1))
        self.exec_reset_animation_layer_btn.setText(QtWidgets.QApplication.translate("MainWindow", "アニメーションレイヤーをリセットする", None, -1))
        self.exec_back_facial_btn.setText(QtWidgets.QApplication.translate("MainWindow", "1つ前の表情に戻る", None, -1))
        self.exec_all_prev_facial_btn.setText(QtWidgets.QApplication.translate("MainWindow", "全戻し", None, -1))
        self.exec_all_next_facial_btn.setText(QtWidgets.QApplication.translate("MainWindow", "全送り", None, -1))
        self.prev_facial_list_label.setText(QtWidgets.QApplication.translate("MainWindow", "一つ前の表情", None, -1))
        self.prev_facial_list_count_label.setText(QtWidgets.QApplication.translate("MainWindow", "Frame(0)", None, -1))
        self.next_facial_list_label.setText(QtWidgets.QApplication.translate("MainWindow", "現在の表情", None, -1))
        self.now_facial_list_count_label.setText(QtWidgets.QApplication.translate("MainWindow", "Frame(0)", None, -1))
        self.export_facial_target_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "facial_targetの出力", None, -1))
        self.exec_export_facial_target_btn.setText(QtWidgets.QApplication.translate("MainWindow", "_facial_target.fbxを出力", None, -1))
        self.ear_target_type_tool_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "耳ターゲット系ツール", None, -1))
        self.ear_target_check_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "確認ツール", None, -1))
        self.ear_check_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "耳", None, -1))
        self.exec_prev_ear_btn.setText(QtWidgets.QApplication.translate("MainWindow", "前の表情", None, -1))
        self.exec_next_ear_btn.setText(QtWidgets.QApplication.translate("MainWindow", "次の表情", None, -1))
        self.exec_reset_ear_animation_layer_btn.setText(QtWidgets.QApplication.translate("MainWindow", "アニメーションレイヤーをリセットする", None, -1))
        self.exec_back_ear_btn.setText(QtWidgets.QApplication.translate("MainWindow", "1つ前の表情に戻る", None, -1))
        self.exec_all_prev_ear_btn.setText(QtWidgets.QApplication.translate("MainWindow", "全戻し", None, -1))
        self.exec_all_next_ear_btn.setText(QtWidgets.QApplication.translate("MainWindow", "全送り", None, -1))
        self.prev_ear_list_label.setText(QtWidgets.QApplication.translate("MainWindow", "一つ前の表情", None, -1))
        self.prev_ear_list_count_label.setText(QtWidgets.QApplication.translate("MainWindow", "Frame(0)", None, -1))
        self.next_facial_list_label_2.setText(QtWidgets.QApplication.translate("MainWindow", "現在の表情", None, -1))
        self.now_ear_list_count_label.setText(QtWidgets.QApplication.translate("MainWindow", "Frame(0)", None, -1))
        self.export_ear_target_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "ear_target.fbxの出力", None, -1))
        self.exec_export_ear_target_btn.setText(QtWidgets.QApplication.translate("MainWindow", "ear_target.fbxの出力", None, -1))
        self.export_facial_blend_target_frame_btn.setText(QtWidgets.QApplication.translate("MainWindow", "facial_blend_target.ma/fbxの作成", None, -1))
        self.exec_export_facial_blend_target_btn.setText(QtWidgets.QApplication.translate("MainWindow", "_facial_blend_target.ma/fbxの作成", None, -1))

