# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_tp_expression\ui\item_widget.ui'
#
# Created: Tue Jan  9 16:20:26 2024
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 192)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enable_label_frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enable_label_frame.sizePolicy().hasHeightForWidth())
        self.enable_label_frame.setSizePolicy(sizePolicy)
        self.enable_label_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.enable_label_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.enable_label_frame.setObjectName("enable_label_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.enable_label_frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.enable_check = QtWidgets.QCheckBox(self.enable_label_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enable_check.sizePolicy().hasHeightForWidth())
        self.enable_check.setSizePolicy(sizePolicy)
        self.enable_check.setText("")
        self.enable_check.setObjectName("enable_check")
        self.verticalLayout_5.addWidget(self.enable_check)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.enable_label_frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_button.sizePolicy().hasHeightForWidth())
        self.frame_button.setSizePolicy(sizePolicy)
        self.frame_button.setStyleSheet("background-color: rgb(93, 93, 93);")
        self.frame_button.setFlat(True)
        self.frame_button.setObjectName("frame_button")
        self.horizontalLayout_2.addWidget(self.frame_button)
        self.del_item_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_item_button.sizePolicy().hasHeightForWidth())
        self.del_item_button.setSizePolicy(sizePolicy)
        self.del_item_button.setObjectName("del_item_button")
        self.horizontalLayout_2.addWidget(self.del_item_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame_group = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_group.sizePolicy().hasHeightForWidth())
        self.frame_group.setSizePolicy(sizePolicy)
        self.frame_group.setTitle("")
        self.frame_group.setFlat(False)
        self.frame_group.setObjectName("frame_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_group)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.expression_combo = QtWidgets.QComboBox(self.frame_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expression_combo.sizePolicy().hasHeightForWidth())
        self.expression_combo.setSizePolicy(sizePolicy)
        self.expression_combo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.expression_combo.setObjectName("expression_combo")
        self.verticalLayout_3.addWidget(self.expression_combo)
        self.expression_layout = QtWidgets.QVBoxLayout()
        self.expression_layout.setObjectName("expression_layout")
        self.verticalLayout_3.addLayout(self.expression_layout)
        self.verticalLayout.addWidget(self.frame_group)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.frame_button.setText(QtWidgets.QApplication.translate("Form", "PushButton", None, -1))
        self.del_item_button.setText(QtWidgets.QApplication.translate("Form", "削除", None, -1))

