//===============================================
//
// FBX èoóÕ
//
// Fujita Yukihiro
//
//===============================================

global proc shr_exportFbx_UI()
{
    if(`workspaceControl -ex uWsc_shr_exportFbx`)
    {
        return;
        // workspaceControl -e -close uWsc_shr_exportFbx;
    }

    workspaceControl
        -retain false
        -iw 200
        -ih 300
        -uiScript "shr_exportFbx();"
        -label "Environment Exporter"
        uWsc_shr_exportFbx;
}

