# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CyDesignerTools_Legacy\Maya\scripts\Project_Gallop\glp_dirt_psd_maker\ui\dirtPSDMakerWindow.ui'
#
# Created: Fri Jun 11 16:33:43 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 246)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 403, 234))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mainVLO = QtWidgets.QVBoxLayout()
        self.mainVLO.setObjectName("mainVLO")
        self.loadDirtRefGrp = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.loadDirtRefGrp.setFont(font)
        self.loadDirtRefGrp.setObjectName("loadDirtRefGrp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.loadDirtRefGrp)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.loadDirtRefVLO = QtWidgets.QVBoxLayout()
        self.loadDirtRefVLO.setContentsMargins(5, 5, 5, 5)
        self.loadDirtRefVLO.setObjectName("loadDirtRefVLO")
        self.loadDirtRefEditHLO = QtWidgets.QHBoxLayout()
        self.loadDirtRefEditHLO.setSpacing(2)
        self.loadDirtRefEditHLO.setObjectName("loadDirtRefEditHLO")
        self.loadDirtRefEditLabel = QtWidgets.QLabel(self.loadDirtRefGrp)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.loadDirtRefEditLabel.setFont(font)
        self.loadDirtRefEditLabel.setObjectName("loadDirtRefEditLabel")
        self.loadDirtRefEditHLO.addWidget(self.loadDirtRefEditLabel)
        self.loadDirtRefEditLE = QtWidgets.QLineEdit(self.loadDirtRefGrp)
        self.loadDirtRefEditLE.setObjectName("loadDirtRefEditLE")
        self.loadDirtRefEditHLO.addWidget(self.loadDirtRefEditLE)
        self.loadDirtRefEditSelectBtn = QtWidgets.QPushButton(self.loadDirtRefGrp)
        self.loadDirtRefEditSelectBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadDirtRefEditSelectBtn.sizePolicy().hasHeightForWidth())
        self.loadDirtRefEditSelectBtn.setSizePolicy(sizePolicy)
        self.loadDirtRefEditSelectBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.loadDirtRefEditSelectBtn.setFont(font)
        self.loadDirtRefEditSelectBtn.setObjectName("loadDirtRefEditSelectBtn")
        self.loadDirtRefEditHLO.addWidget(self.loadDirtRefEditSelectBtn)
        self.loadDirtRefEditOpenBtn = QtWidgets.QPushButton(self.loadDirtRefGrp)
        self.loadDirtRefEditOpenBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.loadDirtRefEditOpenBtn.setFont(font)
        self.loadDirtRefEditOpenBtn.setObjectName("loadDirtRefEditOpenBtn")
        self.loadDirtRefEditHLO.addWidget(self.loadDirtRefEditOpenBtn)
        self.loadDirtRefEditCheckBtn = QtWidgets.QPushButton(self.loadDirtRefGrp)
        self.loadDirtRefEditCheckBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.loadDirtRefEditCheckBtn.setFont(font)
        self.loadDirtRefEditCheckBtn.setObjectName("loadDirtRefEditCheckBtn")
        self.loadDirtRefEditHLO.addWidget(self.loadDirtRefEditCheckBtn)
        self.loadDirtRefVLO.addLayout(self.loadDirtRefEditHLO)
        self.loadDirtRefLoadBtn = QtWidgets.QPushButton(self.loadDirtRefGrp)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.loadDirtRefLoadBtn.setFont(font)
        self.loadDirtRefLoadBtn.setObjectName("loadDirtRefLoadBtn")
        self.loadDirtRefVLO.addWidget(self.loadDirtRefLoadBtn)
        self.gridLayout_3.addLayout(self.loadDirtRefVLO, 0, 0, 1, 1)
        self.mainVLO.addWidget(self.loadDirtRefGrp)
        self.transcriptDirtGrp = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.transcriptDirtGrp.setFont(font)
        self.transcriptDirtGrp.setObjectName("transcriptDirtGrp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.transcriptDirtGrp)
        self.gridLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.transcriptDirtBtn = QtWidgets.QPushButton(self.transcriptDirtGrp)
        self.transcriptDirtBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.transcriptDirtBtn.setFont(font)
        self.transcriptDirtBtn.setObjectName("transcriptDirtBtn")
        self.gridLayout_2.addWidget(self.transcriptDirtBtn, 0, 0, 1, 1)
        self.mainVLO.addWidget(self.transcriptDirtGrp)
        self.gridLayout_4.addLayout(self.mainVLO, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "GallopDirtMaker", None, -1))
        self.loadDirtRefGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Dirtリファレンスの読み込み", None, -1))
        self.loadDirtRefEditLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Dirtリファレンス", None, -1))
        self.loadDirtRefEditSelectBtn.setText(QtWidgets.QApplication.translate("MainWindow", "選択", None, -1))
        self.loadDirtRefEditOpenBtn.setText(QtWidgets.QApplication.translate("MainWindow", "開く", None, -1))
        self.loadDirtRefEditCheckBtn.setText(QtWidgets.QApplication.translate("MainWindow", "チェック", None, -1))
        self.loadDirtRefLoadBtn.setText(QtWidgets.QApplication.translate("MainWindow", "リファレンス読み込み", None, -1))
        self.transcriptDirtGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Dirtの転写", None, -1))
        self.transcriptDirtBtn.setText(QtWidgets.QApplication.translate("MainWindow", "同名メッシュにDirtを転写、PSD作成", None, -1))

