# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'z:\mtk\tools\maya\modules\mtku\scripts\mtku\maya\menus\cutscene\camerasequencer_camera_creator\ui\CreateCameraOption.ui'
#
# Created: Thu Jul  8 10:54:59 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 260)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(130, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cameraGroup = QtWidgets.QLineEdit(self.centralwidget)
        self.cameraGroup.setObjectName("cameraGroup")
        self.horizontalLayout_2.addWidget(self.cameraGroup)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.shotName = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotName.sizePolicy().hasHeightForWidth())
        self.shotName.setSizePolicy(sizePolicy)
        self.shotName.setObjectName("shotName")
        self.horizontalLayout_6.addWidget(self.shotName)
        self.shotNumber = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotNumber.sizePolicy().hasHeightForWidth())
        self.shotNumber.setSizePolicy(sizePolicy)
        self.shotNumber.setMinimumSize(QtCore.QSize(0, 0))
        self.shotNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.shotNumber.setObjectName("shotNumber")
        self.horizontalLayout_6.addWidget(self.shotNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.previewText = QtWidgets.QLabel(self.centralwidget)
        self.previewText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.previewText.setObjectName("previewText")
        self.horizontalLayout_4.addWidget(self.previewText)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(130, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.shotPlacement = QtWidgets.QComboBox(self.centralwidget)
        self.shotPlacement.setObjectName("shotPlacement")
        self.shotPlacement.addItem("")
        self.shotPlacement.addItem("")
        self.shotPlacement.addItem("")
        self.horizontalLayout_5.addWidget(self.shotPlacement)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.cameraType = QtWidgets.QComboBox(self.centralwidget)
        self.cameraType.setObjectName("cameraType")
        self.cameraType.addItem("")
        self.cameraType.addItem("")
        self.cameraType.addItem("")
        self.horizontalLayout_3.addWidget(self.cameraType)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(130, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.startTime = QtWidgets.QSpinBox(self.centralwidget)
        self.startTime.setMinimumSize(QtCore.QSize(50, 0))
        self.startTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.startTime.setObjectName("startTime")
        self.horizontalLayout_7.addWidget(self.startTime)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(130, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.endTime = QtWidgets.QSpinBox(self.centralwidget)
        self.endTime.setMinimumSize(QtCore.QSize(50, 0))
        self.endTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.endTime.setMaximum(9999)
        self.endTime.setProperty("value", 100)
        self.endTime.setObjectName("endTime")
        self.horizontalLayout_8.addWidget(self.endTime)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.createCameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.createCameraButton.setObjectName("createCameraButton")
        self.horizontalLayout.addWidget(self.createCameraButton)
        self.applyButton = QtWidgets.QPushButton(self.centralwidget)
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 345, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Create Camera Options", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Camera GroupName", None, -1))
        self.cameraGroup.setText(QtWidgets.QApplication.translate("MainWindow", "CameraGroup", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Shot Name", None, -1))
        self.shotName.setText(QtWidgets.QApplication.translate("MainWindow", "Cut_", None, -1))
        self.shotNumber.setText(QtWidgets.QApplication.translate("MainWindow", "001", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "(プレビュー：", None, -1))
        self.previewText.setText(QtWidgets.QApplication.translate("MainWindow", "Cut_001", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", ")", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "New Shot Placement", None, -1))
        self.shotPlacement.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.shotPlacement.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "CurrentFrame", None, -1))
        self.shotPlacement.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "EndFrame", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "CameraType", None, -1))
        self.cameraType.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Normal", None, -1))
        self.cameraType.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Aim", None, -1))
        self.cameraType.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "AimAndUp", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Start time", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "End time", None, -1))
        self.createCameraButton.setText(QtWidgets.QApplication.translate("MainWindow", "Create Camera", None, -1))
        self.applyButton.setText(QtWidgets.QApplication.translate("MainWindow", "Apply", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))

