# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'z:\mtk\tools\maya\modules\mtku\scripts\mtku\maya\menus\cutscene\camerasequencer_playblast\ui\playblastOption.ui'
#
# Created: Wed Jul 21 15:35:50 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.directory = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directory.sizePolicy().hasHeightForWidth())
        self.directory.setSizePolicy(sizePolicy)
        self.directory.setMinimumSize(QtCore.QSize(0, 22))
        self.directory.setReadOnly(True)
        self.directory.setObjectName("directory")
        self.horizontalLayout_7.addWidget(self.directory)
        self.openFolderButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFolderButton.sizePolicy().hasHeightForWidth())
        self.openFolderButton.setSizePolicy(sizePolicy)
        self.openFolderButton.setMinimumSize(QtCore.QSize(0, 0))
        self.openFolderButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.openFolderButton.setObjectName("openFolderButton")
        self.horizontalLayout_7.addWidget(self.openFolderButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.fileName = QtWidgets.QLineEdit(self.groupBox)
        self.fileName.setObjectName("fileName")
        self.horizontalLayout_6.addWidget(self.fileName)
        self.fileNumber = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileNumber.sizePolicy().hasHeightForWidth())
        self.fileNumber.setSizePolicy(sizePolicy)
        self.fileNumber.setMinimumSize(QtCore.QSize(0, 0))
        self.fileNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fileNumber.setObjectName("fileNumber")
        self.horizontalLayout_6.addWidget(self.fileNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.previewText = QtWidgets.QLabel(self.groupBox)
        self.previewText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.previewText.setObjectName("previewText")
        self.horizontalLayout_10.addWidget(self.previewText)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.IsFileOverride = QtWidgets.QCheckBox(self.groupBox)
        self.IsFileOverride.setMinimumSize(QtCore.QSize(140, 0))
        self.IsFileOverride.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.IsFileOverride.setObjectName("IsFileOverride")
        self.horizontalLayout_14.addWidget(self.IsFileOverride)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.IsView = QtWidgets.QCheckBox(self.groupBox_3)
        self.IsView.setMinimumSize(QtCore.QSize(140, 0))
        self.IsView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.IsView.setObjectName("IsView")
        self.horizontalLayout_8.addWidget(self.IsView)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.IsOffscreen = QtWidgets.QCheckBox(self.groupBox_3)
        self.IsOffscreen.setMinimumSize(QtCore.QSize(140, 0))
        self.IsOffscreen.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.IsOffscreen.setObjectName("IsOffscreen")
        self.horizontalLayout_9.addWidget(self.IsOffscreen)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.IsOrnaments = QtWidgets.QCheckBox(self.groupBox_3)
        self.IsOrnaments.setMinimumSize(QtCore.QSize(140, 0))
        self.IsOrnaments.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.IsOrnaments.setObjectName("IsOrnaments")
        self.horizontalLayout_13.addWidget(self.IsOrnaments)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.formatType = QtWidgets.QComboBox(self.groupBox_3)
        self.formatType.setObjectName("formatType")
        self.horizontalLayout_5.addWidget(self.formatType)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.encodingType = QtWidgets.QComboBox(self.groupBox_3)
        self.encodingType.setMinimumSize(QtCore.QSize(90, 0))
        self.encodingType.setObjectName("encodingType")
        self.horizontalLayout_4.addWidget(self.encodingType)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.modeType = QtWidgets.QComboBox(self.groupBox_3)
        self.modeType.setObjectName("modeType")
        self.modeType.addItem("")
        self.modeType.addItem("")
        self.modeType.addItem("")
        self.horizontalLayout_11.addWidget(self.modeType)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.IsMP4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.IsMP4.setEnabled(False)
        self.IsMP4.setMinimumSize(QtCore.QSize(140, 0))
        self.IsMP4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.IsMP4.setObjectName("IsMP4")
        self.horizontalLayout_15.addWidget(self.IsMP4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.quality = QtWidgets.QSpinBox(self.groupBox_4)
        self.quality.setMinimumSize(QtCore.QSize(0, 0))
        self.quality.setMaximumSize(QtCore.QSize(40, 16777215))
        self.quality.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.quality.setMaximum(100)
        self.quality.setProperty("value", 70)
        self.quality.setObjectName("quality")
        self.horizontalLayout_3.addWidget(self.quality)
        self.qualitySlider = QtWidgets.QSlider(self.groupBox_4)
        self.qualitySlider.setMaximum(100)
        self.qualitySlider.setProperty("value", 70)
        self.qualitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.qualitySlider.setObjectName("qualitySlider")
        self.horizontalLayout_3.addWidget(self.qualitySlider)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.resolutionWidth = QtWidgets.QSpinBox(self.groupBox_4)
        self.resolutionWidth.setMaximumSize(QtCore.QSize(40, 16777215))
        self.resolutionWidth.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.resolutionWidth.setMinimum(1)
        self.resolutionWidth.setMaximum(4048)
        self.resolutionWidth.setProperty("value", 1920)
        self.resolutionWidth.setObjectName("resolutionWidth")
        self.horizontalLayout_2.addWidget(self.resolutionWidth)
        self.resolutionWidthSlider = QtWidgets.QSlider(self.groupBox_4)
        self.resolutionWidthSlider.setMinimum(1)
        self.resolutionWidthSlider.setMaximum(4048)
        self.resolutionWidthSlider.setProperty("value", 1920)
        self.resolutionWidthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.resolutionWidthSlider.setObjectName("resolutionWidthSlider")
        self.horizontalLayout_2.addWidget(self.resolutionWidthSlider)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.resolutionHeight = QtWidgets.QSpinBox(self.groupBox_4)
        self.resolutionHeight.setMaximumSize(QtCore.QSize(40, 16777215))
        self.resolutionHeight.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.resolutionHeight.setMinimum(1)
        self.resolutionHeight.setMaximum(4047)
        self.resolutionHeight.setProperty("value", 1080)
        self.resolutionHeight.setObjectName("resolutionHeight")
        self.horizontalLayout.addWidget(self.resolutionHeight)
        self.resolutionHeightSlider = QtWidgets.QSlider(self.groupBox_4)
        self.resolutionHeightSlider.setMinimum(1)
        self.resolutionHeightSlider.setMaximum(4048)
        self.resolutionHeightSlider.setProperty("value", 1080)
        self.resolutionHeightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.resolutionHeightSlider.setObjectName("resolutionHeightSlider")
        self.horizontalLayout.addWidget(self.resolutionHeightSlider)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.StartFrameLayout = QtWidgets.QHBoxLayout()
        self.StartFrameLayout.setObjectName("StartFrameLayout")
        self.startTimeLabel = QtWidgets.QLabel(self.groupBox_2)
        self.startTimeLabel.setEnabled(True)
        self.startTimeLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.startTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.StartFrameLayout.addWidget(self.startTimeLabel)
        self.startTime = QtWidgets.QSpinBox(self.groupBox_2)
        self.startTime.setEnabled(True)
        self.startTime.setMaximumSize(QtCore.QSize(40, 16777215))
        self.startTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.startTime.setMinimum(0)
        self.startTime.setMaximum(99999)
        self.startTime.setProperty("value", 0)
        self.startTime.setObjectName("startTime")
        self.StartFrameLayout.addWidget(self.startTime)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.StartFrameLayout.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.StartFrameLayout)
        self.EndFrameLayout = QtWidgets.QHBoxLayout()
        self.EndFrameLayout.setObjectName("EndFrameLayout")
        self.endTimeLabel = QtWidgets.QLabel(self.groupBox_2)
        self.endTimeLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.endTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.EndFrameLayout.addWidget(self.endTimeLabel)
        self.endTime = QtWidgets.QSpinBox(self.groupBox_2)
        self.endTime.setMaximumSize(QtCore.QSize(40, 16777215))
        self.endTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.endTime.setMinimum(0)
        self.endTime.setMaximum(99999)
        self.endTime.setProperty("value", 100)
        self.endTime.setObjectName("endTime")
        self.EndFrameLayout.addWidget(self.endTime)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.EndFrameLayout.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.EndFrameLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.startPlayblastButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPlayblastButton.setObjectName("startPlayblastButton")
        self.horizontalLayout_12.addWidget(self.startPlayblastButton)
        self.applyButton = QtWidgets.QPushButton(self.centralwidget)
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout_12.addWidget(self.applyButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_12.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "PlayblastOption", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Directory:", None, -1))
        self.openFolderButton.setText(QtWidgets.QApplication.translate("MainWindow", "📁", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "File name:", None, -1))
        self.fileName.setText(QtWidgets.QApplication.translate("MainWindow", "Cut_", None, -1))
        self.fileNumber.setText(QtWidgets.QApplication.translate("MainWindow", "001", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "(プレビュー：", None, -1))
        self.previewText.setText(QtWidgets.QApplication.translate("MainWindow", "Cut_001", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", ")", None, -1))
        self.IsFileOverride.setText(QtWidgets.QApplication.translate("MainWindow", "FileOverride", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.IsView.setText(QtWidgets.QApplication.translate("MainWindow", "View:", None, -1))
        self.IsOffscreen.setText(QtWidgets.QApplication.translate("MainWindow", "Offscreen:", None, -1))
        self.IsOrnaments.setText(QtWidgets.QApplication.translate("MainWindow", "Ornaments:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Format:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Encoding:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Mode:", None, -1))
        self.modeType.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "All Frame", None, -1))
        self.modeType.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Select Clip", None, -1))
        self.modeType.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Select Frame", None, -1))
        self.IsMP4.setText(QtWidgets.QApplication.translate("MainWindow", "Convert MP4", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Image", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Quality", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Resolution Width", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Resolution height", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Select Frame", None, -1))
        self.startTimeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Start Frame", None, -1))
        self.endTimeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "End Frame", None, -1))
        self.startPlayblastButton.setText(QtWidgets.QApplication.translate("MainWindow", "Start Playblast", None, -1))
        self.applyButton.setText(QtWidgets.QApplication.translate("MainWindow", "Apply", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))

