# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_unity_snap_importer\ui\connect_item_gui.ui'
#
# Created: Tue Oct  3 15:53:54 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(660, 67)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.type_icon_label = QtWidgets.QLabel(Form)
        self.type_icon_label.setObjectName("type_icon_label")
        self.horizontalLayout.addWidget(self.type_icon_label)
        self.type_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_label.sizePolicy().hasHeightForWidth())
        self.type_label.setSizePolicy(sizePolicy)
        self.type_label.setMinimumSize(QtCore.QSize(60, 0))
        self.type_label.setObjectName("type_label")
        self.horizontalLayout.addWidget(self.type_label)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.unity_label = QtWidgets.QLabel(Form)
        self.unity_label.setObjectName("unity_label")
        self.horizontalLayout_2.addWidget(self.unity_label)
        self.unity_name_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unity_name_label.sizePolicy().hasHeightForWidth())
        self.unity_name_label.setSizePolicy(sizePolicy)
        self.unity_name_label.setMinimumSize(QtCore.QSize(100, 0))
        self.unity_name_label.setObjectName("unity_name_label")
        self.horizontalLayout_2.addWidget(self.unity_name_label)
        self.link_label = QtWidgets.QLabel(Form)
        self.link_label.setObjectName("link_label")
        self.horizontalLayout_2.addWidget(self.link_label)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(20, 0))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.maya_label = QtWidgets.QLabel(Form)
        self.maya_label.setObjectName("maya_label")
        self.horizontalLayout_2.addWidget(self.maya_label)
        self.maya_name_line = QtWidgets.QLineEdit(Form)
        self.maya_name_line.setReadOnly(True)
        self.maya_name_line.setObjectName("maya_name_line")
        self.horizontalLayout_2.addWidget(self.maya_name_line)
        self.name_set_button = QtWidgets.QPushButton(Form)
        self.name_set_button.setObjectName("name_set_button")
        self.horizontalLayout_2.addWidget(self.name_set_button)
        self.name_del_button = QtWidgets.QPushButton(Form)
        self.name_del_button.setObjectName("name_del_button")
        self.horizontalLayout_2.addWidget(self.name_del_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.checks_layout = QtWidgets.QHBoxLayout()
        self.checks_layout.setSpacing(10)
        self.checks_layout.setObjectName("checks_layout")
        self.horizontalLayout_4.addLayout(self.checks_layout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.type_icon_label.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
        self.type_label.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
        self.unity_label.setText(QtWidgets.QApplication.translate("Form", "Unity名:  ", None, -1))
        self.unity_name_label.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
        self.link_label.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
        self.maya_label.setText(QtWidgets.QApplication.translate("Form", "Maya名: ", None, -1))
        self.name_set_button.setText(QtWidgets.QApplication.translate("Form", "Set", None, -1))
        self.name_del_button.setText(QtWidgets.QApplication.translate("Form", "Del", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "オプション", None, -1))

