# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tech-designer\maya_legacy\scripts\Project_Gallop\glp_unity_snap_importer\ui\snap_importer_gui.ui'
#
# Created: Tue Oct  3 14:28:15 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.snap_dir_path_line = QtWidgets.QLineEdit(self.groupBox)
        self.snap_dir_path_line.setObjectName("snap_dir_path_line")
        self.horizontalLayout.addWidget(self.snap_dir_path_line)
        self.snap_dir_set_button = QtWidgets.QPushButton(self.groupBox)
        self.snap_dir_set_button.setObjectName("snap_dir_set_button")
        self.horizontalLayout.addWidget(self.snap_dir_set_button)
        self.snap_dir_update_button = QtWidgets.QPushButton(self.groupBox)
        self.snap_dir_update_button.setObjectName("snap_dir_update_button")
        self.horizontalLayout.addWidget(self.snap_dir_update_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.snap_file_list = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snap_file_list.sizePolicy().hasHeightForWidth())
        self.snap_file_list.setSizePolicy(sizePolicy)
        self.snap_file_list.setMinimumSize(QtCore.QSize(0, 100))
        self.snap_file_list.setMaximumSize(QtCore.QSize(16777215, 100))
        self.snap_file_list.setObjectName("snap_file_list")
        self.verticalLayout.addWidget(self.snap_file_list)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.auto_set_root_button = QtWidgets.QPushButton(self.groupBox_4)
        self.auto_set_root_button.setObjectName("auto_set_root_button")
        self.verticalLayout_5.addWidget(self.auto_set_root_button)
        self.root_connection_list = QtWidgets.QListWidget(self.groupBox_4)
        self.root_connection_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.root_connection_list.setObjectName("root_connection_list")
        self.verticalLayout_5.addWidget(self.root_connection_list)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.orient_axis_obj_radio = QtWidgets.QRadioButton(self.groupBox_5)
        self.orient_axis_obj_radio.setObjectName("orient_axis_obj_radio")
        self.horizontalLayout_3.addWidget(self.orient_axis_obj_radio)
        self.orient_world_radio = QtWidgets.QRadioButton(self.groupBox_5)
        self.orient_world_radio.setChecked(True)
        self.orient_world_radio.setObjectName("orient_world_radio")
        self.horizontalLayout_3.addWidget(self.orient_world_radio)
        self.orient_local_radio = QtWidgets.QRadioButton(self.groupBox_5)
        self.orient_local_radio.setObjectName("orient_local_radio")
        self.horizontalLayout_3.addWidget(self.orient_local_radio)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.axis_obj_connection_list = QtWidgets.QListWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axis_obj_connection_list.sizePolicy().hasHeightForWidth())
        self.axis_obj_connection_list.setSizePolicy(sizePolicy)
        self.axis_obj_connection_list.setMaximumSize(QtCore.QSize(16777215, 40))
        self.axis_obj_connection_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.axis_obj_connection_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.axis_obj_connection_list.setResizeMode(QtWidgets.QListView.Adjust)
        self.axis_obj_connection_list.setObjectName("axis_obj_connection_list")
        self.verticalLayout_7.addWidget(self.axis_obj_connection_list)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.connect_button = QtWidgets.QPushButton(self.groupBox_2)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout_2.addWidget(self.connect_button)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_slider = QtWidgets.QSlider(self.groupBox_3)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.horizontalLayout_2.addWidget(self.frame_slider)
        self.current_frame_label = QtWidgets.QLabel(self.groupBox_3)
        self.current_frame_label.setMinimumSize(QtCore.QSize(20, 0))
        self.current_frame_label.setObjectName("current_frame_label")
        self.horizontalLayout_2.addWidget(self.current_frame_label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.frame_count_label = QtWidgets.QLabel(self.groupBox_3)
        self.frame_count_label.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_count_label.setObjectName("frame_count_label")
        self.horizontalLayout_2.addWidget(self.frame_count_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "SnapDataの取得", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Snapフォルダパス", None, -1))
        self.snap_dir_set_button.setText(QtWidgets.QApplication.translate("MainWindow", "登録", None, -1))
        self.snap_dir_update_button.setText(QtWidgets.QApplication.translate("MainWindow", "更新", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "コネクション", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "ルートの割り当て", None, -1))
        self.auto_set_root_button.setText(QtWidgets.QApplication.translate("MainWindow", "オブジェクト名から自動割り当て", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "ルートの再現座標オプション", None, -1))
        self.orient_axis_obj_radio.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Unityで録画した基準オブジェクトとシーンのオブジェクトを紐づけ、そのオブジェクトのローカル座標でルートを再現します", None, -1))
        self.orient_axis_obj_radio.setText(QtWidgets.QApplication.translate("MainWindow", "基準オブジェクト指定", None, -1))
        self.orient_world_radio.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Unityで記録したワールド座標でルートを再現します\n"
"※マテリアル指定のライトなどワールド座標系のパラメーターの再現度が向上します", None, -1))
        self.orient_world_radio.setText(QtWidgets.QApplication.translate("MainWindow", "ワールド", None, -1))
        self.orient_local_radio.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Unityで記録したローカル座標でルートを再現します", None, -1))
        self.orient_local_radio.setText(QtWidgets.QApplication.translate("MainWindow", "ローカル", None, -1))
        self.connect_button.setText(QtWidgets.QApplication.translate("MainWindow", "コネクト", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "再現フレーム", None, -1))
        self.current_frame_label.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "/", None, -1))
        self.frame_count_label.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))

