!!python/object:shr.cutscene.sequencer.config.data.ActorConfig
version: 1.0.0
actor_import_path: z:/mtk/work/resources/animations/clips/player/workscenes/anm_ply00_m_000_rig.ma
object_type: !!python/object/apply:shr.cutscene.sequencer.config.data.ObjectType
  - 1
recommended_name: Player_001
recommended_animaton_path: Z:/mtk/work/resources/animations/clips/player
necessary_nodes:
  - "{namespace}::rig"
  - "{namespace}::root"
unnecessary_nodes:
  - "{namespace}::rig"
  - "{namespace}::root"

binding_data: !!python/object:shr.cutscene.sequencer.config.data.BindingData
  binding_condition: "{namespace}::rig"
  is_binding_solo: false
  node_type: nurbsCurve
