global proc CyBatchRender(string $targetPath)
{	
	//レンダリング用のテキスト作成
	string $renderTextPath = python("import CyBatchRender;reload(CyBatchRender);CyBatchRender.Execute(\"" + $targetPath + "\")");

	//ファイルチェック後、レンダリング開始
	$existFile = `filetest -f $renderTextPath`;

	if($existFile)
	{
		print "Rendering...";

		system($renderTextPath);
		
		sysFile -delete $renderTextPath;

		print "Complete!\r\n";
	}
}